\
\ @file vrefbuf.fs
\ @brief Voltage reference buffer
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

.include ../common.fs

\
\ @brief VREFBUF control and status register
\ Address offset: 0x00
\ Reset value: 0x00000002
\

$00000001 constant VREFBUF_VREFBUF_CSR_ENVR                         \ Voltage reference buffer mode enable This bit is used to enable the voltage reference buffer mode.
$00000002 constant VREFBUF_VREFBUF_CSR_HIZ                          \ High impedance mode This bit controls the analog switch to connect or not the V<sub>REF+</sub> pin. Refer to Table 229: VREF buffer modes for the mode descriptions depending on ENVR bit configuration.
$00000008 constant VREFBUF_VREFBUF_CSR_VRR                          \ Voltage reference buffer ready
$00000070 constant VREFBUF_VREFBUF_CSR_VRS                          \ Voltage reference scale These bits select the value generated by the voltage reference buffer. VRS = 000: VREFBUF0 voltage selected. VRS = 001: VREFBUF1 voltage selected. VRS = 010: VREFBUF2 voltage selected. VRS = 011: VREFBUF3 voltage selected. Others: Reserved Refer to the product datasheet for each VREFBUFx voltage setting value. Note: The software can program this bitfield only when the VREFBUF is disabled (ENVR=0).


\
\ @brief VREFBUF calibration control register
\ Address offset: 0x04
\ Reset value: 0x00000000
\

$0000003f constant VREFBUF_VREFBUF_CCR_TRIM                         \ Trimming code The TRIM code is a 6-bit unsigned data (minimum 000000, maximum 111111) that is set and updated according the mechanism described below. Reset: TRIM[5:0] is automatically initialized with the VRS = 0 trimming value stored in the flash memory during the production test. VRS change: TRIM[5:0] is automatically initialized with the trimming value (corresponding to VRS setting) stored in the flash memory during the production test. Write in TRIM[5:0]: User can modify the TRIM[5:0] with an arbitrary value. This is permanently disabling the control of the trimming value with VRS (until the device is reset). Note: If the user application performs the trimming, the trimming code must start from 000000 to 111111 in ascending order.


\
\ @brief Voltage reference buffer
\
$58003c00 constant VREFBUF_VREFBUF_CSR  \ offset: 0x00 : VREFBUF control and status register
$58003c04 constant VREFBUF_VREFBUF_CCR  \ offset: 0x04 : VREFBUF calibration control register

