\
\ @file crs.fs
\ @brief Clock Recovery System
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

[ifndef] CRS_DEF

  [ifdef] CRS_CR_DEF
    \
    \ @brief CRS control register
    \ Address offset: 0x00
    \ Reset value: 0x00002000
    \
    $00 constant CRS_SYNCOKIE                   \ [0x00] SYNC event OK interrupt enable
    $01 constant CRS_SYNCWARNIE                 \ [0x01] SYNC warning interrupt enable
    $02 constant CRS_ERRIE                      \ [0x02] Synchronization or trimming error interrupt enable
    $03 constant CRS_ESYNCIE                    \ [0x03] Expected SYNC interrupt enable
    $05 constant CRS_CEN                        \ [0x05] Frequency error counter enable This bit enables the oscillator clock for the frequency error counter. When this bit is set, the CRS_CFGR register is write-protected and cannot be modified.
    $06 constant CRS_AUTOTRIMEN                 \ [0x06] Automatic trimming enable This bit enables the automatic hardware adjustment of TRIM bits according to the measured frequency error between two SYNC events. If this bit is set, the TRIM bits are read-only. The TRIM value can be adjusted by hardware by one or two steps at a time, depending on the measured frequency error value. Refer to Section7.3.4: Frequency error evaluation and automatic trimming for more details.
    $07 constant CRS_SWSYNC                     \ [0x07] Generate software SYNC event This bit is set by software in order to generate a software SYNC event. It is automatically cleared by hardware.
    $08 constant CRS_TRIM                       \ [0x08 : 6] HSI48 oscillator smooth trimming These bits provide a user-programmable trimming value to the HSI48 oscillator. They can be programmed to adjust to variations in voltage and temperature that influence the frequency of the HSI48. The default value is 32, which corresponds to the middle of the trimming interval. The trimming step is around 67 kHz between two consecutive TRIM steps. A higher TRIM value corresponds to a higher output frequency. When the AUTOTRIMEN bit is set, this field is controlled by hardware and is read-only.
  [then]


  [ifdef] CRS_CFGR_DEF
    \
    \ @brief This register can be written only when the frequency error counter is disabled (CEN bit is cleared in CRS_CR). When the counter is enabled, this register is write-protected.
    \ Address offset: 0x04
    \ Reset value: 0x2022BB7F
    \
    $00 constant CRS_RELOAD                     \ [0x00 : 16] Counter reload value RELOAD is the value to be loaded in the frequency error counter with each SYNC event. Refer to Section7.3.3: Frequency error measurement for more details about counter behavior.
    $10 constant CRS_FELIM                      \ [0x10 : 8] Frequency error limit FELIM contains the value to be used to evaluate the captured frequency error value latched in the FECAP[15:0] bits of the CRS_ISR register. Refer to Section7.3.4: Frequency error evaluation and automatic trimming for more details about FECAP evaluation.
    $18 constant CRS_SYNCDIV                    \ [0x18 : 3] SYNC divider These bits are set and cleared by software to control the division factor of the SYNC signal.
    $1c constant CRS_SYNCSRC                    \ [0x1c : 2] SYNC signal source selection These bits are set and cleared by software to select the SYNC signal source. Note: When using USB LPM (Link Power Management) and the device is in Sleep mode, the periodic USB SOF will not be generated by the host. No SYNC signal will therefore be provided to the CRS to calibrate the HSI48 on the run. To guarantee the required clock precision after waking up from Sleep mode, the LSE or reference clock on the GPIOs should be used as SYNC signal.
    $1f constant CRS_SYNCPOL                    \ [0x1f] SYNC polarity selection This bit is set and cleared by software to select the input polarity for the SYNC signal source.
  [then]


  [ifdef] CRS_ISR_DEF
    \
    \ @brief CRS interrupt and status register
    \ Address offset: 0x08
    \ Reset value: 0x00000000
    \
    $00 constant CRS_SYNCOKF                    \ [0x00] SYNC event OK flag This flag is set by hardware when the measured frequency error is smaller than FELIM * 3. This means that either no adjustment of the TRIM value is needed or that an adjustment by one trimming step is enough to compensate the frequency error. An interrupt is generated if the SYNCOKIE bit is set in the CRS_CR register. It is cleared by software by setting the SYNCOKC bit in the CRS_ICR register.
    $01 constant CRS_SYNCWARNF                  \ [0x01] SYNC warning flag This flag is set by hardware when the measured frequency error is greater than or equal to FELIM * 3, but smaller than FELIM * 128. This means that to compensate the frequency error, the TRIM value must be adjusted by two steps or more. An interrupt is generated if the SYNCWARNIE bit is set in the CRS_CR register. It is cleared by software by setting the SYNCWARNC bit in the CRS_ICR register.
    $02 constant CRS_ERRF                       \ [0x02] Error flag This flag is set by hardware in case of any synchronization or trimming error. It is the logical OR of the TRIMOVF, SYNCMISS and SYNCERR bits. An interrupt is generated if the ERRIE bit is set in the CRS_CR register. It is cleared by software in reaction to setting the ERRC bit in the CRS_ICR register, which clears the TRIMOVF, SYNCMISS and SYNCERR bits.
    $03 constant CRS_ESYNCF                     \ [0x03] Expected SYNC flag This flag is set by hardware when the frequency error counter reached a zero value. An interrupt is generated if the ESYNCIE bit is set in the CRS_CR register. It is cleared by software by setting the ESYNCC bit in the CRS_ICR register.
    $08 constant CRS_SYNCERR                    \ [0x08] SYNC error This flag is set by hardware when the SYNC pulse arrives before the ESYNC event and the measured frequency error is greater than or equal to FELIM * 128. This means that the frequency error is too big (internal frequency too low) to be compensated by adjusting the TRIM value, and that some other action should be taken. An interrupt is generated if the ERRIE bit is set in the CRS_CR register. It is cleared by software by setting the ERRC bit in the CRS_ICR register.
    $09 constant CRS_SYNCMISS                   \ [0x09] SYNC missed This flag is set by hardware when the frequency error counter reached value FELIM * 128 and no SYNC was detected, meaning either that a SYNC pulse was missed or that the frequency error is too big (internal frequency too high) to be compensated by adjusting the TRIM value, and that some other action should be taken. At this point, the frequency error counter is stopped (waiting for a next SYNC) and an interrupt is generated if the ERRIE bit is set in the CRS_CR register. It is cleared by software by setting the ERRC bit in the CRS_ICR register.
    $0a constant CRS_TRIMOVF                    \ [0x0a] Trimming overflow or underflow This flag is set by hardware when the automatic trimming tries to over- or under-flow the TRIM value. An interrupt is generated if the ERRIE bit is set in the CRS_CR register. It is cleared by software by setting the ERRC bit in the CRS_ICR register.
    $0f constant CRS_FEDIR                      \ [0x0f] Frequency error direction FEDIR is the counting direction of the frequency error counter latched in the time of the last SYNC event. It shows whether the actual frequency is below or above the target.
    $10 constant CRS_FECAP                      \ [0x10 : 16] Frequency error capture FECAP is the frequency error counter value latched in the time of the last SYNC event. Refer to Section7.3.4: Frequency error evaluation and automatic trimming for more details about FECAP usage.
  [then]


  [ifdef] CRS_ICR_DEF
    \
    \ @brief CRS interrupt flag clear register
    \ Address offset: 0x0C
    \ Reset value: 0x00000000
    \
    $00 constant CRS_SYNCOKC                    \ [0x00] SYNC event OK clear flag Writing 1 to this bit clears the SYNCOKF flag in the CRS_ISR register.
    $01 constant CRS_SYNCWARNC                  \ [0x01] SYNC warning clear flag Writing 1 to this bit clears the SYNCWARNF flag in the CRS_ISR register.
    $02 constant CRS_ERRC                       \ [0x02] Error clear flag Writing 1 to this bit clears TRIMOVF, SYNCMISS and SYNCERR bits and consequently also the ERRF flag in the CRS_ISR register.
    $03 constant CRS_ESYNCC                     \ [0x03] Expected SYNC clear flag Writing 1 to this bit clears the ESYNCF flag in the CRS_ISR register.
  [then]

  \
  \ @brief Clock Recovery System
  \
  $00 constant CRS_CR                   \ CRS control register
  $04 constant CRS_CFGR                 \ This register can be written only when the frequency error counter is disabled (CEN bit is cleared in CRS_CR). When the counter is enabled, this register is write-protected.
  $08 constant CRS_ISR                  \ CRS interrupt and status register
  $0C constant CRS_ICR                  \ CRS interrupt flag clear register

: CRS_DEF ; [then]
