\
\ @file vrefbuf.fs
\ @brief VREFBUF
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

.include ../common.fs

\
\ @brief VREFBUF control and status register
\ Address offset: 0x00
\ Reset value: 0x00000002
\

$00000001 constant VREFBUF_VREFBUF_CSR_ENVR                         \ Voltage reference buffer mode enable This bit is used to enable the voltage reference buffer mode.
$00000002 constant VREFBUF_VREFBUF_CSR_HIZ                          \ High impedance mode This bit controls the analog switch to connect or not the VREF+ pin. Refer to Table196: VREF buffer modes for the mode descriptions depending on ENVR bit configuration.
$00000008 constant VREFBUF_VREFBUF_CSR_VRR                          \ Voltage reference buffer ready
$00000070 constant VREFBUF_VREFBUF_CSR_VRS                          \ Voltage reference scale These bits select the value generated by the voltage reference buffer. Other: Reserved


\
\ @brief VREFBUF calibration control register
\ Address offset: 0x04
\ Reset value: 0x00000000
\

$0000003f constant VREFBUF_VREFBUF_CCR_TRIM                         \ Trimming code These bits are automatically initialized after reset with the trimming value stored in the Flash memory during the production test. Writing into these bits allows to tune the internal reference buffer voltage.


\
\ @brief VREFBUF
\
$58003c00 constant VREFBUF_VREFBUF_CSR  \ offset: 0x00 : VREFBUF control and status register
$58003c04 constant VREFBUF_VREFBUF_CCR  \ offset: 0x04 : VREFBUF calibration control register

