\
\ @file adc.fs
\ @brief ADC address block description
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

[ifndef] ADC_DEF

  [ifdef] ADC_VERSION_ID_DEF
    \
    \ @brief VERSION_ID register
    \ Address offset: 0x00
    \ Reset value: 0x00000020
    \
    $00 constant ADC_VERSION_ID                 \ [0x00 : 8] version of the embedded IP.
  [then]


  [ifdef] ADC_CONF_DEF
    \
    \ @brief ADC configuration register
    \ Address offset: 0x04
    \ Reset value: 0x00020002
    \
    $00 constant ADC_CONT                       \ [0x00] regular sequence runs continuously when ADC mode is enabled
    $01 constant ADC_SEQUENCE                   \ [0x01] enable the sequence mode (active by default)
    $02 constant ADC_SEQ_LEN                    \ [0x02 : 4] number of conversions in a regular sequence
    $06 constant ADC_SMPS_SYNCHRO_ENA           \ [0x06] synchronize the ADC start conversion with a pulse generated by the
    $07 constant ADC_OP_MODE                    \ [0x07 : 2] ADC mode selection (= data path selection)
    $0b constant ADC_SAMPLE_RATE                \ [0x0b : 2] conversion rate of ADC
    $0d constant ADC_DMA_DS_ENA                 \ [0x0d] enable DMA mode for Down Sampler data path
    $0e constant ADC_DMA_DF_ENA                 \ [0x0e] enable DMA mode for Decimation Filter data path
    $0f constant ADC_OVR_DS_CFG                 \ [0x0f] Down Sampler overrun configuration
    $10 constant ADC_OVR_DF_CFG                 \ [0x10] decimation overrun configuration
    $11 constant ADC_BIT_INVERT_SN              \ [0x11] invert bit to bit the ADC data output when a single
    $12 constant ADC_BIT_INVERT_DIFF            \ [0x12] invert bit to bit the ADC data output when a differential
    $13 constant ADC_ADC_CONT_1V2               \ [0x13] select the input sampling method
    $14 constant ADC_VBIAS_PRECH_FORCE          \ [0x14] possibility to keep the VBIAS_PRECH enabled to deactivate the filter
  [then]


  [ifdef] ADC_CTRL_DEF
    \
    \ @brief ADC control register
    \ Address offset: 0x08
    \ Reset value: 0x00000000
    \
    $00 constant ADC_ADC_ON_OFF                 \ [0x00] ADC_ON_OFF: – 0: power off the ADC – 1: power on the ADC
    $01 constant ADC_START_CON                  \ [0x01] generate a start pulse to initiate an ADC conversion
    $02 constant ADC_STOP_OP_MOD                \ [0x02] stop the on-going OP_MODE (ADC mode, Analog audio mode, Full
    $03 constant ADC_DIG_AUD_MODE               \ [0x03] enable the digital audio mode (the data path uses the decimation filter)
    $04 constant ADC_TEST_MODE                  \ [0x04] select the functional or the test mode of the ADC
    $05 constant ADC_ADC_LDO_ENA                \ [0x05] enable the LDO associated to the ADC block
  [then]


  [ifdef] ADC_OCM_CTRL_DEF
    \
    \ @brief Occasionnal mode control register
    \ Address offset: 0x0C
    \ Reset value: 0x00000000
    \
    $00 constant ADC_OCM_SRC                    \ [0x00] select the occasional conversion source
    $01 constant ADC_OCM_ENA                    \ [0x01] start occasional conversion in analog audio and full modes
  [then]


  [ifdef] ADC_PGA_CONF_DEF
    \
    \ @brief PGA configuration register
    \ Address offset: 0x10
    \ Reset value: 0x00000000
    \
    $00 constant ADC_PGA_GAIN                   \ [0x00 : 4] from 6 to 30 dB
    $04 constant ADC_PGA_BIAS                   \ [0x04 : 3] set the microphone bias voltage
  [then]


  [ifdef] ADC_SWITCH_DEF
    \
    \ @brief ADC switch control for Input Selection
    \ Address offset: 0x14
    \ Reset value: 0x00000000
    \
    $00 constant ADC_SE_VIN_0                   \ [0x00 : 2] input voltage for VINM[0] / VINP[0]-VINM[0]
    $02 constant ADC_SE_VIN_1                   \ [0x02 : 2] input voltage for VINM[1] / VINP[1]-VINM[1]
    $04 constant ADC_SE_VIN_2                   \ [0x04 : 2] input voltage for VINM[2] / VINP[2]-VINM[2]
    $06 constant ADC_SE_VIN_3                   \ [0x06 : 2] input voltage for VINM[3] / VINP[3]-VINM[3]
    $08 constant ADC_SE_VIN_4                   \ [0x08 : 2] input voltage for VINP[0]
    $0a constant ADC_SE_VIN_5                   \ [0x0a : 2] input voltage for VINP[1]
    $0c constant ADC_SE_VIN_6                   \ [0x0c : 2] input voltage for VINP[2]
    $0e constant ADC_SE_VIN_7                   \ [0x0e : 2] input voltage for VINP[3]
  [then]


  [ifdef] ADC_DF_CONF_DEF
    \
    \ @brief Decimation filter configuration register
    \ Address offset: 0x18
    \ Reset value: 0x00003015
    \
    $00 constant ADC_DF_CIC_DEC_FACTOR          \ [0x00 : 7] DF_CIC_DEC_FACTOR
    $07 constant ADC_DF_CIC_DHF                 \ [0x07] CIC filter decimator half factor
    $08 constant ADC_DF_ITP1P2                  \ [0x08] 1.2 fractional interpolator enable
    $09 constant ADC_DF_I_U2S                   \ [0x09] select signed/unsigned format for input
    $0a constant ADC_DF_O_S2U                   \ [0x0a] select signed/unsigned format for data output
    $0b constant ADC_PDM_RATE                   \ [0x0b : 4] select the PDM clock rate.
    $0f constant ADC_DF_MICROL_RN               \ [0x0f] left/right channel selection on digital microphone
    $10 constant ADC_DF_HPF_EN                  \ [0x10] high pass filter enable.
    $11 constant ADC_DF_HALF_D_EN               \ [0x11] half dynamic enable.
  [then]


  [ifdef] ADC_DS_CONF_DEF
    \
    \ @brief Downsampler configuration register
    \ Address offset: 0x1C
    \ Reset value: 0x00000000
    \
    $00 constant ADC_DS_RATIO                   \ [0x00 : 3] program the Down Sampler ratio (N factor)
    $03 constant ADC_DS_WIDTH                   \ [0x03 : 3] program the Down Sampler width of data output (DSDTATA)
  [then]


  [ifdef] ADC_SEQ_1_DEF
    \
    \ @brief ADC regular sequence configuration register 1
    \ Address offset: 0x20
    \ Reset value: 0x00000000
    \
    $00 constant ADC_SEQ0                       \ [0x00 : 4] channel number code for first conversion of the sequence
    $04 constant ADC_SEQ1                       \ [0x04 : 4] channel number code for second conversion of the sequence.
    $08 constant ADC_SEQ2                       \ [0x08 : 4] channel number code for 3rd conversion of the sequence.
    $0c constant ADC_SEQ3                       \ [0x0c : 4] channel number code for 4th conversion of the sequence.
    $10 constant ADC_SEQ4                       \ [0x10 : 4] channel number code for 5th conversion of the sequence.
    $14 constant ADC_SEQ5                       \ [0x14 : 4] channel number code for 6th conversion of the sequence.
    $18 constant ADC_SEQ6                       \ [0x18 : 4] channel number code for 7th conversion of the sequence.
    $1c constant ADC_SEQ7                       \ [0x1c : 4] channel number code for 8th conversion of the sequence.
  [then]


  [ifdef] ADC_SEQ_2_DEF
    \
    \ @brief ADC regular sequence configuration register 2
    \ Address offset: 0x24
    \ Reset value: 0x00000000
    \
    $00 constant ADC_SEQ8                       \ [0x00 : 4] channel number code for 9th conversion of the sequence
    $04 constant ADC_SEQ9                       \ [0x04 : 4] channel number code for 10th conversion of the sequence.
    $08 constant ADC_SEQ10                      \ [0x08 : 4] channel number code for 11th conversion of the sequence.
    $0c constant ADC_SEQ11                      \ [0x0c : 4] channel number code for 12th conversion of the sequence.
    $10 constant ADC_SEQ12                      \ [0x10 : 4] channel number code for 13th conversion of the sequence.
    $14 constant ADC_SEQ13                      \ [0x14 : 4] channel number code for 14th conversion of the sequence.
    $18 constant ADC_SEQ14                      \ [0x18 : 4] channel number code for 15th conversion of the sequence.
    $1c constant ADC_SEQ15                      \ [0x1c : 4] channel number code for 16th conversion of the sequence.
  [then]


  [ifdef] ADC_COMP_1_DEF
    \
    \ @brief ADC Gain and offset correction values register 1
    \ Address offset: 0x28
    \ Reset value: 0x00000555
    \
    $00 constant ADC_GAIN1                      \ [0x00 : 12] first calibration point: gain AUXADC_GAIN_1V2[11:0]
    $0c constant ADC_OFFSET1                    \ [0x0c : 7] first calibration point: signed offset compensation[6:0]
  [then]


  [ifdef] ADC_COMP_2_DEF
    \
    \ @brief ADC Gain and offset correction values register 2
    \ Address offset: 0x2C
    \ Reset value: 0x00000555
    \
    $00 constant ADC_GAIN2                      \ [0x00 : 12] second calibration point: gain AUXADC_GAIN_1V2[11:0]
    $0c constant ADC_OFFSET2                    \ [0x0c : 7] second calibration point: signed offset compensation[6:0]
  [then]


  [ifdef] ADC_COMP_3_DEF
    \
    \ @brief ADC Gain and offset correction values register 3
    \ Address offset: 0x30
    \ Reset value: 0x00000555
    \
    $00 constant ADC_GAIN3                      \ [0x00 : 12] third calibration point: gain AUXADC_GAIN_1V2[11:0]
    $0c constant ADC_OFFSET3                    \ [0x0c : 7] third calibration point: signed offset compensation[6:0]
  [then]


  [ifdef] ADC_COMP_4_DEF
    \
    \ @brief ADC Gain and offset correction values register 4
    \ Address offset: 0x34
    \ Reset value: 0x00000555
    \
    $00 constant ADC_GAIN4                      \ [0x00 : 12] fourth calibration point: gain AUXADC_GAIN_1V2[11:0]
    $0c constant ADC_OFFSET4                    \ [0x0c : 7] fourth calibration point: signed offset compensation[6:0]
  [then]


  [ifdef] ADC_COMP_SEL_DEF
    \
    \ @brief ADC Gain and Offset selection values register
    \ Address offset: 0x38
    \ Reset value: 0x00000000
    \
    $00 constant ADC_GAIN_OFFSET0               \ [0x00 : 2] gain / offset used in ADC single negative mode with Vinput range = 1.2V
    $02 constant ADC_GAIN_OFFSET1               \ [0x02 : 2] gain / offset used in ADC single positive mode with Vinput range = 1.2V
    $04 constant ADC_GAIN_OFFSET2               \ [0x04 : 2] gain / offset used in ADC differential mode with Vinput range = 1.2V
    $06 constant ADC_GAIN_OFFSET3               \ [0x06 : 2] gain / offset used in ADC single negative mode with Vinput range = 2.4V
    $08 constant ADC_GAIN_OFFSET4               \ [0x08 : 2] gain / offset used in ADC single positive mode with Vinput range = 2.4V
    $0a constant ADC_GAIN_OFFSET5               \ [0x0a : 2] gain / offset used in ADC differential mode with Vinput range = 2.4V
    $0c constant ADC_GAIN_OFFSET6               \ [0x0c : 2] gain / offset used in ADC single negative mode with Vinput range = 3.6V
    $0e constant ADC_GAIN_OFFSET7               \ [0x0e : 2] gain / offset used in ADC single positive mode with Vinput range = 3.6V
    $10 constant ADC_GAIN_OFFSET8               \ [0x10 : 2] gain / offset used in ADC differential mode with Vinput range = 3.6V
  [then]


  [ifdef] ADC_WD_TH_DEF
    \
    \ @brief High/low limits for event monitoring a channel register
    \ Address offset: 0x3C
    \ Reset value: 0x0FFF0000
    \
    $00 constant ADC_WD_LT                      \ [0x00 : 12] analog watchdog low level threshold.
    $10 constant ADC_WD_HT                      \ [0x10 : 12] analog watchdog high level threshold.
  [then]


  [ifdef] ADC_WD_CONF_DEF
    \
    \ @brief Channel selection for event monitoring register
    \ Address offset: 0x40
    \ Reset value: 0x00000000
    \
    $00 constant ADC_AWD_CHX                    \ [0x00 : 16] analog watchdog channel selection to define which input channel(s) need to be guarded by the watchdog.
  [then]


  [ifdef] ADC_DS_DATAOUT_DEF
    \
    \ @brief Downsampler Data output register
    \ Address offset: 0x44
    \ Reset value: 0x00000000
    \
    $00 constant ADC_DS_DATA                    \ [0x00 : 16] contain the converted data at the output of the Down Sampler
  [then]


  [ifdef] ADC_DF_DATAOUT_DEF
    \
    \ @brief Decimation filter Data output register
    \ Address offset: 0x48
    \ Reset value: 0x00000000
    \
    $00 constant ADC_DF_DATA                    \ [0x00 : 16] contain the converted data at the output of the decimation filter.
  [then]


  [ifdef] ADC_IRQ_STATUS_DEF
    \
    \ @brief Interrupt Status register
    \ Address offset: 0x4C
    \ Reset value: 0x00000000
    \
    $00 constant ADC_EOC_IRQ                    \ [0x00] (Used in test mode only): set when the ADC conversion is completed.
    $01 constant ADC_EODS_IRQ                   \ [0x01] set when the Down Sampler conversion is completed.
    $02 constant ADC_EODF_IRQ                   \ [0x02] set when the decimation filter conversion is completed
    $03 constant ADC_EOS_IRQ                    \ [0x03] set when a sequence of conversion is completed
    $04 constant ADC_AWD_IRQ                    \ [0x04] set when an analog watchdog event occurs
    $05 constant ADC_OVR_DS_IRQ                 \ [0x05] set to indicate a Down Sampler overrun (at least one data is lost)
    $06 constant ADC_OVR_DF_IRQ                 \ [0x06] set to indicate a decimation filter overrun (a data is lost)
    $07 constant ADC_DF_OVRFL_IRQ               \ [0x07] set to indicate the decimation filter is saturated.
  [then]


  [ifdef] ADC_IRQ_ENABLE_DEF
    \
    \ @brief Enable/disable Interrupts
    \ Address offset: 0x50
    \ Reset value: 0x00000000
    \
    $00 constant ADC_EOC_IRQ_ENA                \ [0x00] (Used in test mode only): End of ADC conversion interrupt enable
    $01 constant ADC_EODS_IRQ_ENA               \ [0x01] End of conversion interrupt enable for the Down Sampler output
    $02 constant ADC_EODF_IRQ_ENA               \ [0x02] End of conversion interrupt enable for the decimation filter output
    $03 constant ADC_EOS_IRQ_ENA                \ [0x03] End of regular sequence interrupt enable
    $04 constant ADC_AWD_IRQ_ENA                \ [0x04] analog watchdog interrupt enable
    $05 constant ADC_OVR_DS_IRQ_ENA             \ [0x05] Down Sampler overrun interrupt enable
    $06 constant ADC_OVR_DF_IRQ_ENA             \ [0x06] decimation filter overrun interrupt enable
    $07 constant ADC_DF_OVRFL_IRQ_ENA           \ [0x07] decimation filter saturation interrupt enable
  [then]


  [ifdef] ADC_TIMER_CONF_DEF
    \
    \ @brief Time to add after an LDO Enable or ADC Enable to let the HW to be stable before using it
    \ Address offset: 0x54
    \ Reset value: 0x00009628
    \
    $00 constant ADC_ADC_LDO_DELAY              \ [0x00 : 8] define the duration of a waiting time to be inserted between the ADC_LDO enable and the ADC ON to let time to the LDO to stabilize before starting a conversion.
    $08 constant ADC_VBIAS_PRECH_DELAY          \ [0x08 : 8] define the duration of a waiting time starting at rising edge of PGA_EN signal and corresponding to the VBIAS precharge duration
    $10 constant ADC_PRECH_DELAY_SEL            \ [0x10] Select the time step PD_STEP for the VBIAS_PRECH_DELAY timer
  [then]

  \
  \ @brief ADC address block description
  \
  $00 constant ADC_VERSION_ID           \ VERSION_ID register
  $04 constant ADC_CONF                 \ ADC configuration register
  $08 constant ADC_CTRL                 \ ADC control register
  $0C constant ADC_OCM_CTRL             \ Occasionnal mode control register
  $10 constant ADC_PGA_CONF             \ PGA configuration register
  $14 constant ADC_SWITCH               \ ADC switch control for Input Selection
  $18 constant ADC_DF_CONF              \ Decimation filter configuration register
  $1C constant ADC_DS_CONF              \ Downsampler configuration register
  $20 constant ADC_SEQ_1                \ ADC regular sequence configuration register 1
  $24 constant ADC_SEQ_2                \ ADC regular sequence configuration register 2
  $28 constant ADC_COMP_1               \ ADC Gain and offset correction values register 1
  $2C constant ADC_COMP_2               \ ADC Gain and offset correction values register 2
  $30 constant ADC_COMP_3               \ ADC Gain and offset correction values register 3
  $34 constant ADC_COMP_4               \ ADC Gain and offset correction values register 4
  $38 constant ADC_COMP_SEL             \ ADC Gain and Offset selection values register
  $3C constant ADC_WD_TH                \ High/low limits for event monitoring a channel register
  $40 constant ADC_WD_CONF              \ Channel selection for event monitoring register
  $44 constant ADC_DS_DATAOUT           \ Downsampler Data output register
  $48 constant ADC_DF_DATAOUT           \ Decimation filter Data output register
  $4C constant ADC_IRQ_STATUS           \ Interrupt Status register
  $50 constant ADC_IRQ_ENABLE           \ Enable/disable Interrupts
  $54 constant ADC_TIMER_CONF           \ Time to add after an LDO Enable or ADC Enable to let the HW to be stable before using it

: ADC_DEF ; [then]
