\
\ @file adc.fs
\ @brief ADC address block description
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

.include ../common.fs

\
\ @brief VERSION_ID register
\ Address offset: 0x00
\ Reset value: 0x00000020
\

$000000ff constant ADC_VERSION_ID_VERSION_ID                        \ version of the embedded IP.


\
\ @brief ADC configuration register
\ Address offset: 0x04
\ Reset value: 0x00020002
\

$00000001 constant ADC_CONF_CONT                                    \ regular sequence runs continuously when ADC mode is enabled
$00000002 constant ADC_CONF_SEQUENCE                                \ enable the sequence mode (active by default)
$0000003c constant ADC_CONF_SEQ_LEN                                 \ number of conversions in a regular sequence
$00000040 constant ADC_CONF_SMPS_SYNCHRO_ENA                        \ synchronize the ADC start conversion with a pulse generated by the
$00000180 constant ADC_CONF_OP_MODE                                 \ ADC mode selection (= data path selection)
$00001800 constant ADC_CONF_SAMPLE_RATE                             \ conversion rate of ADC
$00002000 constant ADC_CONF_DMA_DS_ENA                              \ enable DMA mode for Down Sampler data path
$00004000 constant ADC_CONF_DMA_DF_ENA                              \ enable DMA mode for Decimation Filter data path
$00008000 constant ADC_CONF_OVR_DS_CFG                              \ Down Sampler overrun configuration
$00010000 constant ADC_CONF_OVR_DF_CFG                              \ decimation overrun configuration
$00020000 constant ADC_CONF_BIT_INVERT_SN                           \ invert bit to bit the ADC data output when a single
$00040000 constant ADC_CONF_BIT_INVERT_DIFF                         \ invert bit to bit the ADC data output when a differential
$00080000 constant ADC_CONF_ADC_CONT_1V2                            \ select the input sampling method
$00100000 constant ADC_CONF_VBIAS_PRECH_FORCE                       \ possibility to keep the VBIAS_PRECH enabled to deactivate the filter


\
\ @brief ADC control register
\ Address offset: 0x08
\ Reset value: 0x00000000
\

$00000001 constant ADC_CTRL_ADC_ON_OFF                              \ ADC_ON_OFF: – 0: power off the ADC – 1: power on the ADC
$00000002 constant ADC_CTRL_START_CON                               \ generate a start pulse to initiate an ADC conversion
$00000004 constant ADC_CTRL_STOP_OP_MOD                             \ stop the on-going OP_MODE (ADC mode, Analog audio mode, Full
$00000008 constant ADC_CTRL_DIG_AUD_MODE                            \ enable the digital audio mode (the data path uses the decimation filter)
$00000010 constant ADC_CTRL_TEST_MODE                               \ select the functional or the test mode of the ADC
$00000020 constant ADC_CTRL_ADC_LDO_ENA                             \ enable the LDO associated to the ADC block


\
\ @brief Occasionnal mode control register
\ Address offset: 0x0C
\ Reset value: 0x00000000
\

$00000001 constant ADC_OCM_CTRL_OCM_SRC                             \ select the occasional conversion source
$00000002 constant ADC_OCM_CTRL_OCM_ENA                             \ start occasional conversion in analog audio and full modes


\
\ @brief PGA configuration register
\ Address offset: 0x10
\ Reset value: 0x00000000
\

$0000000f constant ADC_PGA_CONF_PGA_GAIN                            \ from 6 to 30 dB
$00000070 constant ADC_PGA_CONF_PGA_BIAS                            \ set the microphone bias voltage


\
\ @brief ADC switch control for Input Selection
\ Address offset: 0x14
\ Reset value: 0x00000000
\

$00000003 constant ADC_SWITCH_SE_VIN_0                              \ input voltage for VINM[0] / VINP[0]-VINM[0]
$0000000c constant ADC_SWITCH_SE_VIN_1                              \ input voltage for VINM[1] / VINP[1]-VINM[1]
$00000030 constant ADC_SWITCH_SE_VIN_2                              \ input voltage for VINM[2] / VINP[2]-VINM[2]
$000000c0 constant ADC_SWITCH_SE_VIN_3                              \ input voltage for VINM[3] / VINP[3]-VINM[3]
$00000300 constant ADC_SWITCH_SE_VIN_4                              \ input voltage for VINP[0]
$00000c00 constant ADC_SWITCH_SE_VIN_5                              \ input voltage for VINP[1]
$00003000 constant ADC_SWITCH_SE_VIN_6                              \ input voltage for VINP[2]
$0000c000 constant ADC_SWITCH_SE_VIN_7                              \ input voltage for VINP[3]


\
\ @brief Decimation filter configuration register
\ Address offset: 0x18
\ Reset value: 0x00003015
\

$0000007f constant ADC_DF_CONF_DF_CIC_DEC_FACTOR                
$00000080 constant ADC_DF_CONF_DF_CIC_DHF                           \ CIC filter decimator half factor
$00000100 constant ADC_DF_CONF_DF_ITP1P2                            \ 1.2 fractional interpolator enable
$00000200 constant ADC_DF_CONF_DF_I_U2S                             \ select signed/unsigned format for input
$00000400 constant ADC_DF_CONF_DF_O_S2U                             \ select signed/unsigned format for data output
$00007800 constant ADC_DF_CONF_PDM_RATE                             \ select the PDM clock rate.
$00008000 constant ADC_DF_CONF_DF_MICROL_RN                         \ left/right channel selection on digital microphone
$00010000 constant ADC_DF_CONF_DF_HPF_EN                            \ high pass filter enable.
$00020000 constant ADC_DF_CONF_DF_HALF_D_EN                         \ half dynamic enable.


\
\ @brief Downsampler configuration register
\ Address offset: 0x1C
\ Reset value: 0x00000000
\

$00000007 constant ADC_DS_CONF_DS_RATIO                             \ program the Down Sampler ratio (N factor)
$00000038 constant ADC_DS_CONF_DS_WIDTH                             \ program the Down Sampler width of data output (DSDTATA)


\
\ @brief ADC regular sequence configuration register 1
\ Address offset: 0x20
\ Reset value: 0x00000000
\

$0000000f constant ADC_SEQ_1_SEQ0                                   \ channel number code for first conversion of the sequence
$000000f0 constant ADC_SEQ_1_SEQ1                                   \ channel number code for second conversion of the sequence.
$00000f00 constant ADC_SEQ_1_SEQ2                                   \ channel number code for 3rd conversion of the sequence.
$0000f000 constant ADC_SEQ_1_SEQ3                                   \ channel number code for 4th conversion of the sequence.
$000f0000 constant ADC_SEQ_1_SEQ4                                   \ channel number code for 5th conversion of the sequence.
$00f00000 constant ADC_SEQ_1_SEQ5                                   \ channel number code for 6th conversion of the sequence.
$0f000000 constant ADC_SEQ_1_SEQ6                                   \ channel number code for 7th conversion of the sequence.
$f0000000 constant ADC_SEQ_1_SEQ7                                   \ channel number code for 8th conversion of the sequence.


\
\ @brief ADC regular sequence configuration register 2
\ Address offset: 0x24
\ Reset value: 0x00000000
\

$0000000f constant ADC_SEQ_2_SEQ8                                   \ channel number code for 9th conversion of the sequence
$000000f0 constant ADC_SEQ_2_SEQ9                                   \ channel number code for 10th conversion of the sequence.
$00000f00 constant ADC_SEQ_2_SEQ10                                  \ channel number code for 11th conversion of the sequence.
$0000f000 constant ADC_SEQ_2_SEQ11                                  \ channel number code for 12th conversion of the sequence.
$000f0000 constant ADC_SEQ_2_SEQ12                                  \ channel number code for 13th conversion of the sequence.
$00f00000 constant ADC_SEQ_2_SEQ13                                  \ channel number code for 14th conversion of the sequence.
$0f000000 constant ADC_SEQ_2_SEQ14                                  \ channel number code for 15th conversion of the sequence.
$f0000000 constant ADC_SEQ_2_SEQ15                                  \ channel number code for 16th conversion of the sequence.


\
\ @brief ADC Gain and offset correction values register 1
\ Address offset: 0x28
\ Reset value: 0x00000555
\

$00000fff constant ADC_COMP_1_GAIN1                                 \ first calibration point: gain AUXADC_GAIN_1V2[11:0]
$0007f000 constant ADC_COMP_1_OFFSET1                               \ first calibration point: signed offset compensation[6:0]


\
\ @brief ADC Gain and offset correction values register 2
\ Address offset: 0x2C
\ Reset value: 0x00000555
\

$00000fff constant ADC_COMP_2_GAIN2                                 \ second calibration point: gain AUXADC_GAIN_1V2[11:0]
$0007f000 constant ADC_COMP_2_OFFSET2                               \ second calibration point: signed offset compensation[6:0]


\
\ @brief ADC Gain and offset correction values register 3
\ Address offset: 0x30
\ Reset value: 0x00000555
\

$00000fff constant ADC_COMP_3_GAIN3                                 \ third calibration point: gain AUXADC_GAIN_1V2[11:0]
$0007f000 constant ADC_COMP_3_OFFSET3                               \ third calibration point: signed offset compensation[6:0]


\
\ @brief ADC Gain and offset correction values register 4
\ Address offset: 0x34
\ Reset value: 0x00000555
\

$00000fff constant ADC_COMP_4_GAIN4                                 \ fourth calibration point: gain AUXADC_GAIN_1V2[11:0]
$0007f000 constant ADC_COMP_4_OFFSET4                               \ fourth calibration point: signed offset compensation[6:0]


\
\ @brief ADC Gain and Offset selection values register
\ Address offset: 0x38
\ Reset value: 0x00000000
\

$00000003 constant ADC_COMP_SEL_GAIN_OFFSET0                        \ gain / offset used in ADC single negative mode with Vinput range = 1.2V
$0000000c constant ADC_COMP_SEL_GAIN_OFFSET1                        \ gain / offset used in ADC single positive mode with Vinput range = 1.2V
$00000030 constant ADC_COMP_SEL_GAIN_OFFSET2                        \ gain / offset used in ADC differential mode with Vinput range = 1.2V
$000000c0 constant ADC_COMP_SEL_GAIN_OFFSET3                        \ gain / offset used in ADC single negative mode with Vinput range = 2.4V
$00000300 constant ADC_COMP_SEL_GAIN_OFFSET4                        \ gain / offset used in ADC single positive mode with Vinput range = 2.4V
$00000c00 constant ADC_COMP_SEL_GAIN_OFFSET5                        \ gain / offset used in ADC differential mode with Vinput range = 2.4V
$00003000 constant ADC_COMP_SEL_GAIN_OFFSET6                        \ gain / offset used in ADC single negative mode with Vinput range = 3.6V
$0000c000 constant ADC_COMP_SEL_GAIN_OFFSET7                        \ gain / offset used in ADC single positive mode with Vinput range = 3.6V
$00030000 constant ADC_COMP_SEL_GAIN_OFFSET8                        \ gain / offset used in ADC differential mode with Vinput range = 3.6V


\
\ @brief High/low limits for event monitoring a channel register
\ Address offset: 0x3C
\ Reset value: 0x0FFF0000
\

$00000fff constant ADC_WD_TH_WD_LT                                  \ analog watchdog low level threshold.
$0fff0000 constant ADC_WD_TH_WD_HT                                  \ analog watchdog high level threshold.


\
\ @brief Channel selection for event monitoring register
\ Address offset: 0x40
\ Reset value: 0x00000000
\

$0000ffff constant ADC_WD_CONF_AWD_CHX                              \ analog watchdog channel selection to define which input channel(s) need to be guarded by the watchdog.


\
\ @brief Downsampler Data output register
\ Address offset: 0x44
\ Reset value: 0x00000000
\

$0000ffff constant ADC_DS_DATAOUT_DS_DATA                           \ contain the converted data at the output of the Down Sampler


\
\ @brief Decimation filter Data output register
\ Address offset: 0x48
\ Reset value: 0x00000000
\

$0000ffff constant ADC_DF_DATAOUT_DF_DATA                           \ contain the converted data at the output of the decimation filter.


\
\ @brief Interrupt Status register
\ Address offset: 0x4C
\ Reset value: 0x00000000
\

$00000001 constant ADC_IRQ_STATUS_EOC_IRQ                           \ (Used in test mode only): set when the ADC conversion is completed.
$00000002 constant ADC_IRQ_STATUS_EODS_IRQ                          \ set when the Down Sampler conversion is completed.
$00000004 constant ADC_IRQ_STATUS_EODF_IRQ                          \ set when the decimation filter conversion is completed
$00000008 constant ADC_IRQ_STATUS_EOS_IRQ                           \ set when a sequence of conversion is completed
$00000010 constant ADC_IRQ_STATUS_AWD_IRQ                           \ set when an analog watchdog event occurs
$00000020 constant ADC_IRQ_STATUS_OVR_DS_IRQ                        \ set to indicate a Down Sampler overrun (at least one data is lost)
$00000040 constant ADC_IRQ_STATUS_OVR_DF_IRQ                        \ set to indicate a decimation filter overrun (a data is lost)
$00000080 constant ADC_IRQ_STATUS_DF_OVRFL_IRQ                      \ set to indicate the decimation filter is saturated.


\
\ @brief Enable/disable Interrupts
\ Address offset: 0x50
\ Reset value: 0x00000000
\

$00000001 constant ADC_IRQ_ENABLE_EOC_IRQ_ENA                       \ (Used in test mode only): End of ADC conversion interrupt enable
$00000002 constant ADC_IRQ_ENABLE_EODS_IRQ_ENA                      \ End of conversion interrupt enable for the Down Sampler output
$00000004 constant ADC_IRQ_ENABLE_EODF_IRQ_ENA                      \ End of conversion interrupt enable for the decimation filter output
$00000008 constant ADC_IRQ_ENABLE_EOS_IRQ_ENA                       \ End of regular sequence interrupt enable
$00000010 constant ADC_IRQ_ENABLE_AWD_IRQ_ENA                       \ analog watchdog interrupt enable
$00000020 constant ADC_IRQ_ENABLE_OVR_DS_IRQ_ENA                    \ Down Sampler overrun interrupt enable
$00000040 constant ADC_IRQ_ENABLE_OVR_DF_IRQ_ENA                    \ decimation filter overrun interrupt enable
$00000080 constant ADC_IRQ_ENABLE_DF_OVRFL_IRQ_ENA                  \ decimation filter saturation interrupt enable


\
\ @brief Time to add after an LDO Enable or ADC Enable to let the HW to be stable before using it
\ Address offset: 0x54
\ Reset value: 0x00009628
\

$000000ff constant ADC_TIMER_CONF_ADC_LDO_DELAY                     \ define the duration of a waiting time to be inserted between the ADC_LDO enable and the ADC ON to let time to the LDO to stabilize before starting a conversion.
$0000ff00 constant ADC_TIMER_CONF_VBIAS_PRECH_DELAY                 \ define the duration of a waiting time starting at rising edge of PGA_EN signal and corresponding to the VBIAS precharge duration
$00010000 constant ADC_TIMER_CONF_PRECH_DELAY_SEL                   \ Select the time step PD_STEP for the VBIAS_PRECH_DELAY timer


\
\ @brief ADC address block description
\
$41006000 constant ADC_VERSION_ID  \ offset: 0x00 : VERSION_ID register
$41006004 constant ADC_CONF       \ offset: 0x04 : ADC configuration register
$41006008 constant ADC_CTRL       \ offset: 0x08 : ADC control register
$4100600c constant ADC_OCM_CTRL   \ offset: 0x0C : Occasionnal mode control register
$41006010 constant ADC_PGA_CONF   \ offset: 0x10 : PGA configuration register
$41006014 constant ADC_SWITCH     \ offset: 0x14 : ADC switch control for Input Selection
$41006018 constant ADC_DF_CONF    \ offset: 0x18 : Decimation filter configuration register
$4100601c constant ADC_DS_CONF    \ offset: 0x1C : Downsampler configuration register
$41006020 constant ADC_SEQ_1      \ offset: 0x20 : ADC regular sequence configuration register 1
$41006024 constant ADC_SEQ_2      \ offset: 0x24 : ADC regular sequence configuration register 2
$41006028 constant ADC_COMP_1     \ offset: 0x28 : ADC Gain and offset correction values register 1
$4100602c constant ADC_COMP_2     \ offset: 0x2C : ADC Gain and offset correction values register 2
$41006030 constant ADC_COMP_3     \ offset: 0x30 : ADC Gain and offset correction values register 3
$41006034 constant ADC_COMP_4     \ offset: 0x34 : ADC Gain and offset correction values register 4
$41006038 constant ADC_COMP_SEL   \ offset: 0x38 : ADC Gain and Offset selection values register
$4100603c constant ADC_WD_TH      \ offset: 0x3C : High/low limits for event monitoring a channel register
$41006040 constant ADC_WD_CONF    \ offset: 0x40 : Channel selection for event monitoring register
$41006044 constant ADC_DS_DATAOUT  \ offset: 0x44 : Downsampler Data output register
$41006048 constant ADC_DF_DATAOUT  \ offset: 0x48 : Decimation filter Data output register
$4100604c constant ADC_IRQ_STATUS  \ offset: 0x4C : Interrupt Status register
$41006050 constant ADC_IRQ_ENABLE  \ offset: 0x50 : Enable/disable Interrupts
$41006054 constant ADC_TIMER_CONF  \ offset: 0x54 : Time to add after an LDO Enable or ADC Enable to let the HW to be stable before using it

