\
\ @file saes.fs
\ @brief Secure AES coprocessor
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

[ifndef] SAES_DEF

  [ifdef] SAES_SAES_CR_DEF
    \
    \ @brief SAES control register
    \ Address offset: 0x00
    \ Reset value: 0x00000000
    \
    $00 constant SAES_EN                        \ [0x00] SAES enable This bit enables/disables the SAES peripheral: At any moment, clearing then setting the bit re-initializes the SAES peripheral. This bit is automatically cleared by hardware upon the completion of the key preparation (Mode 2) and upon the completion of GCM/GMAC/CCM initial phase. The bit cannot be set as long as KEYVALID = 0 nor along with the following settings: KMOD[1:0] = 01 + CHMOD[2:0] = 011 and KMOD[1:0] = 01 + CHMOD[2:0] = 010 + MODE[1:0] = 00. Note: With KMOD[1:0] other than 00, use the IPRST bit rather than the bit EN.
    $01 constant SAES_DATATYPE                  \ [0x01 : 2] Data type selection This bitfield defines the format of data written in the SAES_DINR register or read from the SAES_DOUTR register, through selecting the mode of data swapping: For more details, refer to Section 32.4.15: SAES data registers and data swapping. Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
    $03 constant SAES_MODE                      \ [0x03 : 2] SAES operating mode This bitfield selects the SAES operating mode: Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
    $05 constant SAES_CHMOD                     \ [0x05 : 2] CHMOD[1:0]: Chaining mode selection This bitfield selects the AES chaining mode: others: Reserved Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
    $0b constant SAES_DMAINEN                   \ [0x0b] DMA input enable This bit enables/disables data transferring with DMA, in the input phase: When the bit is set, DMA requests are automatically generated by SAES during the input data phase. This feature is only effective when Mode 1 or Mode 3 is selected through the MODE[1:0] bitfield. It is not effective for Mode 2 (key derivation).
    $0c constant SAES_DMAOUTEN                  \ [0x0c] DMA output enable This bit enables/disables data transferring with DMA, in the output phase: When the bit is set, DMA requests are automatically generated by SAES during the output data phase. This feature is only effective when Mode 1 or Mode 3 is selected through the MODE[1:0] bitfield. It is not effective for Mode 2 (key derivation).
    $0d constant SAES_GCMPH                     \ [0x0d : 2] GCM or CCM phase selection This bitfield selects the phase of GCM, GMAC or CCM algorithm: The bitfield has no effect if other than GCM, GMAC or CCM algorithms are selected (through the ALGOMODE bitfield).
    $10 constant SAES_CHMOD_1                   \ [0x10] CHMOD[2]
    $12 constant SAES_KEYSIZE                   \ [0x12] Key size selection This bitfield defines the length of the key used in the SAES cryptographic core, in bits: When KMOD[1:0] = 01 or 10 KEYSIZE also defines the length of the key to encrypt or decrypt. Attempts to write the bit are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
    $14 constant SAES_NPBLB                     \ [0x14 : 4] Number of padding bytes in last block The bitfield sets the number of padding bytes in last block of payload: ...
    $18 constant SAES_KMOD                      \ [0x18 : 2] Key mode selection
    $1a constant SAES_KSHAREID                  \ [0x1a : 2] Key share identification This bitfield defines, at the end of a decryption process with KMOD[1:0] = 10 (shared key), which target can read the SAES key registers using a dedicated hardware bus. Others: Reserved Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
    $1c constant SAES_KEYSEL                    \ [0x1c : 3] Key selection The bitfield defines the source of the key information to use in the AES cryptographic core. Others: Reserved (if used, unfreeze SAES with IPRST) When KEYSEL is different from zero, selected key value is available in key registers when BUSY bit is cleared and KEYVALID is set in the SAES_SR register. Otherwise, the key error flag KEIF is set. Repeated writing of KEYSEL[2:0] with the same non-zero value only triggers the loading of DHUK or BHK if KEYVALID = 0. When the application software changes the key selection by writing the KEYSEL[2:0] bitfield, the key registers are immediately erased and the KEYVALID flag cleared. At the end of the decryption process, if KMOD[1:0] is other than zero, KEYSEL[2:0] is cleared. Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
    $1f constant SAES_IPRST                     \ [0x1f] SAES peripheral software reset Setting the bit resets the SAES peripheral, putting all registers to their default values, except the IPRST bit itself and the SAES_DPACFG register. Hence, any key-relative data is lost. For this reason, it is recommended to set the bit before handing over the SAES to a less secure application. The bit must be low while writing any configuration registers.
  [then]


  [ifdef] SAES_SAES_SR_DEF
    \
    \ @brief SAES status register
    \ Address offset: 0x04
    \ Reset value: 0x00000000
    \
    $00 constant SAES_CCF                       \ [0x00] Computation completed flag This bit mirrors the CCF bit of the SAES_ISR register.
    $01 constant SAES_RDERR                     \ [0x01] Read error flag This flag indicates the detection of an unexpected read operation from the SAES_DOUTR register (during computation or data input phase): The flag is set by hardware. It is cleared by software upon setting the RWEIF bit of the SAES_ICR register. Upon the flag setting, an interrupt is generated if enabled through the RWEIE bit of the SAES_ICR register. The flag setting has no impact on the SAES operation. Unexpected read returns zero.
    $02 constant SAES_WRERR                     \ [0x02] Write error This flag indicates the detection of an unexpected write operation to the SAES_DINR register (during computation or data output phase): The flag is set by hardware. It is cleared by software upon setting the RWEIF bit of the SAES_ICR register. Upon the flag setting, an interrupt is generated if enabled through the RWEIE bit of the SAES_ICR register. The flag setting has no impact on the SAES operation. Unexpected write is ignored.
    $03 constant SAES_BUSY                      \ [0x03] Busy This flag indicates whether SAES is idle or busy during GCM payload encryption phase: The flag is also set upon SAES initialization, upon fetching random number from the RNG, or upon transferring a shared key to a target peripheral. When GCM encryption is selected, the flag must be at zero before selecting the GCM final phase.
    $07 constant SAES_KEYVALID                  \ [0x07] Key Valid flag This bit is set by hardware when the amount of key information defined by KEYSIZE in SAES_CR has been loaded in SAES_KEYx key registers. In normal mode when KEYSEL equals to zero, the application must write the key registers in the correct sequence, otherwise the KEIF flag of the SAES_ISR register is set and KEYVALID stays at zero. When KEYSEL is different from zero the BUSY flag is automatically set by SAES. When key is loaded successfully, the BUSY flag is cleared and KEYVALID set. Upon an error, the KEIF flag of the SAES_ISR register is set, the BUSY flag cleared and KEYVALID kept at zero. When the KEIF flag is set, the application must clear it through the SAES_ICR register, otherwise KEYVALID cannot be set. See the KEIF bit description for more details. For more information on key loading, refer to Section 32.4.16: SAES key registers.
  [then]


  [ifdef] SAES_SAES_DINR_DEF
    \
    \ @brief SAES data input register
    \ Address offset: 0x08
    \ Reset value: 0x00000000
    \
    $00 constant SAES_DIN                       \ [0x00 : 32] Input data word A four-fold sequential write to this bitfield during the input phase results in writing a complete 128-bit block of input data to the SAES peripheral. From the first to the fourth write, the corresponding data weights are [127:96], [95:64], [63:32], and [31:0]. Upon each write, the data from the 32-bit input buffer are handled by the data swap block according to the DATATYPE[1:0] bitfield, then written into the AES core 128-bit input buffer. The data signification of the input data block depends on the SAES operating mode: - Mode 1 (encryption): plaintext - Mode 2 (key derivation): the bitfield is not used (SAES_KEYRx registers used for input if KEYSEL = 0) - Mode 3 (decryption): ciphertext The data swap operation is described in Section 32.4.15: SAES data registers and data swapping on page 1755.
  [then]


  [ifdef] SAES_SAES_DOUTR_DEF
    \
    \ @brief SAES data output register
    \ Address offset: 0x0C
    \ Reset value: 0x00000000
    \
    $00 constant SAES_DOUT                      \ [0x00 : 32] Output data word This read-only bitfield fetches a 32-bit output buffer. A four-fold sequential read of this bitfield, upon the computation completion (CCF set), virtually reads a complete 128-bit block of output data from the SAES peripheral. Before reaching the output buffer, the data produced by the AES core are handled by the data swap block according to the DATATYPE[1:0] bitfield. Data weights from the first to the fourth read operation are: [127:96], [95:64], [63:32], and [31:0]. The data signification of the output data block depends on the SAES operating mode: - Mode 1 (encryption): ciphertext - Mode 2 (key derivation): the bitfield is not used - Mode 3 (decryption): plaintext The data swap operation is described in Section 32.4.15: SAES data registers and data swapping on page 1755.
  [then]


  [ifdef] SAES_SAES_KEYR0_DEF
    \
    \ @brief SAES key register 0
    \ Address offset: 0x10
    \ Reset value: 0x00000000
    \
    $00 constant SAES_KEY                       \ [0x00 : 32] Cryptographic key, bits [31:0] This write-only bitfield contains the bits [31:0] of the AES encryption or decryption key, depending on the operating mode: - In Mode 1 (encryption), Mode 2 (key derivation): the value to write into the bitfield is the encryption key. - In Mode 3 (decryption): the value to write into the bitfield is the encryption key to be derived before being used for decryption. The SAES_KEYRx registers may be written only when KEYSIZE value is correct and when the SAES peripheral is disabled (EN bit of the SAES_CR register cleared). A special writing sequence is also required, as described in KEYVALID bit of the SAES_SR register. Note that, if KEYSEL is different from 0 and KEYVALID = 0, the key is directly loaded to SAES_KEYRx registers (hence writes to key register is ignored and KEIF is set). Refer to Section 32.4.16: SAES key registers on page 1758 for more details.
  [then]


  [ifdef] SAES_SAES_KEYR1_DEF
    \
    \ @brief SAES key register 1
    \ Address offset: 0x14
    \ Reset value: 0x00000000
    \
    $00 constant SAES_KEY                       \ [0x00 : 32] Cryptographic key, bits [63:32] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield.
  [then]


  [ifdef] SAES_SAES_KEYR2_DEF
    \
    \ @brief SAES key register 2
    \ Address offset: 0x18
    \ Reset value: 0x00000000
    \
    $00 constant SAES_KEY                       \ [0x00 : 32] Cryptographic key, bits [95:64] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield.
  [then]


  [ifdef] SAES_SAES_KEYR3_DEF
    \
    \ @brief SAES key register 3
    \ Address offset: 0x1C
    \ Reset value: 0x00000000
    \
    $00 constant SAES_KEY                       \ [0x00 : 32] Cryptographic key, bits [127:96] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield.
  [then]


  [ifdef] SAES_SAES_IVR0_DEF
    \
    \ @brief SAES initialization vector register 0
    \ Address offset: 0x20
    \ Reset value: 0x00000000
    \
    $00 constant SAES_IVI                       \ [0x00 : 32] Initialization vector input, bits [31:0] Refer to Section 32.4.17: SAES initialization vector registers on page 1760 for description of the IVI[127:0] bitfield. The initialization vector is only used in chaining modes other than ECB. The SAES_IVRx registers may be written only when the SAES peripheral is disabled
  [then]


  [ifdef] SAES_SAES_IVR1_DEF
    \
    \ @brief SAES initialization vector register 1
    \ Address offset: 0x24
    \ Reset value: 0x00000000
    \
    $00 constant SAES_IVI                       \ [0x00 : 32] Initialization vector input, bits [63:32] Refer to the SAES_IVR0 register for description of the IVI[128:0] bitfield.
  [then]


  [ifdef] SAES_SAES_IVR2_DEF
    \
    \ @brief SAES initialization vector register 2
    \ Address offset: 0x28
    \ Reset value: 0x00000000
    \
    $00 constant SAES_IVI                       \ [0x00 : 32] Initialization vector input, bits [95:64] Refer to the SAES_IVR0 register for description of the IVI[128:0] bitfield.
  [then]


  [ifdef] SAES_SAES_IVR3_DEF
    \
    \ @brief SAES initialization vector register 3
    \ Address offset: 0x2C
    \ Reset value: 0x00000000
    \
    $00 constant SAES_IVI                       \ [0x00 : 32] Initialization vector input, bits [127:96] Refer to the SAES_IVR0 register for description of the IVI[128:0] bitfield.
  [then]


  [ifdef] SAES_SAES_KEYR4_DEF
    \
    \ @brief SAES key register 4
    \ Address offset: 0x30
    \ Reset value: 0x00000000
    \
    $00 constant SAES_KEY                       \ [0x00 : 32] Cryptographic key, bits [159:128] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield.
  [then]


  [ifdef] SAES_SAES_KEYR5_DEF
    \
    \ @brief SAES key register 5
    \ Address offset: 0x34
    \ Reset value: 0x00000000
    \
    $00 constant SAES_KEY                       \ [0x00 : 32] Cryptographic key, bits [191:160] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield.
  [then]


  [ifdef] SAES_SAES_KEYR6_DEF
    \
    \ @brief SAES key register 6
    \ Address offset: 0x38
    \ Reset value: 0x00000000
    \
    $00 constant SAES_KEY                       \ [0x00 : 32] Cryptographic key, bits [223:192] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield.
  [then]


  [ifdef] SAES_SAES_KEYR7_DEF
    \
    \ @brief SAES key register 7
    \ Address offset: 0x3C
    \ Reset value: 0x00000000
    \
    $00 constant SAES_KEY                       \ [0x00 : 32] Cryptographic key, bits [255:224] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield.
  [then]


  [ifdef] SAES_SAES_SUSP0R_DEF
    \
    \ @brief SAES suspend registers
    \ Address offset: 0x40
    \ Reset value: 0x00000000
    \
    $00 constant SAES_SUSP                      \ [0x00 : 32] SAES suspend Upon suspend operation, this bitfield of the corresponding SAES_SUSPxR register takes the value of one of internal SAES registers.
  [then]


  [ifdef] SAES_SAES_SUSP1R_DEF
    \
    \ @brief SAES suspend registers
    \ Address offset: 0x44
    \ Reset value: 0x00000000
    \
    $00 constant SAES_SUSP                      \ [0x00 : 32] SAES suspend Upon suspend operation, this bitfield of the corresponding SAES_SUSPxR register takes the value of one of internal SAES registers.
  [then]


  [ifdef] SAES_SAES_SUSP2R_DEF
    \
    \ @brief SAES suspend registers
    \ Address offset: 0x48
    \ Reset value: 0x00000000
    \
    $00 constant SAES_SUSP                      \ [0x00 : 32] SAES suspend Upon suspend operation, this bitfield of the corresponding SAES_SUSPxR register takes the value of one of internal SAES registers.
  [then]


  [ifdef] SAES_SAES_SUSP3R_DEF
    \
    \ @brief SAES suspend registers
    \ Address offset: 0x4C
    \ Reset value: 0x00000000
    \
    $00 constant SAES_SUSP                      \ [0x00 : 32] SAES suspend Upon suspend operation, this bitfield of the corresponding SAES_SUSPxR register takes the value of one of internal SAES registers.
  [then]


  [ifdef] SAES_SAES_SUSP4R_DEF
    \
    \ @brief SAES suspend registers
    \ Address offset: 0x50
    \ Reset value: 0x00000000
    \
    $00 constant SAES_SUSP                      \ [0x00 : 32] SAES suspend Upon suspend operation, this bitfield of the corresponding SAES_SUSPxR register takes the value of one of internal SAES registers.
  [then]


  [ifdef] SAES_SAES_SUSP5R_DEF
    \
    \ @brief SAES suspend registers
    \ Address offset: 0x54
    \ Reset value: 0x00000000
    \
    $00 constant SAES_SUSP                      \ [0x00 : 32] SAES suspend Upon suspend operation, this bitfield of the corresponding SAES_SUSPxR register takes the value of one of internal SAES registers.
  [then]


  [ifdef] SAES_SAES_SUSP6R_DEF
    \
    \ @brief SAES suspend registers
    \ Address offset: 0x58
    \ Reset value: 0x00000000
    \
    $00 constant SAES_SUSP                      \ [0x00 : 32] SAES suspend Upon suspend operation, this bitfield of the corresponding SAES_SUSPxR register takes the value of one of internal SAES registers.
  [then]


  [ifdef] SAES_SAES_SUSP7R_DEF
    \
    \ @brief SAES suspend registers
    \ Address offset: 0x5C
    \ Reset value: 0x00000000
    \
    $00 constant SAES_SUSP                      \ [0x00 : 32] SAES suspend Upon suspend operation, this bitfield of the corresponding SAES_SUSPxR register takes the value of one of internal SAES registers.
  [then]


  [ifdef] SAES_SAES_IER_DEF
    \
    \ @brief SAES interrupt enable register
    \ Address offset: 0x300
    \ Reset value: 0x00000000
    \
    $00 constant SAES_CCFIE                     \ [0x00] Computation complete flag interrupt enable This bit enables or disables (masks) the SAES interrupt generation when CCF (computation complete flag) is set.
    $01 constant SAES_RWEIE                     \ [0x01] Read or write error interrupt enable This bit enables or disables (masks) the SAES interrupt generation when RWEIF (read and/or write error flag) is set.
    $02 constant SAES_KEIE                      \ [0x02] Key error interrupt enable This bit enables or disables (masks) the SAES interrupt generation when KEIF (key error flag) is set.
    $03 constant SAES_RNGEIE                    \ [0x03] RNG error interrupt enable This bit enables or disables (masks) the SAES interrupt generation when RNGEIF (RNG error flag) is set.
  [then]


  [ifdef] SAES_SAES_ISR_DEF
    \
    \ @brief SAES interrupt status register
    \ Address offset: 0x304
    \ Reset value: 0x00000000
    \
    $00 constant SAES_CCF                       \ [0x00] Computation complete flag This flag indicates whether the computation is completed: The flag is set by hardware upon the completion of the computation. It is cleared by software, upon setting the CCF bit of the SAES_ICR register. Upon the flag setting, an interrupt is generated if enabled through the CCFIE bit of the SAES_IER register. The flag is significant only when the DMAOUTEN bit is 0. It may stay high when DMA_EN is 1.
    $01 constant SAES_RWEIF                     \ [0x01] Read or write error interrupt flag This read-only bit is set by hardware when a RDERR or a WRERR error flag is set in the SAES_SR register. RWEIF bit is cleared when application sets the corresponding bit of SAES_ICR register. An interrupt is generated if the RWEIE bit has been previously set in the SAES_IER register. This flags has no meaning when key derivation mode is selected.
    $02 constant SAES_KEIF                      \ [0x02] Key error interrupt flag This read-only bit is set by hardware when key information failed to load into key registers or key register usage is forbidden. Setting the corresponding bit of the SAES_ICR register clears the KEIF and generates interrupt if the KEIE bit of the SAES_IER register is set. KEIF is triggered upon any of the following errors: SAES fails to load the DHUK (KEYSEL = 001 or 100). SAES fails to load the BHK (KEYSEL = 010 or 100) respecting the correct order. SAES fails to load the AHK (KEYSEL = 011 or 101). CRYP fails to load the key shared by SAES peripheral (KMOD = 10). SAES_KEYRx register write does not respect the correct order. (For KEYSIZE = 0, SAES_KEYR0 then SAES_KEYR1 then SAES_KEYR2 then SAES_KEYR3 register, or reverse. For KEYSIZE = 1, SAES_KEYR0 then SAES_KEYR1 then SAES_KEYR2 then SAES_KEYR3 then SAES_KEYR4 then SAES_KEYR5 then SAES_KEYR6 then SAES_KEYR7, or reverse). KEIF must be cleared by the application software, otherwise KEYVALID cannot be set.
    $03 constant SAES_RNGEIF                    \ [0x03] RNG error interrupt flag This read-only bit is set by hardware when an error is detected on RNG bus interface (e.g. bad entropy). RNGEIE bit is cleared when application sets the corresponding bit of SAES_ICR register. An interrupt is generated if the RNGEIE bit has been previously set in the SAES_IER register. Clearing this bit triggers the reload of a new random number from RNG peripheral.
  [then]


  [ifdef] SAES_SAES_ICR_DEF
    \
    \ @brief SAES interrupt clear register
    \ Address offset: 0x308
    \ Reset value: 0x00000000
    \
    $00 constant SAES_CCF                       \ [0x00] Computation complete flag clear Setting this bit clears the CCF status bit of the SAES_SR and SAES_ISR registers.
    $01 constant SAES_RWEIF                     \ [0x01] Read or write error interrupt flag clear Setting this bit clears the RWEIF status bit of the SAES_ISR register, and both RDERR and WRERR flags in the SAES_SR register.
    $02 constant SAES_KEIF                      \ [0x02] Key error interrupt flag clear Setting this bit clears the KEIF status bit of the SAES_ISR register.
    $03 constant SAES_RNGEIF                    \ [0x03] RNG error interrupt flag clear Application must set this bit to clear the RNGEIF status bit in SAES_ISR register.
  [then]

  \
  \ @brief Secure AES coprocessor
  \
  $00 constant SAES_SAES_CR             \ SAES control register
  $04 constant SAES_SAES_SR             \ SAES status register
  $08 constant SAES_SAES_DINR           \ SAES data input register
  $0C constant SAES_SAES_DOUTR          \ SAES data output register
  $10 constant SAES_SAES_KEYR0          \ SAES key register 0
  $14 constant SAES_SAES_KEYR1          \ SAES key register 1
  $18 constant SAES_SAES_KEYR2          \ SAES key register 2
  $1C constant SAES_SAES_KEYR3          \ SAES key register 3
  $20 constant SAES_SAES_IVR0           \ SAES initialization vector register 0
  $24 constant SAES_SAES_IVR1           \ SAES initialization vector register 1
  $28 constant SAES_SAES_IVR2           \ SAES initialization vector register 2
  $2C constant SAES_SAES_IVR3           \ SAES initialization vector register 3
  $30 constant SAES_SAES_KEYR4          \ SAES key register 4
  $34 constant SAES_SAES_KEYR5          \ SAES key register 5
  $38 constant SAES_SAES_KEYR6          \ SAES key register 6
  $3C constant SAES_SAES_KEYR7          \ SAES key register 7
  $40 constant SAES_SAES_SUSP0R         \ SAES suspend registers
  $44 constant SAES_SAES_SUSP1R         \ SAES suspend registers
  $48 constant SAES_SAES_SUSP2R         \ SAES suspend registers
  $4C constant SAES_SAES_SUSP3R         \ SAES suspend registers
  $50 constant SAES_SAES_SUSP4R         \ SAES suspend registers
  $54 constant SAES_SAES_SUSP5R         \ SAES suspend registers
  $58 constant SAES_SAES_SUSP6R         \ SAES suspend registers
  $5C constant SAES_SAES_SUSP7R         \ SAES suspend registers
  $300 constant SAES_SAES_IER           \ SAES interrupt enable register
  $304 constant SAES_SAES_ISR           \ SAES interrupt status register
  $308 constant SAES_SAES_ICR           \ SAES interrupt clear register

: SAES_DEF ; [then]
