\
\ @file gicc.fs
\ @brief GICC address block description
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

[ifndef] GICC_DEF

  [ifdef] GICC_GICC_CTLR_DEF
    \
    \ @brief GICC control register
    \ Address offset: 0x00
    \ Reset value: 0x00000000
    \
    $00 constant GICC_ENABLEGRP0                \ [0x00] Enable group 0 interrupts It enables for the signaling of group 0interrupts by the CPU interface to the connected processor.
    $01 constant GICC_ENABLEGRP1                \ [0x01] Enable group 1 interrupts It enables for the signaling of group 1 interrupts by the CPU interface to the connected processor.
    $02 constant GICC_ACKCTL                    \ [0x02] Acknowledge control When the highest priority pending interrupt is a group 1 interrupt, this bit determines both: - whether a read of GICC_IAR acknowledges the interrupt, or returns a spurious interrupt ID - whether a read of GICC_HPPIR returns the ID of the highest priority pending interrupt, or returns a spurious interrupt ID. Arm deprecates use of this bit and strongly recommends using a software model where this bit is set to 0.
    $03 constant GICC_FIQEN                     \ [0x03] FIQ enable for group 0 interrupts Controls whether the CPU interface signals group 0 interrupts to a target processor using the FIQ or the IRQ signal. The GIC always signals group 1 interrupts using the IRQ signal.
    $04 constant GICC_CBPR                      \ [0x04] BPR control Controls whether the GICC_BPR provides common control to group 0 and group 1 interrupts.
    $05 constant GICC_FIQBYPDISGRP0             \ [0x05] FIQ bypass disable for group 0 interrupts When the signaling of FIQs by the CPU interface is disabled, this bit partly controls whether the bypass FIQ signal is signaled to the processor.
    $06 constant GICC_IRQBYPDISGRP0             \ [0x06] IRQ bypass disable for group 0 interrupts When the signaling of IRQs by the CPU interface is disabled, this bit partly controls whether the bypass IRQ signal is signaled to the processor.
    $07 constant GICC_FIQBYPDISGRP1             \ [0x07] Alias of FIQBYPDISGRP1 from the non-secure copy of this register.
    $08 constant GICC_IRQBYPDISGRP1             \ [0x08] Alias of IRQBYPDISGRP1 from the non-secure copy of this register.
    $09 constant GICC_EOIMODES                  \ [0x09] EOI mode for secure accesses Controls the behavior of accesses to GICC_EOIR and GICC_DIR registers. This control applies only to secure accesses.
    $0a constant GICC_EOIMODENS                 \ [0x0a] Alias of EOIMODENS from the non-secure copy of this register.
  [then]


  [ifdef] GICC_GICC_CTLRNS_DEF
    \
    \ @brief GICC control register
    \ Address offset: 0x00
    \ Reset value: 0x00000000
    \
    $00 constant GICC_ENABLEGRP1                \ [0x00] ENABLEGRP1
    $05 constant GICC_FIQBYPDISGRP1             \ [0x05] FIQBYPDISGRP1
    $06 constant GICC_IRQBYPDISGRP1             \ [0x06] IRQBYPDISGRP1
    $09 constant GICC_EOIMODENS                 \ [0x09] EOI mode for non- secure accesses
  [then]


  [ifdef] GICC_GICC_PMR_DEF
    \
    \ @brief GICC input priority mask register
    \ Address offset: 0x04
    \ Reset value: 0x00000000
    \
    $03 constant GICC_PRIORITY                  \ [0x03 : 5] priority mask level for the CPU interface If the priority of an interrupt is higher than the value indicated by this field, the interface signals the interrupt to the processor.
  [then]


  [ifdef] GICC_GICC_BPR_DEF
    \
    \ @brief GICC binary point register
    \ Address offset: 0x08
    \ Reset value: 0x00000000
    \
    $00 constant GICC_BINARY_POINT              \ [0x00 : 3] The value of this field controls how the 8-bit interrupt priority field is split into a group priority field. It is used to determine interrupt preemption and a sub-priority field. Minimum value is 2.
  [then]


  [ifdef] GICC_GICC_BPRNS_DEF
    \
    \ @brief GICC_BPRNS
    \ Address offset: 0x08
    \ Reset value: 0x00000000
    \
    $00 constant GICC_BINARY_POINT              \ [0x00 : 3] The value of this field controls how the 8-bit interrupt priority field is split into a group priority field. It is used to determine interrupt preemption and a sub-priority field. Minimum value is 2.
  [then]


  [ifdef] GICC_GICC_IAR_DEF
    \
    \ @brief GICC interrupt acknowledge register
    \ Address offset: 0x0C
    \ Reset value: 0x00000000
    \
    $00 constant GICC_INTERRUPT_ID              \ [0x00 : 10] The interrupt ID
    $0a constant GICC_CPUID                     \ [0x0a] For SGIs in a multiprocessor implementation, this field identifies the processor that requested the interrupt. It returns the number of the CPU interface that made the request. For example, a value of 1 means the request was generated by a write to the GICD_SGIR on CPU interface 1.
  [then]


  [ifdef] GICC_GICC_EOIR_DEF
    \
    \ @brief It contains the interrupt ID value from the corresponding GICC_IAR access.
    \ Address offset: 0x10
    \ Reset value: 0x00000000
    \
    $00 constant GICC_EOIINTID                  \ [0x00 : 10] It contains the interrupt ID value from the corresponding GICC_IAR access.
    $0a constant GICC_CPUID                     \ [0x0a] On a multiprocessor implementation, if the write refers to an SGI, this field contains the CPUID value from the corresponding GICC_IAR access.
  [then]


  [ifdef] GICC_GICC_RPR_DEF
    \
    \ @brief GICC running priority register
    \ Address offset: 0x14
    \ Reset value: 0x00000000
    \
    $03 constant GICC_PRIORITY                  \ [0x03 : 5] current running priority on the CPU interface
  [then]


  [ifdef] GICC_GICC_HPPIR_DEF
    \
    \ @brief GICC highest priority pending interrupt register
    \ Address offset: 0x18
    \ Reset value: 0x00000000
    \
    $00 constant GICC_PENDINTID                 \ [0x00 : 10] interrupt ID of the highest-priority pending interrupt
    $0a constant GICC_CPUID                     \ [0x0a] On a multiprocessor implementation, if the PENDINTID field returns the ID of an SGI, this field contains the CPUID value for that interrupt. This identifies the processor that generated the interrupt.
  [then]


  [ifdef] GICC_GICC_ABPR_DEF
    \
    \ @brief GICC aliased binary point register
    \ Address offset: 0x1C
    \ Reset value: 0x00000000
    \
    $00 constant GICC_BINARY_POINT              \ [0x00 : 3] The value of this field controls how the 8-bit interrupt priority field is split into a group priority field. It is used to determine interrupt preemption, and a subpriority field. Minimun value is 3.
  [then]


  [ifdef] GICC_GICC_AIAR_DEF
    \
    \ @brief GICC aliased interrupt acknowledge register
    \ Address offset: 0x20
    \ Reset value: 0x00000000
    \
    $00 constant GICC_INTERRUPT_ID              \ [0x00 : 10] interrupt ID
    $0a constant GICC_CPUID                     \ [0x0a] For SGIs in a multiprocessor implementation, this field identifies the processor that requested the interrupt. It returns the number of the CPU interface that made the request. For example, a value of 1 means the request was generated by a write to the GICD_SGIR on CPU interface 1.
  [then]


  [ifdef] GICC_GICC_AEOIR_DEF
    \
    \ @brief GICC aliased end of interrupt register
    \ Address offset: 0x24
    \ Reset value: 0x00000000
    \
    $00 constant GICC_EOIINTID                  \ [0x00 : 10] It contains the interrupt ID value from the corresponding GICC_AIAR, or non-secure GICC_IAR, access.
    $0a constant GICC_CPUID                     \ [0x0a] On a multiprocessor implementation, when processing an SGI, this field must contain the CPUID value from the corresponding GICC_AIAR, or non-secure GICC_IAR, access.
  [then]


  [ifdef] GICC_GICC_AHPPIR_DEF
    \
    \ @brief GICC aliased highest priority pending interrupt register
    \ Address offset: 0x28
    \ Reset value: 0x00000000
    \
    $00 constant GICC_PENDINTID                 \ [0x00 : 10] interrupt ID of the highest-priority pending interrupt It contains the interrupt ID of the highest-priority pending interrupt If that interrupt is a group 1 interrupt. Otherwise, its value is the spurious interrupt ID, 1023.
    $0a constant GICC_CPUID                     \ [0x0a] On a multiprocessor implementation, if the PENDINTID field returns the ID of an SGI, this field contains the CPUID value for that interrupt. This identifies the processor that generated the interrupt.
  [then]


  [ifdef] GICC_GICC_APR0_DEF
    \
    \ @brief active priority
    \ Address offset: 0xD0
    \ Reset value: 0x00000000
    \
    $00 constant GICC_APR0                      \ [0x00 : 32] active priority
  [then]


  [ifdef] GICC_GICC_NSAPR0_DEF
    \
    \ @brief non-secure active priority
    \ Address offset: 0xE0
    \ Reset value: 0x00000000
    \
    $00 constant GICC_NSAPR0                    \ [0x00 : 32] non-secure active priority
  [then]


  [ifdef] GICC_GICC_IIDR_DEF
    \
    \ @brief GIC implementer (0x43B Arm implementation)
    \ Address offset: 0xFC
    \ Reset value: 0x0102143B
    \
    $00 constant GICC_IMPLEMENTER               \ [0x00 : 12] GIC implementer (0x43B Arm implementation)
    $0c constant GICC_REVISION                  \ [0x0c : 4] revision number for the CPU interface
    $10 constant GICC_ARCH                      \ [0x10 : 4] architecture version of the GIC
    $14 constant GICC_PRODUCTID                 \ [0x14 : 12] product ID
  [then]


  [ifdef] GICC_GICC_DIR_DEF
    \
    \ @brief interrupt ID
    \ Address offset: 0x1000
    \ Reset value: 0x00000000
    \
    $00 constant GICC_INTERRUPT_ID              \ [0x00 : 10] interrupt ID
    $0a constant GICC_CPUID                     \ [0x0a] CPU ID For an SGI in a multiprocessor implementation, this field identifies the processor that requested the interrupt
  [then]

  \
  \ @brief GICC address block description
  \
  $00 constant GICC_GICC_CTLR           \ GICC control register
  $00 constant GICC_GICC_CTLRNS         \ GICC control register
  $04 constant GICC_GICC_PMR            \ GICC input priority mask register
  $08 constant GICC_GICC_BPR            \ GICC binary point register
  $08 constant GICC_GICC_BPRNS          \ GICC_BPRNS
  $0C constant GICC_GICC_IAR            \ GICC interrupt acknowledge register
  $10 constant GICC_GICC_EOIR           \ It contains the interrupt ID value from the corresponding GICC_IAR access.
  $14 constant GICC_GICC_RPR            \ GICC running priority register
  $18 constant GICC_GICC_HPPIR          \ GICC highest priority pending interrupt register
  $1C constant GICC_GICC_ABPR           \ GICC aliased binary point register
  $20 constant GICC_GICC_AIAR           \ GICC aliased interrupt acknowledge register
  $24 constant GICC_GICC_AEOIR          \ GICC aliased end of interrupt register
  $28 constant GICC_GICC_AHPPIR         \ GICC aliased highest priority pending interrupt register
  $D0 constant GICC_GICC_APR0           \ active priority
  $E0 constant GICC_GICC_NSAPR0         \ non-secure active priority
  $FC constant GICC_GICC_IIDR           \ GIC implementer (0x43B Arm implementation)
  $1000 constant GICC_GICC_DIR          \ interrupt ID

: GICC_DEF ; [then]
