\
\ @file gicc.fs
\ @brief GICC address block description
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

.include ../common.fs

\
\ @brief GICC control register
\ Address offset: 0x00
\ Reset value: 0x00000000
\

$00000001 constant GICC_GICC_CTLR_ENABLEGRP0                        \ Enable group 0 interrupts It enables for the signaling of group 0interrupts by the CPU interface to the connected processor.
$00000002 constant GICC_GICC_CTLR_ENABLEGRP1                        \ Enable group 1 interrupts It enables for the signaling of group 1 interrupts by the CPU interface to the connected processor.
$00000004 constant GICC_GICC_CTLR_ACKCTL                            \ Acknowledge control When the highest priority pending interrupt is a group 1 interrupt, this bit determines both: - whether a read of GICC_IAR acknowledges the interrupt, or returns a spurious interrupt ID - whether a read of GICC_HPPIR returns the ID of the highest priority pending interrupt, or returns a spurious interrupt ID. Arm deprecates use of this bit and strongly recommends using a software model where this bit is set to 0.
$00000008 constant GICC_GICC_CTLR_FIQEN                             \ FIQ enable for group 0 interrupts Controls whether the CPU interface signals group 0 interrupts to a target processor using the FIQ or the IRQ signal. The GIC always signals group 1 interrupts using the IRQ signal.
$00000010 constant GICC_GICC_CTLR_CBPR                              \ BPR control Controls whether the GICC_BPR provides common control to group 0 and group 1 interrupts.
$00000020 constant GICC_GICC_CTLR_FIQBYPDISGRP0                     \ FIQ bypass disable for group 0 interrupts When the signaling of FIQs by the CPU interface is disabled, this bit partly controls whether the bypass FIQ signal is signaled to the processor.
$00000040 constant GICC_GICC_CTLR_IRQBYPDISGRP0                     \ IRQ bypass disable for group 0 interrupts When the signaling of IRQs by the CPU interface is disabled, this bit partly controls whether the bypass IRQ signal is signaled to the processor.
$00000080 constant GICC_GICC_CTLR_FIQBYPDISGRP1                     \ Alias of FIQBYPDISGRP1 from the non-secure copy of this register.
$00000100 constant GICC_GICC_CTLR_IRQBYPDISGRP1                     \ Alias of IRQBYPDISGRP1 from the non-secure copy of this register.
$00000200 constant GICC_GICC_CTLR_EOIMODES                          \ EOI mode for secure accesses Controls the behavior of accesses to GICC_EOIR and GICC_DIR registers. This control applies only to secure accesses.
$00000400 constant GICC_GICC_CTLR_EOIMODENS                         \ Alias of EOIMODENS from the non-secure copy of this register.


\
\ @brief GICC control register
\ Address offset: 0x00
\ Reset value: 0x00000000
\

$00000001 constant GICC_GICC_CTLRNS_ENABLEGRP1                      \ ENABLEGRP1
$00000020 constant GICC_GICC_CTLRNS_FIQBYPDISGRP1                   \ FIQBYPDISGRP1
$00000040 constant GICC_GICC_CTLRNS_IRQBYPDISGRP1                   \ IRQBYPDISGRP1
$00000200 constant GICC_GICC_CTLRNS_EOIMODENS                       \ EOI mode for non- secure accesses


\
\ @brief GICC input priority mask register
\ Address offset: 0x04
\ Reset value: 0x00000000
\

$000000f8 constant GICC_GICC_PMR_PRIORITY                           \ priority mask level for the CPU interface If the priority of an interrupt is higher than the value indicated by this field, the interface signals the interrupt to the processor.


\
\ @brief GICC binary point register
\ Address offset: 0x08
\ Reset value: 0x00000000
\

$00000007 constant GICC_GICC_BPR_BINARY_POINT                       \ The value of this field controls how the 8-bit interrupt priority field is split into a group priority field. It is used to determine interrupt preemption and a sub-priority field. Minimum value is 2.


\
\ @brief GICC_BPRNS
\ Address offset: 0x08
\ Reset value: 0x00000000
\

$00000007 constant GICC_GICC_BPRNS_BINARY_POINT                     \ The value of this field controls how the 8-bit interrupt priority field is split into a group priority field. It is used to determine interrupt preemption and a sub-priority field. Minimum value is 2.


\
\ @brief GICC interrupt acknowledge register
\ Address offset: 0x0C
\ Reset value: 0x00000000
\

$000003ff constant GICC_GICC_IAR_INTERRUPT_ID                       \ The interrupt ID
$00000400 constant GICC_GICC_IAR_CPUID                              \ For SGIs in a multiprocessor implementation, this field identifies the processor that requested the interrupt. It returns the number of the CPU interface that made the request. For example, a value of 1 means the request was generated by a write to the GICD_SGIR on CPU interface 1.


\
\ @brief It contains the interrupt ID value from the corresponding GICC_IAR access.
\ Address offset: 0x10
\ Reset value: 0x00000000
\

$000003ff constant GICC_GICC_EOIR_EOIINTID                          \ It contains the interrupt ID value from the corresponding GICC_IAR access.
$00000400 constant GICC_GICC_EOIR_CPUID                             \ On a multiprocessor implementation, if the write refers to an SGI, this field contains the CPUID value from the corresponding GICC_IAR access.


\
\ @brief GICC running priority register
\ Address offset: 0x14
\ Reset value: 0x00000000
\

$000000f8 constant GICC_GICC_RPR_PRIORITY                           \ current running priority on the CPU interface


\
\ @brief GICC highest priority pending interrupt register
\ Address offset: 0x18
\ Reset value: 0x00000000
\

$000003ff constant GICC_GICC_HPPIR_PENDINTID                        \ interrupt ID of the highest-priority pending interrupt
$00000400 constant GICC_GICC_HPPIR_CPUID                            \ On a multiprocessor implementation, if the PENDINTID field returns the ID of an SGI, this field contains the CPUID value for that interrupt. This identifies the processor that generated the interrupt.


\
\ @brief GICC aliased binary point register
\ Address offset: 0x1C
\ Reset value: 0x00000000
\

$00000007 constant GICC_GICC_ABPR_BINARY_POINT                      \ The value of this field controls how the 8-bit interrupt priority field is split into a group priority field. It is used to determine interrupt preemption, and a subpriority field. Minimun value is 3.


\
\ @brief GICC aliased interrupt acknowledge register
\ Address offset: 0x20
\ Reset value: 0x00000000
\

$000003ff constant GICC_GICC_AIAR_INTERRUPT_ID                      \ interrupt ID
$00000400 constant GICC_GICC_AIAR_CPUID                             \ For SGIs in a multiprocessor implementation, this field identifies the processor that requested the interrupt. It returns the number of the CPU interface that made the request. For example, a value of 1 means the request was generated by a write to the GICD_SGIR on CPU interface 1.


\
\ @brief GICC aliased end of interrupt register
\ Address offset: 0x24
\ Reset value: 0x00000000
\

$000003ff constant GICC_GICC_AEOIR_EOIINTID                         \ It contains the interrupt ID value from the corresponding GICC_AIAR, or non-secure GICC_IAR, access.
$00000400 constant GICC_GICC_AEOIR_CPUID                            \ On a multiprocessor implementation, when processing an SGI, this field must contain the CPUID value from the corresponding GICC_AIAR, or non-secure GICC_IAR, access.


\
\ @brief GICC aliased highest priority pending interrupt register
\ Address offset: 0x28
\ Reset value: 0x00000000
\

$000003ff constant GICC_GICC_AHPPIR_PENDINTID                       \ interrupt ID of the highest-priority pending interrupt It contains the interrupt ID of the highest-priority pending interrupt If that interrupt is a group 1 interrupt. Otherwise, its value is the spurious interrupt ID, 1023.
$00000400 constant GICC_GICC_AHPPIR_CPUID                           \ On a multiprocessor implementation, if the PENDINTID field returns the ID of an SGI, this field contains the CPUID value for that interrupt. This identifies the processor that generated the interrupt.


\
\ @brief active priority
\ Address offset: 0xD0
\ Reset value: 0x00000000
\

$00000000 constant GICC_GICC_APR0_APR0                              \ active priority


\
\ @brief non-secure active priority
\ Address offset: 0xE0
\ Reset value: 0x00000000
\

$00000000 constant GICC_GICC_NSAPR0_NSAPR0                          \ non-secure active priority


\
\ @brief GIC implementer (0x43B Arm implementation)
\ Address offset: 0xFC
\ Reset value: 0x0102143B
\

$00000fff constant GICC_GICC_IIDR_IMPLEMENTER                       \ GIC implementer (0x43B Arm implementation)
$0000f000 constant GICC_GICC_IIDR_REVISION                          \ revision number for the CPU interface
$000f0000 constant GICC_GICC_IIDR_ARCH                              \ architecture version of the GIC
$fff00000 constant GICC_GICC_IIDR_PRODUCTID                         \ product ID


\
\ @brief interrupt ID
\ Address offset: 0x1000
\ Reset value: 0x00000000
\

$000003ff constant GICC_GICC_DIR_INTERRUPT_ID                       \ interrupt ID
$00000400 constant GICC_GICC_DIR_CPUID                              \ CPU ID For an SGI in a multiprocessor implementation, this field identifies the processor that requested the interrupt


\
\ @brief GICC address block description
\
$a0022000 constant GICC_GICC_CTLR  \ offset: 0x00 : GICC control register
$a0022000 constant GICC_GICC_CTLRNS  \ offset: 0x00 : GICC control register
$a0022004 constant GICC_GICC_PMR  \ offset: 0x04 : GICC input priority mask register
$a0022008 constant GICC_GICC_BPR  \ offset: 0x08 : GICC binary point register
$a0022008 constant GICC_GICC_BPRNS  \ offset: 0x08 : GICC_BPRNS
$a002200c constant GICC_GICC_IAR  \ offset: 0x0C : GICC interrupt acknowledge register
$a0022010 constant GICC_GICC_EOIR  \ offset: 0x10 : It contains the interrupt ID value from the corresponding GICC_IAR access.
$a0022014 constant GICC_GICC_RPR  \ offset: 0x14 : GICC running priority register
$a0022018 constant GICC_GICC_HPPIR  \ offset: 0x18 : GICC highest priority pending interrupt register
$a002201c constant GICC_GICC_ABPR  \ offset: 0x1C : GICC aliased binary point register
$a0022020 constant GICC_GICC_AIAR  \ offset: 0x20 : GICC aliased interrupt acknowledge register
$a0022024 constant GICC_GICC_AEOIR  \ offset: 0x24 : GICC aliased end of interrupt register
$a0022028 constant GICC_GICC_AHPPIR  \ offset: 0x28 : GICC aliased highest priority pending interrupt register
$a00220d0 constant GICC_GICC_APR0  \ offset: 0xD0 : active priority
$a00220e0 constant GICC_GICC_NSAPR0  \ offset: 0xE0 : non-secure active priority
$a00220fc constant GICC_GICC_IIDR  \ offset: 0xFC : GIC implementer (0x43B Arm implementation)
$a0023000 constant GICC_GICC_DIR  \ offset: 0x1000 : interrupt ID

