\
\ @file saes.fs
\ @brief SAES register block
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

.include ../common.fs

\
\ @brief SAES control register
\ Address offset: 0x00
\ Reset value: 0x00000000
\

$00000001 constant SAES_SAES_CR_EN                                  \ SAES enable This bit enables/disables the SAES peripheral: At any moment, clearing then setting the bit re-initializes the SAES peripheral. This bit is automatically cleared by hardware upon the completion of the key preparation (Mode 2) and upon the completion of GCM/GMAC/CCM initial phase. The bit cannot be set as long as KEYVALID = 0 nor along with the following settings: KMOD = 01 + CHMOD = 011 and KMOD = 01 + CHMOD = 010 + MODE = 00. Note: With KMOD[1:0] other than 00, use the IPRST bit rather than the bit EN.
$00000006 constant SAES_SAES_CR_DATATYPE                            \ Data type selection This bitfield defines the format of data written in the SAES_DINR register or read from the SAES_DOUTR register, through selecting the mode of data swapping: For more details, refer to . Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
$00000018 constant SAES_SAES_CR_MODE                                \ SAES operating mode This bitfield selects the SAES operating mode: Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
$00000060 constant SAES_SAES_CR_CHMOD1                              \ Chaining mode selection This bitfield selects the AES chaining mode: others: Reserved Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
$00000800 constant SAES_SAES_CR_DMAINEN                             \ DMA input enable This bit enables/disables data transferring with DMA, in the input phase: When the bit is set, DMA requests are automatically generated by SAES during the input data phase. This feature is only effective when Mode 1 or Mode 3 is selected through the MODE[1:0] bitfield. It is not effective for Mode 2 (key derivation).
$00001000 constant SAES_SAES_CR_DMAOUTEN                            \ DMA output enable This bit enables/disables data transferring with DMA, in the output phase: When the bit is set, DMA requests are automatically generated by SAES during the output data phase. This feature is only effective when Mode 1 or Mode 3 is selected through the MODE[1:0] bitfield. It is not effective for Mode 2 (key derivation).
$00006000 constant SAES_SAES_CR_GCMPH                               \ GCM or CCM phase selection This bitfield selects the phase of GCM, GMAC or CCM algorithm: The bitfield has no effect if other than GCM, GMAC or CCM algorithms are selected (through the ALGOMODE bitfield).
$00010000 constant SAES_SAES_CR_CHMOD2                              \ Chaining mode selection This bitfield selects the AES chaining mode: others: Reserved Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
$00040000 constant SAES_SAES_CR_KEYSIZE                             \ Key size selection This bitfield defines the length of the key used in the SAES cryptographic core, in bits: When KMOD[1:0]=01 or 10 KEYSIZE also defines the length of the key to encrypt or decrypt. Attempts to write the bit are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
$00080000 constant SAES_SAES_CR_KEYPROT                             \ Key protection When set hardware-based key protection is enabled. Attempts to write the bit are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
$00f00000 constant SAES_SAES_CR_NPBLB                               \ Number of padding bytes in last block The bitfield sets the number of padding bytes in last block of payload: ...
$03000000 constant SAES_SAES_CR_KMOD                                \ Key mode selection The bitfield defines how the SAES key can be used by the application: Others: Reserved With normal key selection, the key registers are freely usable, no specific usage or protection applies to SAES_DIN and SAES_DOUT registers. With wrapped key selection, the key loaded in key registers can only be used to encrypt or decrypt AES keys. Hence, when a decryption is selected in Wrapped-key mode read-as-zero SAES_DOUT register is automatically loaded into SAES key registers after a successful decryption process. With shared key selection, after a successful decryption process, SAES key registers are shared with the peripheral described in KSHAREID(1:0] bitfield. This sharing is valid only while KMOD[1:0]=10 and KEYVALID = 1. When a decryption is selected, read-as-zero SAES_DOUT register is automatically loaded into SAES key registers after a successful decryption process. With KMOD[1:0] other than zero, any attempt to configure the SAES peripheral for use by an application belonging to a different security domain (such as secure, non-secure, another CPU) results in automatic key erasure and setting of the KEIF flag. Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
$0c000000 constant SAES_SAES_CR_KSHAREID                            \ Key share identification This bitfield defines, at the end of a decryption process with KMOD[1:0]=10 (shared key), which target can read the SAES key registers using a dedicated hardware bus. Others: Reserved Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
$70000000 constant SAES_SAES_CR_KEYSEL                              \ Key selection The bitfield defines the source of the key information to use in the AES cryptographic core. Others: Reserved (if used, unfreeze SAES with IPRST) When KEYSEL is different from zero selected key value is available in key registers when BUSY bit is cleared and KEYVALID is set in SAES_SR register. Key error flag KEIF is set otherwise. Repeated writing of KEYSEL[2:0] with the same non-zero value only triggers the loading of DHUK or BHK if KEYVALID = 0. When application changes the key selection by writing to KEYSEL[2:0] bitfield, the key registers are immediately erased and the KEYVALID flag cleared. At the end of the decryption process, if KMOD[1:0] is other than zero, KEYSEL[2:0] is cleared. With the bitfield value other than zero and KEYVALID set, the application cannot transfer the ownership of SAES with a loaded key to an application running in another security context (such as secure, non-secure, specific CPU). More specifically, when security or Compartment ID of an access to any register does not match the information recorded by SAES, the KEIF flag is set. Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
$80000000 constant SAES_SAES_CR_IPRST                               \ SAES peripheral software reset Setting the bit resets the SAES peripheral, putting all registers to their default values, except the IPRST bit itself and the SAES_DPACFG register. Hence, any key-relative data is lost. For this reason, it is recommended to set the bit before handing over the SAES to a less secure application. The bit must be low while writing any configuration registers.


\
\ @brief SAES status register
\ Address offset: 0x04
\ Reset value: 0x00000000
\

$00000001 constant SAES_SAES_SR_CCF                                 \ Computation completed flag This bit mirrors the CCF bit of the SAES_ISR register.
$00000002 constant SAES_SAES_SR_RDERR                               \ Read error flag This flag indicates the detection of an unexpected read operation from the SAES_DOUTR register (during computation or data input phase): The flag is set by hardware. It is cleared by software upon setting the RWEIF bit of the SAES_ICR register. Upon the flag setting, an interrupt is generated if enabled through the RWEIE bit of the SAES_ICR register. The flag setting has no impact on the SAES operation. Unexpected read returns zero.
$00000004 constant SAES_SAES_SR_WRERR                               \ Write error This flag indicates the detection of an unexpected write operation to the SAES_DINR register (during computation or data output phase): The flag is set by hardware. It is cleared by software upon setting the RWEIF bit of the SAES_ICR register. Upon the flag setting, an interrupt is generated if enabled through the RWEIE bit of the SAES_ICR register. The flag setting has no impact on the SAES operation. Unexpected write is ignored.
$00000008 constant SAES_SAES_SR_BUSY                                \ Busy This flag indicates whether SAES is idle or busy during GCM payload encryption phase: The flag is set upon SAES initialization, upon fetching random number from the RNG, or upon transferring a shared key to a target peripheral. When GCM encryption is selected, the flag must be at zero before selecting the GCM final phase.
$00000080 constant SAES_SAES_SR_KEYVALID                            \ Key Valid flag This bit is set by hardware when the amount of key information defined by KEYSIZE in SAES_CR has been loaded in SAES_KEYx key registers. In normal mode when KEYSEL equals to zero, the application must write the key registers in the correct sequence, otherwise the KEIF flag of the SAES_ISR register is set and KEYVALID stays at zero. When KEYSEL is different from zero the BUSY flag is automatically set by SAES. When key is loaded successfully, the BUSY flag is cleared and KEYVALID set. Upon an error, the KEIF flag of the SAES_ISR register is set, the BUSY flag cleared and KEYVALID kept at zero. When the KEIF flag is set, the application must clear it through the SAES_ICR register, otherwise KEYVALID cannot be set. See the KEIF bit description for more details. For more information on key loading please refer to .


\
\ @brief SAES data input register
\ Address offset: 0x08
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_DINR_DIN                               \ Input data word A four-fold sequential write to this bitfield during the input phase results in writing a complete 128-bit block of input data to the SAES peripheral. From the first to the fourth write, the corresponding data weights are [127:96], [95:64], [63:32], and [31:0]. Upon each write, the data from the 32-bit input buffer are handled by the data swap block according to the DATATYPE[1:0] bitfield, then written into the AES core 128-bit input buffer. The data signification of the input data block depends on the SAES operating mode: - Mode 1 (encryption): plaintext - Mode 2 (key derivation): the bitfield is not used (SAES_KEYRx registers used for input if KEYSEL=0) - Mode 3 (decryption): ciphertext The data swap operation is described in on page 1718.


\
\ @brief SAES data output register
\ Address offset: 0x0C
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_DOUTR_DOUT                             \ Output data word This read-only bitfield fetches a 32-bit output buffer. A four-fold sequential read of this bitfield, upon the computation completion (CCF set), virtually reads a complete 128-bit block of output data from the SAES peripheral. Before reaching the output buffer, the data produced by the AES core are handled by the data swap block according to the DATATYPE[1:0] bitfield. Data weights from the first to the fourth read operation are: [127:96], [95:64], [63:32], and [31:0]. The data signification of the output data block depends on the SAES operating mode: - Mode 1 (encryption): ciphertext - Mode 2 (key derivation): the bitfield is not used - Mode 3 (decryption): plaintext The data swap operation is described in on page 1718.


\
\ @brief SAES key register 0
\ Address offset: 0x10
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_KEYR0_KEY                              \ Cryptographic key, bits [31:0] This write-only bitfield contains the bits [31:0] of the AES encryption or decryption key, depending on the operating mode: - In Mode 1 (encryption), Mode 2 (key derivation): the value to write into the bitfield is the encryption key. - In Mode 3 (decryption): the value to write into the bitfield is the encryption key to be derived before being used for decryption. The SAES_KEYRx registers may be written only when KEYSIZE value is correct and when the SAES peripheral is disabled (EN bit of the SAES_CR register cleared). A special writing sequence is also required, as described in KEYVALID bit of the SAES_SR register. Note that, if KEYSEL is different from 0 and KEYVALID = 0, the key is directly loaded to SAES_KEYRx registers (hence writes to key register is ignored and KEIF is set). Refer to for more details.


\
\ @brief SAES key register 1
\ Address offset: 0x14
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_KEYR1_KEY                              \ Cryptographic key, bits [63:32] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief SAES key register 2
\ Address offset: 0x18
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_KEYR2_KEY                              \ Cryptographic key, bits [95:64] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief SAES key register 3
\ Address offset: 0x1C
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_KEYR3_KEY                              \ Cryptographic key, bits [127:96] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief SAES initialization vector register 0
\ Address offset: 0x20
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_IVR0_IVI                               \ Initialization vector input, bits [31:0] Refer to for description of the IVI[127:0] bitfield. The initialization vector is only used in chaining modes other than ECB. The SAES_IVRx registers may be written only when the SAES peripheral is disabled


\
\ @brief SAES initialization vector register 1
\ Address offset: 0x24
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_IVR1_IVI                               \ Initialization vector input, bits [63:32] Refer to the SAES_IVR0 register for description of the IVI[128:0] bitfield.


\
\ @brief SAES initialization vector register 2
\ Address offset: 0x28
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_IVR2_IVI                               \ Initialization vector input, bits [95:64] Refer to the SAES_IVR0 register for description of the IVI[128:0] bitfield.


\
\ @brief SAES initialization vector register 3
\ Address offset: 0x2C
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_IVR3_IVI                               \ Initialization vector input, bits [127:96] Refer to the SAES_IVR0 register for description of the IVI[128:0] bitfield.


\
\ @brief SAES key register 4
\ Address offset: 0x30
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_KEYR4_KEY                              \ Cryptographic key, bits [159:128] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief SAES key register 5
\ Address offset: 0x34
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_KEYR5_KEY                              \ Cryptographic key, bits [191:160] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief SAES key register 6
\ Address offset: 0x38
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_KEYR6_KEY                              \ Cryptographic key, bits [223:192] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief SAES key register 7
\ Address offset: 0x3C
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_KEYR7_KEY                              \ Cryptographic key, bits [255:224] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief SAES suspend registers
\ Address offset: 0x40
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_SUSP0R_SUSP                            \ SAES suspend Upon suspend operation, this bitfield of the corresponding SAES_SUSPxR register takes the value of one of internal SAES registers.


\
\ @brief SAES suspend registers
\ Address offset: 0x44
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_SUSP1R_SUSP                            \ SAES suspend Upon suspend operation, this bitfield of the corresponding SAES_SUSPxR register takes the value of one of internal SAES registers.


\
\ @brief SAES suspend registers
\ Address offset: 0x48
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_SUSP2R_SUSP                            \ SAES suspend Upon suspend operation, this bitfield of the corresponding SAES_SUSPxR register takes the value of one of internal SAES registers.


\
\ @brief SAES suspend registers
\ Address offset: 0x4C
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_SUSP3R_SUSP                            \ SAES suspend Upon suspend operation, this bitfield of the corresponding SAES_SUSPxR register takes the value of one of internal SAES registers.


\
\ @brief SAES suspend registers
\ Address offset: 0x50
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_SUSP4R_SUSP                            \ SAES suspend Upon suspend operation, this bitfield of the corresponding SAES_SUSPxR register takes the value of one of internal SAES registers.


\
\ @brief SAES suspend registers
\ Address offset: 0x54
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_SUSP5R_SUSP                            \ SAES suspend Upon suspend operation, this bitfield of the corresponding SAES_SUSPxR register takes the value of one of internal SAES registers.


\
\ @brief SAES suspend registers
\ Address offset: 0x58
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_SUSP6R_SUSP                            \ SAES suspend Upon suspend operation, this bitfield of the corresponding SAES_SUSPxR register takes the value of one of internal SAES registers.


\
\ @brief SAES suspend registers
\ Address offset: 0x5C
\ Reset value: 0x00000000
\

$00000000 constant SAES_SAES_SUSP7R_SUSP                            \ SAES suspend Upon suspend operation, this bitfield of the corresponding SAES_SUSPxR register takes the value of one of internal SAES registers.


\
\ @brief SAES interrupt enable register
\ Address offset: 0x300
\ Reset value: 0x00000000
\

$00000001 constant SAES_SAES_IER_CCFIE                              \ Computation complete flag interrupt enable This bit enables or disables (masks) the SAES interrupt generation when CCF (computation complete flag) is set.
$00000002 constant SAES_SAES_IER_RWEIE                              \ Read or write error interrupt enable This bit enables or disables (masks) the SAES interrupt generation when RWEIF (read and/or write error flag) is set.
$00000004 constant SAES_SAES_IER_KEIE                               \ Key error interrupt enable This bit enables or disables (masks) the SAES interrupt generation when KEIF (key error flag) is set.
$00000008 constant SAES_SAES_IER_RNGEIE                             \ RNG error interrupt enable This bit enables or disables (masks) the SAES interrupt generation when RNGEIF (RNG error flag) is set.


\
\ @brief SAES interrupt status register
\ Address offset: 0x304
\ Reset value: 0x00000000
\

$00000001 constant SAES_SAES_ISR_CCF                                \ Computation complete flag This flag indicates whether the computation is completed: The flag is set by hardware upon the completion of the computation. It is cleared by software, upon setting the CCF bit of the SAES_ICR register. Upon the flag setting, an interrupt is generated if enabled through the CCFIE bit of the SAES_IER register. The flag is significant only when the DMAOUTEN bit is 0. It may stay high when DMA_EN is 1.
$00000002 constant SAES_SAES_ISR_RWEIF                              \ Read or write error interrupt flag This read-only bit is set by hardware when a RDERR or a WRERR error flag is set in the SAES_SR register. RWEIF bit is cleared when application sets the corresponding bit of SAES_ICR register. An interrupt is generated if the RWEIE bit has been previously set in the SAES_IER register. This flags has no meaning when key derivation mode is selected.
$00000004 constant SAES_SAES_ISR_KEIF                               \ Key error interrupt flag This read-only bit is set by hardware when key information failed to load into key registers or key register usage is forbidden. KEIF bit is cleared when application sets the corresponding bit in SAES_ICR register. An interrupt is generated if the KEIE bit has been previously set in the SAES_IER register. KEIF is triggered if one of below error occurred: Application did not write SAES_KEYRx registers in the correct sequence. Specifically, If KEYSIZE=0 SAES_KEYR0, then SAES_KEYR1, then SAES_KEYR2 then SAES_KEYR3 register must be written (or the reverse order). If KEYSIZE=1 SAES_KEYR0, then SAES_KEYR1, then SAES_KEYR2 then SAES_KEYR3, then SAES_KEYR4, then SAES_KEYR5, then SAES_KEYR6, then SAES_KEYR7 register must be written (or the reverse order). SAES failed to load the DHUK (KEYSEL=001 or 100) SAES failed to load the BHK (KEYSEL=010 or 100) using the same sequence as above. AES failed to load the key shared by SAES peripheral (KMOD=10) When KEYVALID=1 and (KEYPROT=1 or KEYSEL not 0x0), security context of the application that loaded the key (secure, non-secure, CPU) does not match the security or Compartment ID attribute of the access to SAES_CR or SAES_DOUT. In this case KEYVALID and EN bits are cleared. KEIF must be cleared by application otherwise KEYVALID cannot be set.
$00000008 constant SAES_SAES_ISR_RNGEIF                             \ RNG error interrupt flag This read-only bit is set by hardware when an error is detected on RNG bus interface (e.g. bad entropy). RNGEIE bit is cleared when application sets the corresponding bit of SAES_ICR register. An interrupt is generated if the RNGEIE bit has been previously set in the SAES_IER register. Clearing this bit triggers the reload of a new random number from RNG peripheral.


\
\ @brief SAES interrupt clear register
\ Address offset: 0x308
\ Reset value: 0x00000000
\

$00000001 constant SAES_SAES_ICR_CCF                                \ Computation complete flag clear Application must set this bit to clear the CCF status bit in SAES_SR and SAES_ISR register.
$00000002 constant SAES_SAES_ICR_RWEIF                              \ Read or write error interrupt flag clear Application must set this bit to clear the RWEIF status bit in SAES_ISR register, and both RDERR and WRERR flags in SAES_SR register.
$00000004 constant SAES_SAES_ICR_KEIF                               \ Key error interrupt flag clear Application must set this bit to clear the KEIF status bit in SAES_ISR register.
$00000008 constant SAES_SAES_ICR_RNGEIF                             \ RNG error interrupt flag clear Application must set this bit to clear the RNGEIF status bit in SAES_ISR register.


\
\ @brief SAES hardware configuration register
\ Address offset: 0x3F0
\ Reset value: 0x00000112
\

$0000000f constant SAES_SAES_HWCFGR_CFG1                            \ HW Generic 1
$000000f0 constant SAES_SAES_HWCFGR_CFG2                            \ HW Generic 2
$00000f00 constant SAES_SAES_HWCFGR_CFG3                            \ HW Generic 3


\
\ @brief SAES version register
\ Address offset: 0x3F4
\ Reset value: 0x00000030
\

$0000000f constant SAES_SAES_VERR_MINREV                            \ Minor revision This bitfield returns the SAES peripheral minor version (0x0).
$000000f0 constant SAES_SAES_VERR_MAJREV                            \ Major revision This bitfield returns the SAES peripheral major version (0x3).


\
\ @brief SAES identification register
\ Address offset: 0x3F8
\ Reset value: 0x00170023
\

$00000000 constant SAES_SAES_IPIDR_ID                               \ Identification code of the peripheral This bitfield returns the identification code of the SAES peripheral.


\
\ @brief SAES size ID register
\ Address offset: 0x3FC
\ Reset value: 0xA3C5DD01
\

$00000000 constant SAES_SAES_SIDR_SID                               \ Size identification code This bitfield returns the size identification code of the SAES peripheral as defined below: Bits[31:8] = 0xA3C5DD (fixed code) Bits[7:0] = 0x01 (1 Kbyte address decoding)


\
\ @brief SAES register block
\
$54005000 constant SAES_SAES_CR   \ offset: 0x00 : SAES control register
$54005004 constant SAES_SAES_SR   \ offset: 0x04 : SAES status register
$54005008 constant SAES_SAES_DINR  \ offset: 0x08 : SAES data input register
$5400500c constant SAES_SAES_DOUTR  \ offset: 0x0C : SAES data output register
$54005010 constant SAES_SAES_KEYR0  \ offset: 0x10 : SAES key register 0
$54005014 constant SAES_SAES_KEYR1  \ offset: 0x14 : SAES key register 1
$54005018 constant SAES_SAES_KEYR2  \ offset: 0x18 : SAES key register 2
$5400501c constant SAES_SAES_KEYR3  \ offset: 0x1C : SAES key register 3
$54005020 constant SAES_SAES_IVR0  \ offset: 0x20 : SAES initialization vector register 0
$54005024 constant SAES_SAES_IVR1  \ offset: 0x24 : SAES initialization vector register 1
$54005028 constant SAES_SAES_IVR2  \ offset: 0x28 : SAES initialization vector register 2
$5400502c constant SAES_SAES_IVR3  \ offset: 0x2C : SAES initialization vector register 3
$54005030 constant SAES_SAES_KEYR4  \ offset: 0x30 : SAES key register 4
$54005034 constant SAES_SAES_KEYR5  \ offset: 0x34 : SAES key register 5
$54005038 constant SAES_SAES_KEYR6  \ offset: 0x38 : SAES key register 6
$5400503c constant SAES_SAES_KEYR7  \ offset: 0x3C : SAES key register 7
$54005040 constant SAES_SAES_SUSP0R  \ offset: 0x40 : SAES suspend registers
$54005044 constant SAES_SAES_SUSP1R  \ offset: 0x44 : SAES suspend registers
$54005048 constant SAES_SAES_SUSP2R  \ offset: 0x48 : SAES suspend registers
$5400504c constant SAES_SAES_SUSP3R  \ offset: 0x4C : SAES suspend registers
$54005050 constant SAES_SAES_SUSP4R  \ offset: 0x50 : SAES suspend registers
$54005054 constant SAES_SAES_SUSP5R  \ offset: 0x54 : SAES suspend registers
$54005058 constant SAES_SAES_SUSP6R  \ offset: 0x58 : SAES suspend registers
$5400505c constant SAES_SAES_SUSP7R  \ offset: 0x5C : SAES suspend registers
$54005300 constant SAES_SAES_IER  \ offset: 0x300 : SAES interrupt enable register
$54005304 constant SAES_SAES_ISR  \ offset: 0x304 : SAES interrupt status register
$54005308 constant SAES_SAES_ICR  \ offset: 0x308 : SAES interrupt clear register
$540053f0 constant SAES_SAES_HWCFGR  \ offset: 0x3F0 : SAES hardware configuration register
$540053f4 constant SAES_SAES_VERR  \ offset: 0x3F4 : SAES version register
$540053f8 constant SAES_SAES_IPIDR  \ offset: 0x3F8 : SAES identification register
$540053fc constant SAES_SAES_SIDR  \ offset: 0x3FC : SAES size ID register

