\
\ @file aes.fs
\ @brief Advanced encryption standard hardware accelerator
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

.include ../common.fs

\
\ @brief AES control register
\ Address offset: 0x00
\ Reset value: 0x00000000
\

$00000001 constant AES_AES_CR_EN                                    \ AES enable This bit enables/disables the AES peripheral: At any moment, clearing then setting the bit re-initializes the AES peripheral. This bit is automatically cleared by hardware upon the completion of the key preparation (Mode 2) and upon the completion of GCM/GMAC/CCM initial phase. The bit cannot be set as long as KEYVALID = 0. Note: With KMOD[1:0] other than 00, use the IPRST bit rather than the bit EN.
$00000006 constant AES_AES_CR_DATATYPE                              \ Data type selection This bitfield defines the format of data written in the AES_DINR register or read from the AES_DOUTR register, through selecting the mode of data swapping: For more details, refer to . Attempts to write the bitfield are ignored when the BUSY flag of AES_SR register is set, as well as when the EN bit of the AES_CR register is set before the write access and it is not cleared by that write access.
$00000018 constant AES_AES_CR_MODE                                  \ AES operating mode This bitfield selects the AES operating mode: Attempts to write the bitfield are ignored when the BUSY flag of AES_SR register is set, as well as when the EN bit of the AES_CR register is set before the write access and it is not cleared by that write access.
$00000060 constant AES_AES_CR_CHMOD1                                \ Chaining mode selection This bitfield selects the AES chaining mode: others: Reserved Attempts to write the bitfield are ignored when the BUSY flag of AES_SR register is set, as well as when the EN bit of the AES_CR register is set before the write access and it is not cleared by that write access.
$00000800 constant AES_AES_CR_DMAINEN                               \ DMA input enable This bit enables/disables data transferring with DMA, in the input phase: When the bit is set, DMA requests are automatically generated by AES during the input data phase. This feature is only effective when Mode 1 or Mode 3 is selected through the MODE[1:0] bitfield. It is not effective for Mode 2 (key derivation).
$00001000 constant AES_AES_CR_DMAOUTEN                              \ DMA output enable This bit enables/disables data transferring with DMA, in the output phase: When the bit is set, DMA requests are automatically generated by AES during the output data phase. This feature is only effective when Mode 1 or Mode 3 is selected through the MODE[1:0] bitfield. It is not effective for Mode 2 (key derivation).
$00006000 constant AES_AES_CR_GCMPH                                 \ GCM or CCM phase selection This bitfield selects the phase of GCM, GMAC or CCM algorithm: The bitfield has no effect if other than GCM, GMAC or CCM algorithms are selected (through the ALGOMODE bitfield).
$00010000 constant AES_AES_CR_CHMOD2                                \ Chaining mode selection This bitfield selects the AES chaining mode: others: Reserved Attempts to write the bitfield are ignored when the BUSY flag of AES_SR register is set, as well as when the EN bit of the AES_CR register is set before the write access and it is not cleared by that write access.
$00040000 constant AES_AES_CR_KEYSIZE                               \ Key size selection This bitfield defines the length of the key used in the AES cryptographic core, in bits: Attempts to write the bit are ignored when the BUSY flag of AES_SR register is set, as well as when the EN bit of the AES_CR register is set before the write access and it is not cleared by that write access.
$00f00000 constant AES_AES_CR_NPBLB                                 \ Number of padding bytes in last block The bitfield sets the number of padding bytes in last block of payload: ...
$03000000 constant AES_AES_CR_KMOD                                  \ Key mode selection The bitfield defines how the AES key can be used by the application: Others: Reserved With normal key selection, the key registers are freely usable, no specific usage or protection applies to AES_DIN and AES_DOUT registers. With selection of shared key from SAES co-processor, the AES peripheral automatically loads its key registers with the data stored in the key registers of the SAES peripheral. The key value is available in key registers when BUSY bit is cleared and KEYVALID is set in the AES_SR register. Key error flag KEIF is set otherwise in the AES_ISR register. The bitfield must be set only when KEYSIZE is correct, and when a shared key decryption sequence has been successfully completed in SAES co-processor. N/AAttempts to write the bitfield are ignored when the BUSY flag of AES_SR register is set, as well as when the EN bit of the AES_CR register is set before the write access and it is not cleared by that write access.
$80000000 constant AES_AES_CR_IPRST                                 \ AES peripheral software reset Setting the bit resets the AES peripheral, putting all registers to their default values, except the IPRST bit itself. Hence, any key-relative data is lost. For this reason, it is recommended to set the bit before handing over the AES to a less secure application. The bit must be low while writing any configuration registers.


\
\ @brief AES status register
\ Address offset: 0x04
\ Reset value: 0x00000000
\

$00000001 constant AES_AES_SR_CCF                                   \ Computation completed flag This bit mirrors the CCF bit of the AES_ISR register.
$00000002 constant AES_AES_SR_RDERR                                 \ Read error flag This flag indicates the detection of an unexpected read operation from the AES_DOUTR register (during computation or data input phase): The flag is set by hardware. It is cleared by software upon setting the RWEIF bit of the AES_ICR register. Upon the flag setting, an interrupt is generated if enabled through the RWEIE bit of the AES_ICR register. The flag setting has no impact on the AES operation. Unexpected read returns zero.
$00000004 constant AES_AES_SR_WRERR                                 \ Write error This flag indicates the detection of an unexpected write operation to the AES_DINR register (during computation or data output phase): The flag is set by hardware. It is cleared by software upon setting the RWEIF bit of the AES_ICR register. Upon the flag setting, an interrupt is generated if enabled through the RWEIE bit of the AES_ICR register. The flag setting has no impact on the AES operation. Unexpected write is ignored.
$00000008 constant AES_AES_SR_BUSY                                  \ Busy This flag indicates whether AES is idle or busy during GCM payload encryption phase: When the flag indicates 'idle', the current GCM encryption processing may be suspended to process a higher-priority message. In other chaining modes, or in GCM phases other than payload encryption, the flag must be ignored for the suspend process. The flag is set when transferring a shared key from SAES peripheral.
$00000080 constant AES_AES_SR_KEYVALID                              \ Key Valid flag This bit is set by hardware when the amount of key information defined by KEYSIZE in AES_CR has been loaded in AES_KEYx key registers. In normal mode when KEYSEL equals to zero, the application must write the key registers in the correct sequence, otherwise the KEIF flag of the AES_ISR register is set and KEYVALID stays at zero. When KEYSEL is different from zero the BUSY flag is automatically set by AES. When key is loaded successfully, the BUSY flag is cleared and KEYVALID set. Upon an error, the KEIF flag of the AES_ISR register is set, the BUSY flag cleared and KEYVALID kept at zero. When the KEIF flag is set, the application must clear it through the AES_ICR register, otherwise KEYVALID cannot be set. See the KEIF bit description for more details. For more information on key loading please refer to .


\
\ @brief AES data input register
\ Address offset: 0x08
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_DINR_DIN                                 \ Input data word A four-fold sequential write to this bitfield during the input phase results in writing a complete 128-bit block of input data to the AES peripheral. From the first to the fourth write, the corresponding data weights are [127:96], [95:64], [63:32], and [31:0]. Upon each write, the data from the 32-bit input buffer are handled by the data swap block according to the DATATYPE[1:0] bitfield, then written into the AES core 128-bit input buffer. The data signification of the input data block depends on the AES operating mode: - Mode 1 (encryption): plaintext - Mode 2 (key derivation): the bitfield is not used (AES_KEYRx registers used for input) - Mode 3 (decryption): ciphertext The data swap operation is described in page 1149.


\
\ @brief AES data output register
\ Address offset: 0x0C
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_DOUTR_DOUT                               \ Output data word This read-only bitfield fetches a 32-bit output buffer. A four-fold sequential read of this bitfield, upon the computation completion (CCF set), virtually reads a complete 128-bit block of output data from the AES peripheral. Before reaching the output buffer, the data produced by the AES core are handled by the data swap block according to the DATATYPE[1:0] bitfield. Data weights from the first to the fourth read operation are: [127:96], [95:64], [63:32], and [31:0]. The data signification of the output data block depends on the AES operating mode: - Mode 1 (encryption): ciphertext - Mode 2 (key derivation): the bitfield is not used - Mode 3 (decryption): plaintext The data swap operation is described in page 1149.


\
\ @brief AES key register 0
\ Address offset: 0x10
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_KEYR0_KEY                                \ Cryptographic key, bits [31:0] This write-only bitfield contains the bits [31:0] of the AES encryption or decryption key, depending on the operating mode: - In Mode 1 (encryption), Mode 2 (key derivation): the value to write into the bitfield is the encryption key. - In Mode 3 (decryption): the value to write into the bitfield is the encryption key to be derived before being used for decryption. The AES_KEYRx registers may be written only when KEYSIZE value is correct and when the AES peripheral is disabled (EN bit of the AES_CR register cleared). A special writing sequence is also required, as described in KEYVALID bit of the AES_SR register. Note that, if KMOD[1:0] = 10 (shared key), the key is directly loaded from SAES peripheral to AES_KEYRx registers (hence writes to key register is ignored and KEIF is set). Refer to for more details.


\
\ @brief AES key register 1
\ Address offset: 0x14
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_KEYR1_KEY                                \ Cryptographic key, bits [63:32] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief AES key register 2
\ Address offset: 0x18
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_KEYR2_KEY                                \ Cryptographic key, bits [95:64] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief AES key register 3
\ Address offset: 0x1C
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_KEYR3_KEY                                \ Cryptographic key, bits [127:96] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief AES initialization vector register 0
\ Address offset: 0x20
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_IVR0_IVI                                 \ Initialization vector input, bits [31:0] Refer to for description of the IVI[127:0] bitfield. The initialization vector is only used in chaining modes other than ECB. The AES_IVRx registers may be written only when the AES peripheral is disabled


\
\ @brief AES initialization vector register 1
\ Address offset: 0x24
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_IVR1_IVI                                 \ Initialization vector input, bits [63:32] Refer to the AES_IVR0 register for description of the IVI[128:0] bitfield.


\
\ @brief AES initialization vector register 2
\ Address offset: 0x28
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_IVR2_IVI                                 \ Initialization vector input, bits [95:64] Refer to the AES_IVR0 register for description of the IVI[128:0] bitfield.


\
\ @brief AES initialization vector register 3
\ Address offset: 0x2C
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_IVR3_IVI                                 \ Initialization vector input, bits [127:96] Refer to the AES_IVR0 register for description of the IVI[128:0] bitfield.


\
\ @brief AES key register 4
\ Address offset: 0x30
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_KEYR4_KEY                                \ Cryptographic key, bits [159:128] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief AES key register 5
\ Address offset: 0x34
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_KEYR5_KEY                                \ Cryptographic key, bits [191:160] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief AES key register 6
\ Address offset: 0x38
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_KEYR6_KEY                                \ Cryptographic key, bits [223:192] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief AES key register 7
\ Address offset: 0x3C
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_KEYR7_KEY                                \ Cryptographic key, bits [255:224] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief AES suspend registers
\ Address offset: 0x40
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_SUSP0R_SUSP                              \ AES suspend Upon suspend operation, this bitfield of the corresponding AES_SUSPxR register takes the value of one of internal AES registers.


\
\ @brief AES suspend registers
\ Address offset: 0x44
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_SUSP1R_SUSP                              \ AES suspend Upon suspend operation, this bitfield of the corresponding AES_SUSPxR register takes the value of one of internal AES registers.


\
\ @brief AES suspend registers
\ Address offset: 0x48
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_SUSP2R_SUSP                              \ AES suspend Upon suspend operation, this bitfield of the corresponding AES_SUSPxR register takes the value of one of internal AES registers.


\
\ @brief AES suspend registers
\ Address offset: 0x4C
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_SUSP3R_SUSP                              \ AES suspend Upon suspend operation, this bitfield of the corresponding AES_SUSPxR register takes the value of one of internal AES registers.


\
\ @brief AES suspend registers
\ Address offset: 0x50
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_SUSP4R_SUSP                              \ AES suspend Upon suspend operation, this bitfield of the corresponding AES_SUSPxR register takes the value of one of internal AES registers.


\
\ @brief AES suspend registers
\ Address offset: 0x54
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_SUSP5R_SUSP                              \ AES suspend Upon suspend operation, this bitfield of the corresponding AES_SUSPxR register takes the value of one of internal AES registers.


\
\ @brief AES suspend registers
\ Address offset: 0x58
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_SUSP6R_SUSP                              \ AES suspend Upon suspend operation, this bitfield of the corresponding AES_SUSPxR register takes the value of one of internal AES registers.


\
\ @brief AES suspend registers
\ Address offset: 0x5C
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_SUSP7R_SUSP                              \ AES suspend Upon suspend operation, this bitfield of the corresponding AES_SUSPxR register takes the value of one of internal AES registers.


\
\ @brief AES interrupt enable register
\ Address offset: 0x300
\ Reset value: 0x00000000
\

$00000001 constant AES_AES_IER_CCFIE                                \ Computation complete flag interrupt enable This bit enables or disables (masks) the AES interrupt generation when CCF (computation complete flag) is set.
$00000002 constant AES_AES_IER_RWEIE                                \ Read or write error interrupt enable This bit enables or disables (masks) the AES interrupt generation when RWEIF (read and/or write error flag) is set.
$00000004 constant AES_AES_IER_KEIE                                 \ Key error interrupt enable This bit enables or disables (masks) the AES interrupt generation when KEIF (key error flag) is set.


\
\ @brief AES interrupt status register
\ Address offset: 0x304
\ Reset value: 0x00000000
\

$00000001 constant AES_AES_ISR_CCF                                  \ Computation complete flag This flag indicates whether the computation is completed: The flag is set by hardware upon the completion of the computation. It is cleared by software, upon setting the CCF bit of the AES_ICR register. Upon the flag setting, an interrupt is generated if enabled through the CCFIE bit of the AES_IER register. The flag is significant only when the DMAOUTEN bit is 0. It may stay high when DMA_EN is 1.
$00000002 constant AES_AES_ISR_RWEIF                                \ Read or write error interrupt flag This read-only bit is set by hardware when a RDERR or a WRERR error flag is set in the AES_SR register. RWEIF bit is cleared when application sets the corresponding bit of AES_ICR register. An interrupt is generated if the RWEIE bit has been previously set in the AES_IER register. This flags has no meaning when key derivation mode is selected.
$00000004 constant AES_AES_ISR_KEIF                                 \ Key error interrupt flag This read-only bit is set by hardware when key information failed to load into key registers. Setting the corresponding bit of the AES_ICR register clears the KEIF and generates interrupt if the KEIE bit of the AES_IER register is set. KEIF is triggered upon any of the following errors: AES_KEYRx register write does not respect the correct order. (For KEYSIZE = 0, AES_KEYR0 then AES_KEYR1 then AES_KEYR2 then AES_KEYR3 register, or reverse. For KEYSIZE = 1, AES_KEYR0 then AES_KEYR1 then AES_KEYR2 then AES_KEYR3 then AES_KEYR4 then AES_KEYR5 then AES_KEYR6 then AES_KEYR7, or reverse). KEIF must be cleared by the application software, otherwise KEYVALID cannot be set.


\
\ @brief AES interrupt clear register
\ Address offset: 0x308
\ Reset value: 0x00000000
\

$00000001 constant AES_AES_ICR_CCF                                  \ Computation complete flag clear Setting this bit clears the CCF status bit of the AES_SR and AES_ISR registers.
$00000002 constant AES_AES_ICR_RWEIF                                \ Read or write error interrupt flag clear Setting this bit clears the RWEIF status bit of the AES_ISR register, and both RDERR and WRERR flags in the AES_SR register.
$00000004 constant AES_AES_ICR_KEIF                                 \ Key error interrupt flag clear Setting this bit clears the KEIF status bit of the AES_ISR register.


\
\ @brief Advanced encryption standard hardware accelerator
\
$420c0000 constant AES_AES_CR     \ offset: 0x00 : AES control register
$420c0004 constant AES_AES_SR     \ offset: 0x04 : AES status register
$420c0008 constant AES_AES_DINR   \ offset: 0x08 : AES data input register
$420c000c constant AES_AES_DOUTR  \ offset: 0x0C : AES data output register
$420c0010 constant AES_AES_KEYR0  \ offset: 0x10 : AES key register 0
$420c0014 constant AES_AES_KEYR1  \ offset: 0x14 : AES key register 1
$420c0018 constant AES_AES_KEYR2  \ offset: 0x18 : AES key register 2
$420c001c constant AES_AES_KEYR3  \ offset: 0x1C : AES key register 3
$420c0020 constant AES_AES_IVR0   \ offset: 0x20 : AES initialization vector register 0
$420c0024 constant AES_AES_IVR1   \ offset: 0x24 : AES initialization vector register 1
$420c0028 constant AES_AES_IVR2   \ offset: 0x28 : AES initialization vector register 2
$420c002c constant AES_AES_IVR3   \ offset: 0x2C : AES initialization vector register 3
$420c0030 constant AES_AES_KEYR4  \ offset: 0x30 : AES key register 4
$420c0034 constant AES_AES_KEYR5  \ offset: 0x34 : AES key register 5
$420c0038 constant AES_AES_KEYR6  \ offset: 0x38 : AES key register 6
$420c003c constant AES_AES_KEYR7  \ offset: 0x3C : AES key register 7
$420c0040 constant AES_AES_SUSP0R  \ offset: 0x40 : AES suspend registers
$420c0044 constant AES_AES_SUSP1R  \ offset: 0x44 : AES suspend registers
$420c0048 constant AES_AES_SUSP2R  \ offset: 0x48 : AES suspend registers
$420c004c constant AES_AES_SUSP3R  \ offset: 0x4C : AES suspend registers
$420c0050 constant AES_AES_SUSP4R  \ offset: 0x50 : AES suspend registers
$420c0054 constant AES_AES_SUSP5R  \ offset: 0x54 : AES suspend registers
$420c0058 constant AES_AES_SUSP6R  \ offset: 0x58 : AES suspend registers
$420c005c constant AES_AES_SUSP7R  \ offset: 0x5C : AES suspend registers
$420c0300 constant AES_AES_IER    \ offset: 0x300 : AES interrupt enable register
$420c0304 constant AES_AES_ISR    \ offset: 0x304 : AES interrupt status register
$420c0308 constant AES_AES_ICR    \ offset: 0x308 : AES interrupt clear register

