\
\ @file crc.fs
\ @brief Cyclic redundancy check calculation unit
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

.include ../common.fs

\
\ @brief CRC data register
\ Address offset: 0x00
\ Reset value: 0xFFFFFFFF
\

$00000000 constant CRC_CRC_DR_DR                                    \ Data register bits This register is used to write new data to the CRC calculator. It holds the previous CRC calculation result when it is read. If the data size is less than 32 bits, the least significant bits are used to write/read the correct value.


\
\ @brief CRC independent data register
\ Address offset: 0x04
\ Reset value: 0x00000000
\

$00000000 constant CRC_CRC_IDR_IDR                                  \ General-purpose 32-bit data register bits These bits can be used as a temporary storage location for four bytes. This register is not affected by CRC resets generated by the RESET bit in the CRC_CR register


\
\ @brief CRC control register
\ Address offset: 0x08
\ Reset value: 0x00000000
\

$00000001 constant CRC_CRC_CR_RESET                                 \ RESET bit This bit is set by software to reset the CRC calculation unit and set the data register to the value stored in the CRC_INIT register. This bit can only be set, it is automatically cleared by hardware
$00000018 constant CRC_CRC_CR_POLYSIZE                              \ Polynomial size These bits control the size of the polynomial.
$00000060 constant CRC_CRC_CR_REV_IN                                \ Reverse input data These bits control the reversal of the bit order of the input data
$00000080 constant CRC_CRC_CR_REV_OUT                               \ Reverse output data This bit controls the reversal of the bit order of the output data.


\
\ @brief CRC initial value
\ Address offset: 0x10
\ Reset value: 0xFFFFFFFF
\

$00000000 constant CRC_CRC_INIT_CRC_INIT                            \ Programmable initial CRC value This register is used to write the CRC initial value.


\
\ @brief CRC polynomial
\ Address offset: 0x14
\ Reset value: 0x04C11DB7
\

$00000000 constant CRC_CRC_POL_POL                                  \ Programmable polynomial This register is used to write the coefficients of the polynomial to be used for CRC calculation. If the polynomial size is less than 32 bits, the least significant bits have to be used to program the correct value.


\
\ @brief Cyclic redundancy check calculation unit
\
$40023000 constant CRC_CRC_DR     \ offset: 0x00 : CRC data register
$40023004 constant CRC_CRC_IDR    \ offset: 0x04 : CRC independent data register
$40023008 constant CRC_CRC_CR     \ offset: 0x08 : CRC control register
$40023010 constant CRC_CRC_INIT   \ offset: 0x10 : CRC initial value
$40023014 constant CRC_CRC_POL    \ offset: 0x14 : CRC polynomial

