\
\ @file aes.fs
\ @brief Advanced Encryption Standard
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

.include ../common.fs

\
\ @brief AES control register
\ Address offset: 0x00
\ Reset value: 0x00000000
\

$00000001 constant AES_AES_CR_EN                                    \ AES enable This bit enables/disables the AES peripheral: At any moment, clearing then setting the bit re-initializes the AES peripheral. This bit is automatically cleared by hardware upon the completion of the key preparation (Mode 2) and upon the completion of GCM/GMAC/CCM initial phase.
$00000006 constant AES_AES_CR_DATATYPE                              \ Data type selection This bitfield defines the format of data written in the AES_DINR register or read from the AES_DOUTR register, through selecting the mode of data swapping: For more details, refer to . Attempts to write the bitfield are ignored when the EN bit of the AES_CR register is set before the write access and it is not cleared by that write access.
$00000018 constant AES_AES_CR_MODE                                  \ AES operating mode This bitfield selects the AES operating mode: Attempts to write the bitfield are ignored when the EN bit of the AES_CR register is set before the write access and it is not cleared by that write access. Any attempt to selecting Mode 4 while either ECB or CBC chaining mode is not selected, defaults to effective selection of Mode 3. It is not possible to select a Mode 3 following a Mode 4.
$00000060 constant AES_AES_CR_CHMOD1                                \ Chaining mode selection, bit [2] Refer to the bits [5:6] of the register for the description of the CHMOD[2:0] bitfield CHMOD[1:0]: Chaining mode selection, bits [1:0] This bitfield, together with the bit CHMOD[2] forming CHMOD[2:0], selects the AES chaining mode: others: Reserved Attempts to write the bitfield are ignored when the EN bit of the AES_CR register is set before the write access and it is not cleared by that write access.
$00000080 constant AES_AES_CR_CCFC                                  \ Computation complete flag clear Upon written to 1, this bit clears the computation complete flag (CCF) in the AES_SR register: Reading the flag always returns zero.
$00000100 constant AES_AES_CR_ERRC                                  \ Error flag clear Upon written to 1, this bit clears the RDERR and WRERR error flags in the AES_SR register: Reading the flag always returns zero.
$00000200 constant AES_AES_CR_CCFIE                                 \ CCF interrupt enable This bit enables or disables (masks) the AES interrupt generation when CCF (computation complete flag) is set:
$00000400 constant AES_AES_CR_ERRIE                                 \ Error interrupt enable This bit enables or disables (masks) the AES interrupt generation when RDERR and/or WRERR is set:
$00000800 constant AES_AES_CR_DMAINEN                               \ DMA input enable This bit enables/disables data transferring with DMA, in the input phase: When the bit is set, DMA requests are automatically generated by AES during the input data phase. This feature is only effective when Mode 1 or Mode 3 is selected through the MODE[1:0] bitfield. It is not effective for Mode 2 (key derivation). Usage of DMA with Mode 4 (single decryption) is not recommended.
$00001000 constant AES_AES_CR_DMAOUTEN                              \ DMA output enable This bit enables/disables data transferring with DMA, in the output phase: When the bit is set, DMA requests are automatically generated by AES during the output data phase. This feature is only effective when Mode 1 or Mode 3 is selected through the MODE[1:0] bitfield. It is not effective for Mode 2 (key derivation). Usage of DMA with Mode 4 (single decryption) is not recommended.
$00006000 constant AES_AES_CR_GCMPH                                 \ GCM or CCM phase selection This bitfield selects the phase of GCM, GMAC or CCM algorithm: The bitfield has no effect if other than GCM, GMAC or CCM algorithms are selected (through the ALGOMODE bitfield).
$00010000 constant AES_AES_CR_CHMOD2                                \ Chaining mode selection, bit [2] Refer to the bits [5:6] of the register for the description of the CHMOD[2:0] bitfield CHMOD[1:0]: Chaining mode selection, bits [1:0] This bitfield, together with the bit CHMOD[2] forming CHMOD[2:0], selects the AES chaining mode: others: Reserved Attempts to write the bitfield are ignored when the EN bit of the AES_CR register is set before the write access and it is not cleared by that write access.
$00040000 constant AES_AES_CR_KEYSIZE                               \ Key size selection This bitfield defines the length of the key used in the AES cryptographic core, in bits: Attempts to write the bit are ignored when the EN bit of the AES_CR register is set before the write access and it is not cleared by that write access.
$00f00000 constant AES_AES_CR_NPBLB                                 \ Number of padding bytes in last block The bitfield sets the number of padding bytes in last block of payload: ...


\
\ @brief AES status register
\ Address offset: 0x04
\ Reset value: 0x00000000
\

$00000001 constant AES_AES_SR_CCF                                   \ Computation completed flag This flag indicates whether the computation is completed: The flag is set by hardware upon the completion of the computation. It is cleared by software, upon setting the CCFC bit of the AES_CR register. Upon the flag setting, an interrupt is generated if enabled through the CCFIE bit of the AES_CR register. The flag is significant only when the DMAOUTEN bit is 0. It may stay high when DMA_EN is 1.
$00000002 constant AES_AES_SR_RDERR                                 \ Read error flag This flag indicates the detection of an unexpected read operation from the AES_DOUTR register (during computation or data input phase): The flag is set by hardware. It is cleared by software upon setting the ERRC bit of the AES_CR register. Upon the flag setting, an interrupt is generated if enabled through the ERRIE bit of the AES_CR register. The flag setting has no impact on the AES operation. Unexpected read returns zero.
$00000004 constant AES_AES_SR_WRERR                                 \ Write error This flag indicates the detection of an unexpected write operation to the AES_DINR register (during computation or data output phase): The flag is set by hardware. It is cleared by software upon setting the ERRC bit of the AES_CR register. Upon the flag setting, an interrupt is generated if enabled through the ERRIE bit of the AES_CR register. The flag setting has no impact on the AES operation. Unexpected write is ignored.
$00000008 constant AES_AES_SR_BUSY                                  \ Busy


\
\ @brief AES data input register
\ Address offset: 0x08
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_DINR_DIN                                 \ Input data word A four-fold sequential write to this bitfield during the input phase results in writing a complete 128-bit block of input data to the AES peripheral. From the first to the fourth write, the corresponding data weights are [127:96], [95:64], [63:32], and [31:0]. Upon each write, the data from the 32-bit input buffer are handled by the data swap block according to the DATATYPE[1:0] bitfield, then written into the AES core 128-bit input buffer. The data signification of the input data block depends on the AES operating mode: - Mode 1 (encryption): plaintext - Mode 2 (key derivation): the bitfield is not used (AES_KEYRx registers used for input) - Mode 3 (decryption) and Mode 4 (key derivation then single decryption): ciphertext The data swap operation is described in page499.


\
\ @brief AES data output register
\ Address offset: 0x0C
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_DOUTR_DOUT                               \ Output data word This read-only bitfield fetches a 32-bit output buffer. A four-fold sequential read of this bitfield, upon the computation completion (CCF set), virtually reads a complete 128-bit block of output data from the AES peripheral. Before reaching the output buffer, the data produced by the AES core are handled by the data swap block according to the DATATYPE[1:0] bitfield. Data weights from the first to the fourth read operation are: [127:96], [95:64], [63:32], and [31:0]. The data signification of the output data block depends on the AES operating mode: - Mode 1 (encryption): ciphertext - Mode 2 (key derivation): the bitfield is not used (AES_KEYRx registers used for output) - Mode 3 (decryption) and Mode 4 (key derivation then single decryption): plaintext The data swap operation is described in page499.


\
\ @brief AES key register 0
\ Address offset: 0x10
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_KEYR0_KEY                                \ Cryptographic key, bits [31:0] This bitfield contains the bits [31:0] of the AES encryption or decryption key, depending on the operating mode: - In Mode 1 (encryption), Mode 2 (key derivation) and Mode 4 (key derivation then single decryption): the value to write into the bitfield is the encryption key. - In Mode 3 (decryption): the value to write into the bitfield is the encryption key to be derived before being used for decryption. After writing the encryption key into the bitfield, its reading before enabling AES returns the same value. Its reading after enabling AES and after the CCF flag is set returns the decryption key derived from the encryption key. Note: In mode 4 (key derivation then single decryption) the bitfield always contains the encryption key. The AES_KEYRx registers may be written only when KEYSIZE value is correct and when the AES peripheral is disabled (EN bit of the AES_CR register cleared). Note that, if, the key is directly loaded to AES_KEYRx registers (hence writes to key register is ignored and KEIF is set). Refer to for more details.


\
\ @brief AES key register 1
\ Address offset: 0x14
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_KEYR1_KEY                                \ Cryptographic key, bits [63:32] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief AES key register 2
\ Address offset: 0x18
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_KEYR2_KEY                                \ Cryptographic key, bits [95:64] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief AES key register 3
\ Address offset: 0x1C
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_KEYR3_KEY                                \ Cryptographic key, bits [127:96] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief AES initialization vector register 0
\ Address offset: 0x20
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_IVR0_IVI                                 \ Initialization vector input, bits [31:0] Refer to for description of the IVI[127:0] bitfield. The initialization vector is only used in chaining modes other than ECB. The AES_IVRx registers may be written only when the AES peripheral is disabled


\
\ @brief AES initialization vector register 1
\ Address offset: 0x24
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_IVR1_IVI                                 \ Initialization vector input, bits [63:32] Refer to the AES_IVR0 register for description of the IVI[128:0] bitfield.


\
\ @brief AES initialization vector register 2
\ Address offset: 0x28
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_IVR2_IVI                                 \ Initialization vector input, bits [95:64] Refer to the AES_IVR0 register for description of the IVI[128:0] bitfield.


\
\ @brief AES initialization vector register 3
\ Address offset: 0x2C
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_IVR3_IVI                                 \ Initialization vector input, bits [127:96] Refer to the AES_IVR0 register for description of the IVI[128:0] bitfield.


\
\ @brief AES key register 4
\ Address offset: 0x30
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_KEYR4_KEY                                \ Cryptographic key, bits [159:128] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief AES key register 5
\ Address offset: 0x34
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_KEYR5_KEY                                \ Cryptographic key, bits [191:160] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief AES key register 6
\ Address offset: 0x38
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_KEYR6_KEY                                \ Cryptographic key, bits [223:192] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief AES key register 7
\ Address offset: 0x3C
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_KEYR7_KEY                                \ Cryptographic key, bits [255:224] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield.


\
\ @brief AES suspend registers
\ Address offset: 0x40
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_SUSP0R_SUSP                              \ AES suspend Upon suspend operation, this bitfield of every AES_SUSPxR register takes the value of one of internal AES registers.


\
\ @brief AES suspend registers
\ Address offset: 0x44
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_SUSP1R_SUSP                              \ AES suspend Upon suspend operation, this bitfield of every AES_SUSPxR register takes the value of one of internal AES registers.


\
\ @brief AES suspend registers
\ Address offset: 0x48
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_SUSP2R_SUSP                              \ AES suspend Upon suspend operation, this bitfield of every AES_SUSPxR register takes the value of one of internal AES registers.


\
\ @brief AES suspend registers
\ Address offset: 0x4C
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_SUSP3R_SUSP                              \ AES suspend Upon suspend operation, this bitfield of every AES_SUSPxR register takes the value of one of internal AES registers.


\
\ @brief AES suspend registers
\ Address offset: 0x50
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_SUSP4R_SUSP                              \ AES suspend Upon suspend operation, this bitfield of every AES_SUSPxR register takes the value of one of internal AES registers.


\
\ @brief AES suspend registers
\ Address offset: 0x54
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_SUSP5R_SUSP                              \ AES suspend Upon suspend operation, this bitfield of every AES_SUSPxR register takes the value of one of internal AES registers.


\
\ @brief AES suspend registers
\ Address offset: 0x58
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_SUSP6R_SUSP                              \ AES suspend Upon suspend operation, this bitfield of every AES_SUSPxR register takes the value of one of internal AES registers.


\
\ @brief AES suspend registers
\ Address offset: 0x5C
\ Reset value: 0x00000000
\

$00000000 constant AES_AES_SUSP7R_SUSP                              \ AES suspend Upon suspend operation, this bitfield of every AES_SUSPxR register takes the value of one of internal AES registers.


\
\ @brief Advanced Encryption Standard
\
$40026000 constant AES_AES_CR     \ offset: 0x00 : AES control register
$40026004 constant AES_AES_SR     \ offset: 0x04 : AES status register
$40026008 constant AES_AES_DINR   \ offset: 0x08 : AES data input register
$4002600c constant AES_AES_DOUTR  \ offset: 0x0C : AES data output register
$40026010 constant AES_AES_KEYR0  \ offset: 0x10 : AES key register 0
$40026014 constant AES_AES_KEYR1  \ offset: 0x14 : AES key register 1
$40026018 constant AES_AES_KEYR2  \ offset: 0x18 : AES key register 2
$4002601c constant AES_AES_KEYR3  \ offset: 0x1C : AES key register 3
$40026020 constant AES_AES_IVR0   \ offset: 0x20 : AES initialization vector register 0
$40026024 constant AES_AES_IVR1   \ offset: 0x24 : AES initialization vector register 1
$40026028 constant AES_AES_IVR2   \ offset: 0x28 : AES initialization vector register 2
$4002602c constant AES_AES_IVR3   \ offset: 0x2C : AES initialization vector register 3
$40026030 constant AES_AES_KEYR4  \ offset: 0x30 : AES key register 4
$40026034 constant AES_AES_KEYR5  \ offset: 0x34 : AES key register 5
$40026038 constant AES_AES_KEYR6  \ offset: 0x38 : AES key register 6
$4002603c constant AES_AES_KEYR7  \ offset: 0x3C : AES key register 7
$40026040 constant AES_AES_SUSP0R  \ offset: 0x40 : AES suspend registers
$40026044 constant AES_AES_SUSP1R  \ offset: 0x44 : AES suspend registers
$40026048 constant AES_AES_SUSP2R  \ offset: 0x48 : AES suspend registers
$4002604c constant AES_AES_SUSP3R  \ offset: 0x4C : AES suspend registers
$40026050 constant AES_AES_SUSP4R  \ offset: 0x50 : AES suspend registers
$40026054 constant AES_AES_SUSP5R  \ offset: 0x54 : AES suspend registers
$40026058 constant AES_AES_SUSP6R  \ offset: 0x58 : AES suspend registers
$4002605c constant AES_AES_SUSP7R  \ offset: 0x5C : AES suspend registers

