\
\ @file vrefbuf.fs
\ @brief VREFBUF address block description
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

[ifndef] VREFBUF_DEF

  [ifdef] VREFBUF_VREFBUF_CSR_DEF
    \
    \ @brief VREFBUF control and status register
    \ Address offset: 0x00
    \ Reset value: 0x00000002
    \
    $00 constant VREFBUF_ENVR                   \ [0x00] Voltage reference buffer mode enable This bit is used to enable the voltage reference buffer mode.
    $01 constant VREFBUF_HIZ                    \ [0x01] High impedance mode This bit controls the analog switch to connect or not the V<sub>REF+</sub> pin. Refer to Table172: VREF buffer modes for the mode descriptions depending on ENVR bit configuration.
    $02 constant VREFBUF_VRS                    \ [0x02] Voltage reference scale This bit selects the value generated by the voltage reference buffer.
    $03 constant VREFBUF_VRR                    \ [0x03] Voltage reference buffer ready
  [then]


  [ifdef] VREFBUF_VREFBUF_CCR_DEF
    \
    \ @brief VREFBUF calibration control register
    \ Address offset: 0x04
    \ Reset value: 0x00000000
    \
    $00 constant VREFBUF_TRIM                   \ [0x00 : 6] None
  [then]

  \
  \ @brief VREFBUF address block description
  \
  $00 constant VREFBUF_VREFBUF_CSR      \ VREFBUF control and status register
  $04 constant VREFBUF_VREFBUF_CCR      \ VREFBUF calibration control register

: VREFBUF_DEF ; [then]
