\
\ @file sec_aes.fs
\ @brief Advanced encryption standard hardware accelerator
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

.include ../common.fs

\
\ @brief AES control register
\ Address offset: 0x00
\ Reset value: 0x00000000
\

$00000001 constant SEC_AES_AES_CR_EN                                \ Enable This bit enables/disables the AES peripheral. At any moment, clearing then setting the bit re-initializes the AES peripheral. This bit is automatically cleared by hardware upon the completion of the key preparation (MODE[1:0] at 01) and upon the completion of GCM/GMAC/CCM initialization phase. The bit cannot be set as long as KEYVALID=0.
$00000006 constant SEC_AES_AES_CR_DATATYPE                          \ Data type This bitfield defines the format of data written in the AES_DINR register or read from the AES_DOUTR register, through selecting the mode of data swapping. This swapping is defined in Section23.4.17: AES data registers and data swapping. Attempts to write the bitfield are ignored when BUSY is set, as well as when EN is set before the write access and it is not cleared by that write access.
$00000018 constant SEC_AES_AES_CR_MODE                              \ Operating mode This bitfield selects the AES operating mode: Attempts to write the bitfield are ignored when BUSY is set, as well as when EN is set before the write access and it is not cleared by that write access.
$00000060 constant SEC_AES_AES_CR_CHMOD                             \ CHMOD[1:0]: Chaining mode This bitfield selects the AES chaining mode: others: Reserved Attempts to write the bitfield are ignored when BUSY is set, as well as when EN is set before the write access and it is not cleared by that write access.
$00000800 constant SEC_AES_AES_CR_DMAINEN                           \ DMA input enable When this bit is set, DMA requests are automatically generated by the peripheral during the input data phase. Setting this bit is ignored when MODE[1:0] is at 01 (key derivation).
$00001000 constant SEC_AES_AES_CR_DMAOUTEN                          \ DMA output enable When this bit is set, DMA requests are automatically generated by the peripheral during the output data phase. Setting this bit is ignored when MODE[1:0] is at 01 (key derivation).
$00006000 constant SEC_AES_AES_CR_GCMPH                             \ GCM or CCM phase selection This bitfield selects the phase, applicable only with GCM, GMAC or CCM chaining modes. This bitfield has no effect if GCM, GMAC or CCM algorithm is not selected with CHMOD[2:0].
$00010000 constant SEC_AES_AES_CR_CHMOD_1                           \ CHMOD[2]
$00040000 constant SEC_AES_AES_CR_KEYSIZE                           \ Key size selection This bitfield defines the key length in bits of the key used by AES. Attempts to write the bit are ignored when BUSY is set, as well as when the EN is set before the write access and it is not cleared by that write access.
$00f00000 constant SEC_AES_AES_CR_NPBLB                             \ Number of padding bytes in last block This padding information must be filled by software before processing the last block of GCM payload encryption or CCM payload decryption, otherwise authentication tag computation is incorrect. ...
$03000000 constant SEC_AES_AES_CR_KMOD                              \ Key mode selection The bitfield defines how the AES key can be used by the application. KEYSIZE must be correctly initialized when setting KMOD[1:0] different from zero. Others: Reserved Attempts to write the bitfield are ignored when BUSY is set, as well as when EN is set before the write access and it is not cleared by that write access.
$80000000 constant SEC_AES_AES_CR_IPRST                             \ AES peripheral software reset Setting the bit resets the AES peripheral, putting all registers to their default values, except the IPRST bit itself. Hence, any key-relative data are lost. For this reason, it is recommended to set the bit before handing over the AES to a less secure application. The bit must be low while writing any configuration registers.


\
\ @brief AES status register
\ Address offset: 0x04
\ Reset value: 0x00000000
\

$00000002 constant SEC_AES_AES_SR_RDERRF                            \ Read error flag This bit is set when an unexpected read to the AES_DOUTR register occurred. When set RDERRF bit has no impact on the AES operations. This flag is cleared by setting the RWEIF bit in AES_ICR register. If RWEIE bit is set in AES_IER register an interrupt is generated when RDERRF is set. It is cleared by setting the RWEIF bit of the AES_ICR register.
$00000004 constant SEC_AES_AES_SR_WRERRF                            \ Write error flag This bit is set when an unexpected write to the AES_DINR register occurred. When set WRERRF bit has no impact on the AES operations. This flag is cleared by setting the RWEIF bit in AES_ICR register. If RWEIE bit is set in AES_IER register an interrupt is generated when WRERRF is set. It is cleared by setting the RWEIF bit of the AES_ICR register.
$00000008 constant SEC_AES_AES_SR_BUSY                              \ Busy This flag indicates whether AES is idle or busy. AES is flagged as idle when disabled or when the last processing is completed. AES is flagged as busy when processing a block data, preparing a key (ECB or CBC decryption only), or transferring a shared key from SAES peripheral. When GCM encryption is selected, this flag must be at zero before suspending current process to manage a higher-priority message.
$00000080 constant SEC_AES_AES_SR_KEYVALID                          \ Key valid flag This bit is set by hardware when the key of size defined by KEYSIZE is loaded in AES_KEYRx key registers. The EN bit can only be set when KEYVALID is set. In normal mode when KEYSEL[2:0] is at 000, the key must be written in the key registers in the correct sequence, otherwise the KEIF flag is set and KEYVALID remains cleared. When KEYSEL[2:0] is different from zero, the BUSY flag is automatically set by AES. When the key is loaded successfully, BUSY is cleared and KEYVALID set. Upon an error, KEIF is set, BUSY cleared and KEYVALID remains cleared. If set, KEIF must be cleared through the AES_ICR register, otherwise KEYVALID cannot be set. See the KEIF flag description for more details. For further information on key loading, refer to Section23.4.18: AES key registers.


\
\ @brief AES data input register
\ Address offset: 0x08
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_DINR_DIN                             \ Input data word A four-fold sequential write to this bitfield during the Input phase results in writing a complete 16-bytes block of input data to the AES peripheral. From the first to the fourth write, the corresponding data weights are [127:96], [95:64], [63:32], and [31:0]. Upon each write, the data from the 32-bit input buffer are handled by the data swap block according to the DATATYPE[1:0] bitfield, then written into the AES core 16-bytes input buffer. Reads return zero.


\
\ @brief AES data output register
\ Address offset: 0x0C
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_DOUTR_DOUT                           \ Output data word This read-only bitfield fetches a 32-bit output buffer. A four-fold sequential read of this bitfield, upon the computation completion (CCF flag set), virtually reads a complete 16-byte block of output data from the AES peripheral. Before reaching the output buffer, the data produced by the AES core are handled by the data swap block according to the DATATYPE[1:0] bitfield. Data weights from the first to the fourth read operation are: [127:96], [95:64], [63:32], and [31:0].


\
\ @brief AES key register 0
\ Address offset: 0x10
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_KEYR0_KEY                            \ Cryptographic key, bits [31:0] This write-only bitfield contains the bits [31:0] of the AES encryption or decryption key, depending on the operating mode MODE[1:0] in AES_CR. The AES_KEYRx registers may be written only when KEYSIZE value is correct and when the AES peripheral is disabled (EN bit of the AES_CR register cleared). A special writing sequence is also required, as described in KEYVALID bit of the AES_SR register. Note that, if KMOD[1:0] is at 10 (shared key), the key is directly loaded from SAES peripheral to AES_KEYRx registers (hence writes to key register is ignored and KEIF is set). When KEYVALID is set a write to this register clears KEYVALID if AES is disabled.


\
\ @brief AES key register 1
\ Address offset: 0x14
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_KEYR1_KEY                            \ Cryptographic key, bits [63:32] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield. When KEYVALID is set in AES_SR a write to this register clears KEYVALID if EN is cleared in AES_CR.


\
\ @brief AES key register 2
\ Address offset: 0x18
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_KEYR2_KEY                            \ Cryptographic key, bits [95:64] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield. When KEYVALID is set in AES_SR a write to this register clears KEYVALID if EN is cleared in AES_CR.


\
\ @brief AES key register 3
\ Address offset: 0x1C
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_KEYR3_KEY                            \ Cryptographic key, bits [127:96] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield. When KEYVALID is set in AES_SR a write to this register clears KEYVALID if EN is cleared in AES_CR.


\
\ @brief AES initialization vector register 0
\ Address offset: 0x20
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_IVR0_IVI                             \ Initialization vector input, bits [31:0] AES_IVRx registers store the 128-bit initialization vector or the nonce, depending on the chaining mode selected. This value is updated by the AES core after each computation round (when applicable). Write to this register is ignored when EN bit is set in AES_SR register


\
\ @brief AES initialization vector register 1
\ Address offset: 0x24
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_IVR1_IVI                             \ Initialization vector input, bits [63:32] Refer to the AES_IVR0 register for description of the IVI[128:0] bitfield.


\
\ @brief AES initialization vector register 2
\ Address offset: 0x28
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_IVR2_IVI                             \ Initialization vector input, bits [95:64] Refer to the AES_IVR0 register for description of the IVI[128:0] bitfield.


\
\ @brief AES initialization vector register 3
\ Address offset: 0x2C
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_IVR3_IVI                             \ Initialization vector input, bits [127:96] Refer to the AES_IVR0 register for description of the IVI[128:0] bitfield.


\
\ @brief AES key register 4
\ Address offset: 0x30
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_KEYR4_KEY                            \ Cryptographic key, bits [159:128] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield. Writing to this register has no effect when key size is 128-bit (KEYSIZE=0). When KEYVALID is set in AES_SR a write to this register clears KEYVALID if EN is cleared in AES_CR.


\
\ @brief AES key register 5
\ Address offset: 0x34
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_KEYR5_KEY                            \ Cryptographic key, bits [191:160] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield. Writing to this register has no effect when key size is 128-bit (KEYSIZE=0). When KEYVALID is set in AES_SR a write to this register clears KEYVALID if EN is cleared in AES_CR.


\
\ @brief AES key register 6
\ Address offset: 0x38
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_KEYR6_KEY                            \ Cryptographic key, bits [223:192] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield. Writing to this register has no effect when key size is 128-bit (KEYSIZE=0). When KEYVALID is set in AES_SR a write to this register clears KEYVALID if EN is cleared in AES_CR.


\
\ @brief AES key register 7
\ Address offset: 0x3C
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_KEYR7_KEY                            \ Cryptographic key, bits [255:224] Refer to the AES_KEYR0 register for description of the KEY[255:0] bitfield. Writing to this register has no effect when key size is 128-bit (KEYSIZE=0). When KEYVALID is set in AES_SR a write to this register clears KEYVALID if EN is cleared in AES_CR.


\
\ @brief AES suspend registers
\ Address offset: 0x40
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_SUSPR0_SUSP                          \ Suspend data AES_SUSPRx registers contain the complete internal register states of the AES when the GCM, GMAC or CCM processing of the current task is suspended to process a higher-priority task. Refer to Section23.4.8: AES suspend and resume operations for more details. Read to this register returns zero when EN bit is cleared in AES_SR register. AES_SUSPRx registers are not used in other chaining modes than GCM, GMAC or CCM.


\
\ @brief AES suspend registers
\ Address offset: 0x44
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_SUSPR1_SUSP                          \ Suspend data AES_SUSPRx registers contain the complete internal register states of the AES when the GCM, GMAC or CCM processing of the current task is suspended to process a higher-priority task. Refer to Section23.4.8: AES suspend and resume operations for more details. Read to this register returns zero when EN bit is cleared in AES_SR register. AES_SUSPRx registers are not used in other chaining modes than GCM, GMAC or CCM.


\
\ @brief AES suspend registers
\ Address offset: 0x48
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_SUSPR2_SUSP                          \ Suspend data AES_SUSPRx registers contain the complete internal register states of the AES when the GCM, GMAC or CCM processing of the current task is suspended to process a higher-priority task. Refer to Section23.4.8: AES suspend and resume operations for more details. Read to this register returns zero when EN bit is cleared in AES_SR register. AES_SUSPRx registers are not used in other chaining modes than GCM, GMAC or CCM.


\
\ @brief AES suspend registers
\ Address offset: 0x4C
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_SUSPR3_SUSP                          \ Suspend data AES_SUSPRx registers contain the complete internal register states of the AES when the GCM, GMAC or CCM processing of the current task is suspended to process a higher-priority task. Refer to Section23.4.8: AES suspend and resume operations for more details. Read to this register returns zero when EN bit is cleared in AES_SR register. AES_SUSPRx registers are not used in other chaining modes than GCM, GMAC or CCM.


\
\ @brief AES suspend registers
\ Address offset: 0x50
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_SUSPR4_SUSP                          \ Suspend data AES_SUSPRx registers contain the complete internal register states of the AES when the GCM, GMAC or CCM processing of the current task is suspended to process a higher-priority task. Refer to Section23.4.8: AES suspend and resume operations for more details. Read to this register returns zero when EN bit is cleared in AES_SR register. AES_SUSPRx registers are not used in other chaining modes than GCM, GMAC or CCM.


\
\ @brief AES suspend registers
\ Address offset: 0x54
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_SUSPR5_SUSP                          \ Suspend data AES_SUSPRx registers contain the complete internal register states of the AES when the GCM, GMAC or CCM processing of the current task is suspended to process a higher-priority task. Refer to Section23.4.8: AES suspend and resume operations for more details. Read to this register returns zero when EN bit is cleared in AES_SR register. AES_SUSPRx registers are not used in other chaining modes than GCM, GMAC or CCM.


\
\ @brief AES suspend registers
\ Address offset: 0x58
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_SUSPR6_SUSP                          \ Suspend data AES_SUSPRx registers contain the complete internal register states of the AES when the GCM, GMAC or CCM processing of the current task is suspended to process a higher-priority task. Refer to Section23.4.8: AES suspend and resume operations for more details. Read to this register returns zero when EN bit is cleared in AES_SR register. AES_SUSPRx registers are not used in other chaining modes than GCM, GMAC or CCM.


\
\ @brief AES suspend registers
\ Address offset: 0x5C
\ Reset value: 0x00000000
\

$00000000 constant SEC_AES_AES_SUSPR7_SUSP                          \ Suspend data AES_SUSPRx registers contain the complete internal register states of the AES when the GCM, GMAC or CCM processing of the current task is suspended to process a higher-priority task. Refer to Section23.4.8: AES suspend and resume operations for more details. Read to this register returns zero when EN bit is cleared in AES_SR register. AES_SUSPRx registers are not used in other chaining modes than GCM, GMAC or CCM.


\
\ @brief AES interrupt enable register
\ Address offset: 0x300
\ Reset value: 0x00000000
\

$00000001 constant SEC_AES_AES_IER_CCFIE                            \ Computation complete flag interrupt enable This bit enables or disables (masks) the AES interrupt generation when CCF (computation complete flag) is set.
$00000002 constant SEC_AES_AES_IER_RWEIE                            \ Read or write error interrupt enable This bit enables or disables (masks) the AES interrupt generation when RWEIF (read and/or write error flag) is set.
$00000004 constant SEC_AES_AES_IER_KEIE                             \ Key error interrupt enable This bit enables or disables (masks) the AES interrupt generation when KEIF (key error flag) is set.


\
\ @brief AES interrupt status register
\ Address offset: 0x304
\ Reset value: 0x00000000
\

$00000001 constant SEC_AES_AES_ISR_CCF                              \ Computation complete flag This flag indicates whether the computation is completed. It is significant only when the DMAOUTEN bit is cleared, and it may stay high when DMAOUTEN is set. CCF bit is cleared when application sets the corresponding bit of AES_ICR register. An interrupt is generated if the CCFIE bit has been previously set in the AES_IER register.
$00000002 constant SEC_AES_AES_ISR_RWEIF                            \ Read or write error interrupt flag This read-only bit is set by hardware when a RDERRF or a WRERRF error flag is set in the AES_SR register. RWEIF bit is cleared when application sets the corresponding bit of AES_ICR register. An interrupt is generated if the RWEIE bit has been previously set in the AES_IER register. This flags has no meaning when key derivation mode is selected.
$00000004 constant SEC_AES_AES_ISR_KEIF                             \ Key error interrupt flag This read-only bit is set by hardware when key information failed to load into key registers. Setting the corresponding bit of the AES_ICR register clears the KEIF and generates interrupt if the KEIE bit of the AES_IER register is set. KEIF is triggered upon any of the following errors: AES_KEYRx register write does not respect the correct order. (For KEYSIZE=0, AES_KEYR0 then AES_KEYR1 then AES_KEYR2 then AES_KEYR3 register, or reverse. For KEYSIZE set, AES_KEYR0 then AES_KEYR1 then AES_KEYR2 then AES_KEYR3 then AES_KEYR4 then AES_KEYR5 then AES_KEYR6 then AES_KEYR7, or reverse). KEIF must be cleared by the application software, otherwise KEYVALID cannot be set.


\
\ @brief AES interrupt clear register
\ Address offset: 0x308
\ Reset value: 0x00000000
\

$00000001 constant SEC_AES_AES_ICR_CCF                              \ Computation complete flag clear Setting this bit clears the CCF status bit of the AES_ISR register.
$00000002 constant SEC_AES_AES_ICR_RWEIF                            \ Read or write error interrupt flag clear Setting this bit clears the RWEIF status bit of the AES_ISR register, and clears both RDERRF and WRERRF flags in the AES_SR register.
$00000004 constant SEC_AES_AES_ICR_KEIF                             \ Key error interrupt flag clear Setting this bit clears the KEIF status bit of the AES_ISR register.


\
\ @brief Advanced encryption standard hardware accelerator
\
$520c0000 constant SEC_AES_AES_CR  \ offset: 0x00 : AES control register
$520c0004 constant SEC_AES_AES_SR  \ offset: 0x04 : AES status register
$520c0008 constant SEC_AES_AES_DINR  \ offset: 0x08 : AES data input register
$520c000c constant SEC_AES_AES_DOUTR  \ offset: 0x0C : AES data output register
$520c0010 constant SEC_AES_AES_KEYR0  \ offset: 0x10 : AES key register 0
$520c0014 constant SEC_AES_AES_KEYR1  \ offset: 0x14 : AES key register 1
$520c0018 constant SEC_AES_AES_KEYR2  \ offset: 0x18 : AES key register 2
$520c001c constant SEC_AES_AES_KEYR3  \ offset: 0x1C : AES key register 3
$520c0020 constant SEC_AES_AES_IVR0  \ offset: 0x20 : AES initialization vector register 0
$520c0024 constant SEC_AES_AES_IVR1  \ offset: 0x24 : AES initialization vector register 1
$520c0028 constant SEC_AES_AES_IVR2  \ offset: 0x28 : AES initialization vector register 2
$520c002c constant SEC_AES_AES_IVR3  \ offset: 0x2C : AES initialization vector register 3
$520c0030 constant SEC_AES_AES_KEYR4  \ offset: 0x30 : AES key register 4
$520c0034 constant SEC_AES_AES_KEYR5  \ offset: 0x34 : AES key register 5
$520c0038 constant SEC_AES_AES_KEYR6  \ offset: 0x38 : AES key register 6
$520c003c constant SEC_AES_AES_KEYR7  \ offset: 0x3C : AES key register 7
$520c0040 constant SEC_AES_AES_SUSPR0  \ offset: 0x40 : AES suspend registers
$520c0044 constant SEC_AES_AES_SUSPR1  \ offset: 0x44 : AES suspend registers
$520c0048 constant SEC_AES_AES_SUSPR2  \ offset: 0x48 : AES suspend registers
$520c004c constant SEC_AES_AES_SUSPR3  \ offset: 0x4C : AES suspend registers
$520c0050 constant SEC_AES_AES_SUSPR4  \ offset: 0x50 : AES suspend registers
$520c0054 constant SEC_AES_AES_SUSPR5  \ offset: 0x54 : AES suspend registers
$520c0058 constant SEC_AES_AES_SUSPR6  \ offset: 0x58 : AES suspend registers
$520c005c constant SEC_AES_AES_SUSPR7  \ offset: 0x5C : AES suspend registers
$520c0300 constant SEC_AES_AES_IER  \ offset: 0x300 : AES interrupt enable register
$520c0304 constant SEC_AES_AES_ISR  \ offset: 0x304 : AES interrupt status register
$520c0308 constant SEC_AES_AES_ICR  \ offset: 0x308 : AES interrupt clear register

