\
\ @file sec_usart1.fs
\ @brief USART register block
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

.include ../common.fs

\
\ @brief USART control register 1 [alternate]
\ Address offset: 0x00
\ Reset value: 0x00000000
\

$00000001 constant SEC_USART1_USART_CR1_UE                          \ USART enable When this bit is cleared, the USART prescalers and outputs are stopped immediately, and all current operations are discarded. The USART configuration is kept, but all the USART_ISR status flags are reset. This bit is set and cleared by software. Note: To enter low-power mode without generating errors on the line, the TE bit must be previously reset and the software must wait for the TC bit in the USART_ISR to be set before resetting the UE bit. Note: The DMA requests are also reset when UE = 0 so the DMA channel must be disabled before resetting the UE bit. Note: In Smartcard mode, (SCEN = 1), the CK is always available when CLKEN = 1, regardless of the UE bit value.
$00000002 constant SEC_USART1_USART_CR1_UESM                        \ USART enable in low-power mode When this bit is cleared, the USART cannot request its kernel clock and is not functional in low-power mode. When this bit is set, the USART can wake up the MCU from low-power mode. This bit is set and cleared by software. Note: The UESM bit must be set at the initialization phase. Note: If the USART does not support the wakeup from low-power mode, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000004 constant SEC_USART1_USART_CR1_RE                          \ Receiver enable This bit enables the receiver. It is set and cleared by software.
$00000008 constant SEC_USART1_USART_CR1_TE                          \ Transmitter enable This bit enables the transmitter. When the Autonomous mode is not used, TE bit is set and cleared by software. When the Autonomous mode is used, TE bit becomes a status bit, which is set and cleared by hardware. Note: During transmission, a low pulse on the TE bit (0 followed by 1) sends a preamble (idle line) after the current word, except in Smartcard mode. In order to generate an idle character, the TE must not be immediately written to 1. To ensure the required duration, the software can poll the TEACK bit in the USART_ISR register. Note: In Smartcard mode, when TE is set, there is a 1 bit-time delay before the transmission starts.
$00000010 constant SEC_USART1_USART_CR1_IDLEIE                      \ IDLE interrupt enable This bit is set and cleared by software.
$00000020 constant SEC_USART1_USART_CR1_RXFNEIE                     \ RXFIFO not empty interrupt enable This bit is set and cleared by software.
$00000040 constant SEC_USART1_USART_CR1_TCIE                        \ Transmission complete interrupt enable This bit is set and cleared by software.
$00000080 constant SEC_USART1_USART_CR1_TXFNFIE                     \ TXFIFO not full interrupt enable This bit is set and cleared by software.
$00000100 constant SEC_USART1_USART_CR1_PEIE                        \ PE interrupt enable This bit is set and cleared by software.
$00000200 constant SEC_USART1_USART_CR1_PS                          \ Parity selection This bit selects the odd or even parity when the parity generation/detection is enabled (PCE bit set). It is set and cleared by software. The parity is selected after the current byte. This bitfield can only be written when the USART is disabled (UE=0).
$00000400 constant SEC_USART1_USART_CR1_PCE                         \ Parity control enable This bit selects the hardware parity control (generation and detection). When the parity control is enabled, the computed parity is inserted at the MSB position (9th bit if M=1; 8th bit if M=0) and the parity is checked on the received data. This bit is set and cleared by software. Once it is set, PCE is active after the current byte (in reception and in transmission). This bitfield can only be written when the USART is disabled (UE=0).
$00000800 constant SEC_USART1_USART_CR1_WAKE                        \ Receiver wakeup method This bit determines the USART wakeup method from Mute mode. It is set or cleared by software. This bitfield can only be written when the USART is disabled (UE=0).
$00001000 constant SEC_USART1_USART_CR1_M0                          \ Word length This bit is used in conjunction with bit 28 (M1) to determine the word length. It is set or cleared by software (refer to bit 28 (M1)description). This bit can only be written when the USART is disabled (UE=0).
$00002000 constant SEC_USART1_USART_CR1_MME                         \ Mute mode enable This bit enables the USART Mute mode function. When set, the USART can switch between active and Mute mode, as defined by the WAKE bit. It is set and cleared by software.
$00004000 constant SEC_USART1_USART_CR1_CMIE                        \ Character match interrupt enable This bit is set and cleared by software.
$00008000 constant SEC_USART1_USART_CR1_OVER8                       \ Oversampling mode This bit can only be written when the USART is disabled (UE=0). Note: In LIN, IrDA and Smartcard modes, this bit must be kept cleared.
$001f0000 constant SEC_USART1_USART_CR1_DEDT                        \ Driver Enable deassertion time This 5-bit value defines the time between the end of the last stop bit, in a transmitted message, and the de-activation of the DE (Driver Enable) signal. It is expressed in sample time units (1/8 or 1/16 bit time, depending on the oversampling rate). If the USART_TDR register is written during the DEDT time, the new data is transmitted only when the DEDT and DEAT times have both elapsed. This bitfield can only be written when the USART is disabled (UE=0). Note: If the Driver Enable feature is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$03e00000 constant SEC_USART1_USART_CR1_DEAT                        \ Driver Enable assertion time This 5-bit value defines the time between the activation of the DE (Driver Enable) signal and the beginning of the start bit. It is expressed in sample time units (1/8 or 1/16 bit time, depending on the oversampling rate). This bitfield can only be written when the USART is disabled (UE=0). Note: If the Driver Enable feature is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$04000000 constant SEC_USART1_USART_CR1_RTOIE                       \ Receiver timeout interrupt enable This bit is set and cleared by software. Note: If the USART does not support the Receiver timeout feature, this bit is reserved and must be kept at reset value. Section 78.4: USART implementation on page 4565.
$08000000 constant SEC_USART1_USART_CR1_EOBIE                       \ End of Block interrupt enable This bit is set and cleared by software. Note: If the USART does not support Smartcard mode, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$10000000 constant SEC_USART1_USART_CR1_M1                          \ Word length This bit must be used in conjunction with bit 12 (M0) to determine the word length. It is set or cleared by software. M[1:0] = 00: 1 start bit, 8 Data bits, n Stop bit M[1:0] = 01: 1 start bit, 9 Data bits, n Stop bit M[1:0] = 10: 1 start bit, 7 Data bits, n Stop bit This bit can only be written when the USART is disabled (UE=0). Note: In 7-bits data length mode, the Smartcard mode, LIN master mode and auto baud rate (0x7F and 0x55 frames detection) are not supported.
$20000000 constant SEC_USART1_USART_CR1_FIFOEN                      \ FIFO mode enable This bit is set and cleared by software. This bitfield can only be written when the USART is disabled (UE=0). Note: FIFO mode can be used on standard UART communication, in SPI Master/Slave mode and in Smartcard modes only. It must not be enabled in IrDA and LIN modes.
$40000000 constant SEC_USART1_USART_CR1_TXFEIE                      \ TXFIFO empty interrupt enable This bit is set and cleared by software.
$80000000 constant SEC_USART1_USART_CR1_RXFFIE                      \ RXFIFO Full interrupt enable This bit is set and cleared by software.


\
\ @brief USART control register 1 [alternate]
\ Address offset: 0x00
\ Reset value: 0x00000000
\

$00000001 constant SEC_USART1_USART_CR1_ALTERNATE1_UE               \ USART enable When this bit is cleared, the USART prescalers and outputs are stopped immediately, and all current operations are discarded. The USART configuration is kept, but all the USART_ISR status flags are reset. This bit is set and cleared by software. Note: To enter low-power mode without generating errors on the line, the TE bit must be previously reset and the software must wait for the TC bit in the USART_ISR to be set before resetting the UE bit. Note: The DMA requests are also reset when UE = 0 so the DMA channel must be disabled before resetting the UE bit. Note: In Smartcard mode, (SCEN = 1), the CK is always available when CLKEN = 1, regardless of the UE bit value.
$00000002 constant SEC_USART1_USART_CR1_ALTERNATE1_UESM             \ USART enable in low-power mode When this bit is cleared, the USART cannot request its kernel clock and is not functional in low-power mode. When this bit is set, the USART can wake up the MCU from low-power mode. This bit is set and cleared by software. Note: The UESM bit must be set at the initialization phase. Note: If the USART does not support the wakeup from low-power mode, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000004 constant SEC_USART1_USART_CR1_ALTERNATE1_RE               \ Receiver enable This bit enables the receiver. It is set and cleared by software.
$00000008 constant SEC_USART1_USART_CR1_ALTERNATE1_TE               \ Transmitter enable This bit enables the transmitter. When the Autonomous mode is not used, TE bit is set and cleared by software. When the Autonomous mode is used, TE bit becomes a status bit, which is set and cleared by hardware. Note: During transmission, a low pulse on the TE bit (0 followed by 1) sends a preamble (idle line) after the current word, except in Smartcard mode. In order to generate an idle character, the TE must not be immediately written to 1. To ensure the required duration, the software can poll the TEACK bit in the USART_ISR register. Note: In Smartcard mode, when TE is set, there is a 1 bit-time delay before the transmission starts.
$00000010 constant SEC_USART1_USART_CR1_ALTERNATE1_IDLEIE           \ IDLE interrupt enable This bit is set and cleared by software.
$00000020 constant SEC_USART1_USART_CR1_ALTERNATE1_RXNEIE           \ Receive data register not empty This bit is set and cleared by software.
$00000040 constant SEC_USART1_USART_CR1_ALTERNATE1_TCIE             \ Transmission complete interrupt enable This bit is set and cleared by software.
$00000080 constant SEC_USART1_USART_CR1_ALTERNATE1_TXEIE            \ Transmit data register empty This bit is set and cleared by software.
$00000100 constant SEC_USART1_USART_CR1_ALTERNATE1_PEIE             \ PE interrupt enable This bit is set and cleared by software.
$00000200 constant SEC_USART1_USART_CR1_ALTERNATE1_PS               \ Parity selection This bit selects the odd or even parity when the parity generation/detection is enabled (PCE bit set). It is set and cleared by software. The parity is selected after the current byte. This bitfield can only be written when the USART is disabled (UE=0).
$00000400 constant SEC_USART1_USART_CR1_ALTERNATE1_PCE              \ Parity control enable This bit selects the hardware parity control (generation and detection). When the parity control is enabled, the computed parity is inserted at the MSB position (9th bit if M=1; 8th bit if M=0) and the parity is checked on the received data. This bit is set and cleared by software. Once it is set, PCE is active after the current byte (in reception and in transmission). This bitfield can only be written when the USART is disabled (UE=0).
$00000800 constant SEC_USART1_USART_CR1_ALTERNATE1_WAKE             \ Receiver wakeup method This bit determines the USART wakeup method from Mute mode. It is set or cleared by software. This bitfield can only be written when the USART is disabled (UE=0).
$00001000 constant SEC_USART1_USART_CR1_ALTERNATE1_M0               \ Word length This bit is used in conjunction with bit 28 (M1) to determine the word length. It is set or cleared by software (refer to bit 28 (M1)description). This bit can only be written when the USART is disabled (UE=0).
$00002000 constant SEC_USART1_USART_CR1_ALTERNATE1_MME              \ Mute mode enable This bit enables the USART Mute mode function. When set, the USART can switch between active and Mute mode, as defined by the WAKE bit. It is set and cleared by software.
$00004000 constant SEC_USART1_USART_CR1_ALTERNATE1_CMIE             \ Character match interrupt enable This bit is set and cleared by software.
$00008000 constant SEC_USART1_USART_CR1_ALTERNATE1_OVER8            \ Oversampling mode This bit can only be written when the USART is disabled (UE=0). Note: In LIN, IrDA and Smartcard modes, this bit must be kept cleared.
$001f0000 constant SEC_USART1_USART_CR1_ALTERNATE1_DEDT             \ Driver Enable deassertion time This 5-bit value defines the time between the end of the last stop bit, in a transmitted message, and the de-activation of the DE (Driver Enable) signal. It is expressed in sample time units (1/8 or 1/16 bit time, depending on the oversampling rate). If the USART_TDR register is written during the DEDT time, the new data is transmitted only when the DEDT and DEAT times have both elapsed. This bitfield can only be written when the USART is disabled (UE=0). Note: If the Driver Enable feature is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$03e00000 constant SEC_USART1_USART_CR1_ALTERNATE1_DEAT             \ Driver Enable assertion time This 5-bit value defines the time between the activation of the DE (Driver Enable) signal and the beginning of the start bit. It is expressed in sample time units (1/8 or 1/16 bit time, depending on the oversampling rate). This bitfield can only be written when the USART is disabled (UE=0). Note: If the Driver Enable feature is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$04000000 constant SEC_USART1_USART_CR1_ALTERNATE1_RTOIE            \ Receiver timeout interrupt enable This bit is set and cleared by software. Note: If the USART does not support the Receiver timeout feature, this bit is reserved and must be kept at reset value. Section 78.4: USART implementation on page 4565.
$08000000 constant SEC_USART1_USART_CR1_ALTERNATE1_EOBIE            \ End of Block interrupt enable This bit is set and cleared by software. Note: If the USART does not support Smartcard mode, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$10000000 constant SEC_USART1_USART_CR1_ALTERNATE1_M1               \ Word length This bit must be used in conjunction with bit 12 (M0) to determine the word length. It is set or cleared by software. M[1:0] = 00: 1 start bit, 8 Data bits, n Stop bit M[1:0] = 01: 1 start bit, 9 Data bits, n Stop bit M[1:0] = 10: 1 start bit, 7 Data bits, n Stop bit This bit can only be written when the USART is disabled (UE=0). Note: In 7-bits data length mode, the Smartcard mode, LIN master mode and auto baud rate (0x7F and 0x55 frames detection) are not supported.
$20000000 constant SEC_USART1_USART_CR1_ALTERNATE1_FIFOEN           \ FIFO mode enable This bit is set and cleared by software. This bitfield can only be written when the USART is disabled (UE=0). Note: FIFO mode can be used on standard UART communication, in SPI Master/Slave mode and in Smartcard modes only. It must not be enabled in IrDA and LIN modes.


\
\ @brief USART control register 2
\ Address offset: 0x04
\ Reset value: 0x00000000
\

$00000001 constant SEC_USART1_USART_CR2_SLVEN                       \ Synchronous Slave mode enable When the SLVEN bit is set, the Synchronous slave mode is enabled. Note: When SPI slave mode is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000008 constant SEC_USART1_USART_CR2_DIS_NSS                     \ When the DIS_NSS bit is set, the NSS pin input is ignored. Note: When SPI slave mode is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000010 constant SEC_USART1_USART_CR2_ADDM7                       \ 7-bit Address Detection/4-bit Address Detection This bit is for selection between 4-bit address detection or 7-bit address detection. This bit can only be written when the USART is disabled (UE=0) Note: In 7-bit and 9-bit data modes, the address detection is done on 6-bit and 8-bit address (ADD[5:0] and ADD[7:0]) respectively.
$00000020 constant SEC_USART1_USART_CR2_LBDL                        \ LIN break detection length This bit is for selection between 11 bit or 10 bit break detection. This bit can only be written when the USART is disabled (UE=0). Note: If LIN mode is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000040 constant SEC_USART1_USART_CR2_LBDIE                       \ LIN break detection interrupt enable Break interrupt mask (break detection using break delimiter). Note: If LIN mode is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000100 constant SEC_USART1_USART_CR2_LBCL                        \ Last bit clock pulse This bit is used to select whether the clock pulse associated with the last data bit transmitted (MSB) has to be output on the CK pin in Synchronous mode. The last bit is the 7th or 8th or 9th data bit transmitted depending on the 7 or 8 or 9 bit format selected by the M bit in the USART_CR1 register. This bit can only be written when the USART is disabled (UE=0). Note: If Synchronous mode is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000200 constant SEC_USART1_USART_CR2_CPHA                        \ Clock phase This bit is used to select the phase of the clock output on the CK pin in Synchronous mode. It works in conjunction with the CPOL bit to produce the desired clock/data relationship (see Figure 933 and Figure 934) This bit can only be written when the USART is disabled (UE=0). Note: If Synchronous mode is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000400 constant SEC_USART1_USART_CR2_CPOL                        \ Clock polarity This bit enables the user to select the polarity of the clock output on the CK pin in Synchronous mode. It works in conjunction with the CPHA bit to produce the desired clock/data relationship This bit can only be written when the USART is disabled (UE=0). Note: If Synchronous mode is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000800 constant SEC_USART1_USART_CR2_CLKEN                       \ Clock enable This bit enables the user to enable the CK pin. This bit can only be written when the USART is disabled (UE=0). Note: If neither Synchronous mode nor Smartcard mode is supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565. In Smartcard mode, in order to provide correctly the CK clock to the smartcard, the steps below must be respected: UE = 0 SCEN = 1 GTPR configuration CLKEN= 1 Note: UE = 1
$00003000 constant SEC_USART1_USART_CR2_STOP                        \ stop bits These bits are used for programming the stop bits. This bitfield can only be written when the USART is disabled (UE=0).
$00004000 constant SEC_USART1_USART_CR2_LINEN                       \ LIN mode enable This bit is set and cleared by software. The LIN mode enables the capability to send LIN synchronous breaks (13 low bits) using the SBKRQ bit in the USART_CR1 register, and to detect LIN Sync breaks. This bitfield can only be written when the USART is disabled (UE=0). Note: If the USART does not support LIN mode, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00008000 constant SEC_USART1_USART_CR2_SWAP                        \ Swap TX/RX pins This bit is set and cleared by software. This bitfield can only be written when the USART is disabled (UE=0).
$00010000 constant SEC_USART1_USART_CR2_RXINV                       \ RX pin active level inversion This bit is set and cleared by software. This enables the use of an external inverter on the RX line. This bitfield can only be written when the USART is disabled (UE=0).
$00020000 constant SEC_USART1_USART_CR2_TXINV                       \ TX pin active level inversion This bit is set and cleared by software. This enables the use of an external inverter on the TX line. This bitfield can only be written when the USART is disabled (UE=0).
$00040000 constant SEC_USART1_USART_CR2_DATAINV                     \ Binary data inversion This bit is set and cleared by software. This bitfield can only be written when the USART is disabled (UE=0).
$00080000 constant SEC_USART1_USART_CR2_MSBFIRST                    \ Most significant bit first This bit is set and cleared by software. This bitfield can only be written when the USART is disabled (UE=0).
$00100000 constant SEC_USART1_USART_CR2_ABREN                       \ Auto baud rate enable This bit is set and cleared by software. Note: If the USART does not support the auto baud rate feature, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00600000 constant SEC_USART1_USART_CR2_ABRMOD                      \ Auto baud rate mode These bits are set and cleared by software. This bitfield can only be written when ABREN = 0 or the USART is disabled (UE=0). Note: If DATAINV=1 and/or MSBFIRST=1 the patterns must be the same on the line, for example 0xAA for MSBFIRST) Note: If the USART does not support the auto baud rate feature, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00800000 constant SEC_USART1_USART_CR2_RTOEN                       \ Receiver timeout enable This bit is set and cleared by software. When this feature is enabled, the RTOF flag in the USART_ISR register is set if the RX line is idle (no reception) for the duration programmed in the RTOR (receiver timeout register). Note: If the USART does not support the Receiver timeout feature, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$ff000000 constant SEC_USART1_USART_CR2_ADD                         \ Address of the USART node These bits give the address of the USART node in Mute mode or a character code to be recognized in low-power or Run mode: In Mute mode: they are used in multiprocessor communication to wakeup from Mute mode with 4-bit/7-bit address mark detection. The MSB of the character sent by the transmitter should be equal to 1. In 4-bit address mark detection, only ADD[3:0] bits are used. In low-power mode: they are used for wake up from low-power mode on character match. When a character, received during low-power mode, corresponds to the character programmed through ADD[7:0] bitfield, the CMF flag is set and wakes up the device from low-power mode if the corresponding interrupt is enabled by setting CMIE bit. In Run mode with Mute mode inactive (for example, end-of-block detection in ModBus protocol): the whole received character (8 bits) is compared to ADD[7:0] value and CMF flag is set on match. An interrupt is generated if the CMIE bit is set. These bits can only be written when the reception is disabled (RE = 0) or when the USART is disabled (UE = 0).


\
\ @brief USART control register 3
\ Address offset: 0x08
\ Reset value: 0x00000000
\

$00000001 constant SEC_USART1_USART_CR3_EIE                         \ Error interrupt enable Error Interrupt Enable Bit is required to enable interrupt generation in case of a framing error, overrun error noise flag or SPI slave underrun error (FE=1 or ORE=1 or NE=1or UDR = 1 in the USART_ISR register).
$00000002 constant SEC_USART1_USART_CR3_IREN                        \ IrDA mode enable This bit is set and cleared by software. This bit can only be written when the USART is disabled (UE=0). Note: If IrDA mode is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000004 constant SEC_USART1_USART_CR3_IRLP                        \ IrDA low-power This bit is used for selecting between normal and low-power IrDA modes This bit can only be written when the USART is disabled (UE=0). Note: If IrDA mode is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000008 constant SEC_USART1_USART_CR3_HDSEL                       \ Half-duplex selection Selection of Single-wire Half-duplex mode This bit can only be written when the USART is disabled (UE=0).
$00000010 constant SEC_USART1_USART_CR3_NACK                        \ Smartcard NACK enable This bitfield can only be written when the USART is disabled (UE=0). Note: If the USART does not support Smartcard mode, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000020 constant SEC_USART1_USART_CR3_SCEN                        \ Smartcard mode enable This bit is used for enabling Smartcard mode. This bitfield can only be written when the USART is disabled (UE=0). Note: If the USART does not support Smartcard mode, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000040 constant SEC_USART1_USART_CR3_DMAR                        \ DMA enable receiver This bit is set/reset by software
$00000080 constant SEC_USART1_USART_CR3_DMAT                        \ DMA enable transmitter This bit is set/reset by software
$00000100 constant SEC_USART1_USART_CR3_RTSE                        \ RTS enable This bit can only be written when the USART is disabled (UE=0). Note: If the hardware flow control feature is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000200 constant SEC_USART1_USART_CR3_CTSE                        \ CTS enable This bit can only be written when the USART is disabled (UE=0) Note: If the hardware flow control feature is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000400 constant SEC_USART1_USART_CR3_CTSIE                       \ CTS interrupt enable Note: If the hardware flow control feature is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000800 constant SEC_USART1_USART_CR3_ONEBIT                      \ One sample bit method enable This bit enables the user to select the sample method. When the one sample bit method is selected the noise detection flag (NE) is disabled. This bit can only be written when the USART is disabled (UE=0).
$00001000 constant SEC_USART1_USART_CR3_OVRDIS                      \ Overrun Disable This bit is used to disable the receive overrun detection. the ORE flag is not set and the new received data overwrites the previous content of the USART_RDR register. When FIFO mode is enabled, the RXFIFO is bypassed and data are written directly in USART_RDR register. Even when FIFO management is enabled, the RXNE flag is to be used. This bit can only be written when the USART is disabled (UE=0). Note: This control bit enables checking the communication flow w/o reading the data
$00002000 constant SEC_USART1_USART_CR3_DDRE                        \ DMA Disable on Reception Error This bit can only be written when the USART is disabled (UE=0). Note: The reception errors are: parity error, framing error or noise error.
$00004000 constant SEC_USART1_USART_CR3_DEM                         \ Driver enable mode This bit enables the user to activate the external transceiver control, through the DE signal. This bit can only be written when the USART is disabled (UE=0). Note: If the Driver Enable feature is not supported, this bit is reserved and must be kept at reset value. Section 78.4: USART implementation on page 4565.
$00008000 constant SEC_USART1_USART_CR3_DEP                         \ Driver enable polarity selection This bit can only be written when the USART is disabled (UE=0). Note: If the Driver Enable feature is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$000e0000 constant SEC_USART1_USART_CR3_SCARCNT                     \ Smartcard auto-retry count This bitfield specifies the number of retries for transmission and reception in Smartcard mode. In Transmission mode, it specifies the number of automatic retransmission retries, before generating a transmission error (FE bit set). In Reception mode, it specifies the number or erroneous reception trials, before generating a reception error (RXNE/RXFNE and PE bits set). This bitfield must be programmed only when the USART is disabled (UE=0). When the USART is enabled (UE=1), this bitfield may only be written to 0x0, in order to stop retransmission. 0x1 to 0x7: number of automatic retransmission attempts (before signaling error) Note: If Smartcard mode is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00800000 constant SEC_USART1_USART_CR3_TXFTIE                      \ TXFIFO threshold interrupt enable This bit is set and cleared by software.
$01000000 constant SEC_USART1_USART_CR3_TCBGTIE                     \ Transmission Complete before guard time, interrupt enable This bit is set and cleared by software. Note: If the USART does not support the Smartcard mode, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$0e000000 constant SEC_USART1_USART_CR3_RXFTCFG                     \ Receive FIFO threshold configuration Remaining combinations: Reserved
$10000000 constant SEC_USART1_USART_CR3_RXFTIE                      \ RXFIFO threshold interrupt enable This bit is set and cleared by software.
$e0000000 constant SEC_USART1_USART_CR3_TXFTCFG                     \ TXFIFO threshold configuration Remaining combinations: Reserved


\
\ @brief USART baud rate register
\ Address offset: 0x0C
\ Reset value: 0x00000000
\

$0000ffff constant SEC_USART1_USART_BRR_BRR                         \ USART baud rate BRR[15:4] BRR[15:4] correspond to USARTDIV[15:4] BRR[3:0] When OVER8 = 0, BRR[3:0] = USARTDIV[3:0]. When OVER8 = 1: BRR[2:0] = USARTDIV[3:0] shifted 1 bit to the right. BRR[3] must be kept cleared.


\
\ @brief USART guard time and prescaler register
\ Address offset: 0x10
\ Reset value: 0x00000000
\

$000000ff constant SEC_USART1_USART_GTPR_PSC                        \ Prescaler value PSC[7:0] = IrDA Normal and Low-power baud rate This bitfield is used for programming the prescaler for dividing the USART source clock to achieve the low-power frequency: The source clock is divided by the value given in the register (8 significant bits): ... PSC[4:0]: Prescaler value This bitfield is used for programming the prescaler for dividing the USART source clock to provide the Smartcard clock. The value given in the register (5 significant bits) is multiplied by 2 to give the division factor of the source clock frequency: ... This bitfield can only be written when the USART is disabled (UE=0). Note: Bits [7:5] must be kept cleared if Smartcard mode is used. Note: This bitfield is reserved and forced by hardware to 0 when the Smartcard and IrDA modes are not supported. Refer to Section 78.4: USART implementation on page 4565.
$0000ff00 constant SEC_USART1_USART_GTPR_GT                         \ Guard time value This bitfield is used to program the Guard time value in terms of number of baud clock periods. This is used in Smartcard mode. The Transmission Complete flag is set after this guard time value. This bitfield can only be written when the USART is disabled (UE=0). Note: If Smartcard mode is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.


\
\ @brief USART receiver timeout register
\ Address offset: 0x14
\ Reset value: 0x00000000
\

$00ffffff constant SEC_USART1_USART_RTOR_RTO                        \ Receiver timeout value This bitfield gives the Receiver timeout value in terms of number of bit duration. In Standard mode, the RTOF flag is set if, after the last received character, no new start bit is detected for more than the RTO value. In Smartcard mode, this value is used to implement the CWT and BWT. See Smartcard chapter for more details. In the standard, the CWT/BWT measurement is done starting from the start bit of the last received character. Note: This value must only be programmed once per received character.
$ff000000 constant SEC_USART1_USART_RTOR_BLEN                       \ Block Length This bitfield gives the Block length in Smartcard T=1 Reception. Its value equals the number of information characters + the length of the Epilogue Field (1-LEC/2-CRC) - 1. Examples: BLEN = 0 - 0 information characters + LEC BLEN = 1 - 0 information characters + CRC BLEN = 255 - 254 information characters + CRC (total 256 characters)) In Smartcard mode, the Block length counter is reset when TXE=0 (TXFE = 0 in case FIFO mode is enabled). This bitfield can be used also in other modes. In this case, the Block length counter is reset when RE=0 (receiver disabled) and/or when the EOBCF bit is written to 1. Note: This value can be programmed after the start of the block reception (using the data from the LEN character in the Prologue Field). It must be programmed only once per received block.


\
\ @brief USART request register
\ Address offset: 0x18
\ Reset value: 0x00000000
\

$00000001 constant SEC_USART1_USART_RQR_ABRRQ                       \ Auto baud rate request Writing 1 to this bit resets the ABRF and ABRE flags in the USART_ISR and requests an automatic baud rate measurement on the next received data frame. Note: If the USART does not support the auto baud rate feature, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000002 constant SEC_USART1_USART_RQR_SBKRQ                       \ Send break request Writing 1 to this bit sets the SBKF flag and request to send a BREAK on the line, as soon as the transmit machine is available. Note: When the application needs to send the break character following all previously inserted data, including the ones not yet transmitted, the software should wait for the TXE flag assertion before setting the SBKRQ bit.
$00000004 constant SEC_USART1_USART_RQR_MMRQ                        \ Mute mode request Writing 1 to this bit puts the USART in Mute mode and resets the RWU flag.
$00000008 constant SEC_USART1_USART_RQR_RXFRQ                       \ Receive data flush request Writing 1 to this bit empties the entire receive FIFO i.e. clears the bit RXFNE. This enables to discard the received data without reading them, and avoid an overrun condition.
$00000010 constant SEC_USART1_USART_RQR_TXFRQ                       \ Transmit data flush request When FIFO mode is disabled, writing 1 to this bit sets the TXE flag. This enables to discard the transmit data. This bit must be used only in Smartcard mode, when data have not been sent due to errors (NACK) and the FE flag is active in the USART_ISR register. If the USART does not support Smartcard mode, this bit is reserved and must be kept at reset value. When FIFO is enabled, TXFRQ bit is set to flush the whole FIFO. This sets the TXFE flag (Transmit FIFO empty, bit 23 in the USART_ISR register). Flushing the Transmit FIFO is supported in both UART and Smartcard modes. Note: In FIFO mode, the TXFNF flag is reset during the flush request until TxFIFO is empty in order to ensure that no data are written in the data register.


\
\ @brief USART interrupt and status register [alternate]
\ Address offset: 0x1C
\ Reset value: 0x000000C0
\

$00000001 constant SEC_USART1_USART_ISR_PE                          \ Parity error This bit is set by hardware when a parity error occurs in Reception mode. It is cleared by software, writing 1 to the PECF in the USART_ICR register. An interrupt is generated if PEIE = 1 in the USART_CR1 register. Note: This error is associated with the character in the USART_RDR.
$00000002 constant SEC_USART1_USART_ISR_FE                          \ Framing error This bit is set by hardware when a de-synchronization, excessive noise or a break character is detected. It is cleared by software, writing 1 to the FECF bit in the USART_ICR register. When transmitting data in Smartcard mode, this bit is set when the maximum number of transmit attempts is reached without success (the card NACKs the data frame). An interrupt is generated if EIE = 1 in the USART_CR1 register. Note: This error is associated with the character in the USART_RDR.
$00000004 constant SEC_USART1_USART_ISR_NE                          \ Noise detection flag This bit is set by hardware when noise is detected on a received frame. It is cleared by software, writing 1 to the NFCF bit in the USART_ICR register. Note: This bit does not generate an interrupt as it appears at the same time as the RXFNE bit which itself generates an interrupt. An interrupt is generated when the NE flag is set during multi buffer communication if the EIE bit is set. Note: When the line is noise-free, the NE flag can be disabled by programming the ONEBIT bit to 1 to increase the USART tolerance to deviations (Refer to Section 78.5.9: Tolerance of the USART receiver to clock deviation on page 4584). Note: This error is associated with the character in the USART_RDR.
$00000008 constant SEC_USART1_USART_ISR_ORE                         \ Overrun error This bit is set by hardware when the data currently being received in the shift register is ready to be transferred into the USART_RDR register while RXFF = 1. It is cleared by a software, writing 1 to the ORECF, in the USART_ICR register. An interrupt is generated if RXFNEIE=1 or EIE = 1 in the USART_CR1 register. Note: When this bit is set, the USART_RDR register content is not lost but the shift register is overwritten. An interrupt is generated if the ORE flag is set during multi buffer communication if the EIE bit is set. Note: This bit is permanently forced to 0 (no overrun detection) when the bit OVRDIS is set in the USART_CR3 register.
$00000010 constant SEC_USART1_USART_ISR_IDLE                        \ Idle line detected This bit is set by hardware when an Idle Line is detected. An interrupt is generated if IDLEIE=1 in the USART_CR1 register. It is cleared by software, writing 1 to the IDLECF in the USART_ICR register. Note: The IDLE bit is not set again until the RXFNE bit has been set (i.e. a new idle line occurs). Note: If Mute mode is enabled (MME=1), IDLE is set if the USART is not mute (RWU=0), whatever the Mute mode selected by the WAKE bit. If RWU=1, IDLE is not set.
$00000020 constant SEC_USART1_USART_ISR_RXFNE                       \ RXFIFO not empty RXFNE bit is set by hardware when the RXFIFO is not empty, meaning that data can be read from the USART_RDR register. Every read operation from the USART_RDR frees a location in the RXFIFO. RXFNE is cleared when the RXFIFO is empty. The RXFNE flag can also be cleared by writing 1 to the RXFRQ in the USART_RQR register. An interrupt is generated if RXFNEIE=1 in the USART_CR1 register.
$00000040 constant SEC_USART1_USART_ISR_TC                          \ Transmission complete This bit indicates that the last data written in the USART_TDR has been transmitted out of the shift register. The TC flag behaves as follows: When TDN = 0, the TC flag is set when the transmission of a frame containing data is complete and when TXE/TXFE is set. When TDN is equal to the number of data in the TXFIFO, the TC flag is set when TXFIFO is empty and TDN is reached. When TDN is greater than the number of data in the TXFIFO, TC remains cleared until the TXFIFO is filled again to reach the programmed number of data to be transferred. When TDN is less than the number of data in the TXFIFO, TC is set when TDN is reached even if the TXFIFO is not empty. An interrupt is generated if TCIE=1 in the USART_CR1 register. TC bit is cleared by software by writing 1 to the TCCF in the USART_ICR register or by writing to the USART_TDR register.
$00000080 constant SEC_USART1_USART_ISR_TXFNF                       \ TXFIFO not full TXFNF is set by hardware when TXFIFO is not full meaning that data can be written in the USART_TDR. Every write operation to the USART_TDR places the data in the TXFIFO. This flag remains set until the TXFIFO is full. When the TXFIFO is full, this flag is cleared indicating that data can not be written into the USART_TDR. An interrupt is generated if the TXFNFIE bit =1 in the USART_CR1 register. Note: The TXFNF is kept reset during the flush request until TXFIFO is empty. After sending the flush request (by setting TXFRQ bit), the flag TXFNF should be checked prior to writing in TXFIFO (TXFNF and TXFE is set at the same time). Note: This bit is used during single buffer transmission.
$00000100 constant SEC_USART1_USART_ISR_LBDF                        \ LIN break detection flag This bit is set by hardware when the LIN break is detected. It is cleared by software, by writing 1 to the LBDCF in the USART_ICR. An interrupt is generated if LBDIE = 1 in the USART_CR2 register. Note: If the USART does not support LIN mode, this bit is reserved and kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000200 constant SEC_USART1_USART_ISR_CTSIF                       \ CTS interrupt flag This bit is set by hardware when the CTS input toggles, if the CTSE bit is set. It is cleared by software, by writing 1 to the CTSCF bit in the USART_ICR register. An interrupt is generated if CTSIE=1 in the USART_CR3 register. Note: If the hardware flow control feature is not supported, this bit is reserved and kept at reset value.
$00000400 constant SEC_USART1_USART_ISR_CTS                         \ CTS flag This bit is set/reset by hardware. It is an inverted copy of the status of the CTS input pin. Note: If the hardware flow control feature is not supported, this bit is reserved and kept at reset value.
$00000800 constant SEC_USART1_USART_ISR_RTOF                        \ Receiver timeout This bit is set by hardware when the timeout value, programmed in the RTOR register has lapsed, without any communication. It is cleared by software, writing 1 to the RTOCF bit in the USART_ICR register. An interrupt is generated if RTOIE=1 in the USART_CR2 register. In Smartcard mode, the timeout corresponds to the CWT or BWT timings. Note: If a time equal to the value programmed in RTOR register separates 2 characters, RTOF is not set. If this time exceeds this value + 2 sample times (2/16 or 2/8, depending on the oversampling method), RTOF flag is set. Note: The counter counts even if RE = 0 but RTOF is set only when RE = 1. If the timeout has already elapsed when RE is set, then RTOF is set. Note: If the USART does not support the Receiver timeout feature, this bit is reserved and kept at reset value.
$00001000 constant SEC_USART1_USART_ISR_EOBF                        \ End of block flag This bit is set by hardware when a complete block has been received (for example T=1 Smartcard mode). The detection is done when the number of received bytes (from the start of the block, including the prologue) is equal or greater than BLEN + 4. An interrupt is generated if EOBIE = 1 in the USART_CR1 register. It is cleared by software, writing 1 to EOBCF in the USART_ICR register. Note: If Smartcard mode is not supported, this bit is reserved and kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00002000 constant SEC_USART1_USART_ISR_UDR                         \ SPI slave underrun error flag In Slave transmission mode, this flag is set when the first clock pulse for data transmission appears while the software has not yet loaded any value into USART_TDR. This flag is reset by setting UDRCF bit in the USART_ICR register. Note: If the USART does not support the SPI slave mode, this bit is reserved and kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00004000 constant SEC_USART1_USART_ISR_ABRE                        \ Auto baud rate error This bit is set by hardware if the baud rate measurement failed (baud rate out of range or character comparison failed) It is cleared by software, by writing 1 to the ABRRQ bit in the USART_RQR register. Note: If the USART does not support the auto baud rate feature, this bit is reserved and kept at reset value.
$00008000 constant SEC_USART1_USART_ISR_ABRF                        \ Auto baud rate flag This bit is set by hardware when the automatic baud rate has been set (RXFNE is also set, generating an interrupt if RXFNEIE = 1) or when the auto baud rate operation was completed without success (ABRE=1) (ABRE, RXFNE and FE are also set in this case) It is cleared by software, in order to request a new auto baud rate detection, by writing 1 to the ABRRQ in the USART_RQR register. Note: If the USART does not support the auto baud rate feature, this bit is reserved and kept at reset value.
$00010000 constant SEC_USART1_USART_ISR_BUSY                        \ Busy flag This bit is set and reset by hardware. It is active when a communication is ongoing on the RX line (successful start bit detected). It is reset at the end of the reception (successful or not).
$00020000 constant SEC_USART1_USART_ISR_CMF                         \ Character match flag This bit is set by hardware, when a the character defined by ADD[7:0] is received. It is cleared by software, writing 1 to the CMCF in the USART_ICR register. An interrupt is generated if CMIE=1in the USART_CR1 register.
$00040000 constant SEC_USART1_USART_ISR_SBKF                        \ Send break flag This bit indicates that a send break character was requested. It is set by software, by writing 1 to the SBKRQ bit in the USART_CR3 register. It is automatically reset by hardware during the stop bit of break transmission.
$00080000 constant SEC_USART1_USART_ISR_RWU                         \ Receiver wakeup from Mute mode This bit indicates if the USART is in Mute mode. It is cleared/set by hardware when a wakeup/mute sequence is recognized. The Mute mode control sequence (address or IDLE) is selected by the WAKE bit in the USART_CR1 register. When wakeup on IDLE mode is selected, this bit can only be set by software, writing 1 to the MMRQ bit in the USART_RQR register. Note: If the USART does not support the wakeup from Stop feature, this bit is reserved and kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00200000 constant SEC_USART1_USART_ISR_TEACK                       \ Transmit enable acknowledge flag This bit is set/reset by hardware, when the Transmit Enable value is taken into account by the USART. It can be used when an idle frame request is generated by writing TE=0, followed by TE=1 in the USART_CR1 register, in order to respect the TE=0 minimum period.
$00400000 constant SEC_USART1_USART_ISR_REACK                       \ Receive enable acknowledge flag This bit is set/reset by hardware, when the Receive Enable value is taken into account by the USART. It can be used to verify that the USART is ready for reception before entering low-power mode. Note: If the USART does not support the wakeup from Stop feature, this bit is reserved and kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00800000 constant SEC_USART1_USART_ISR_TXFE                        \ TXFIFO Empty This bit is set by hardware when TXFIFO is Empty. When the TXFIFO contains at least one data, this flag is cleared. The TXFE flag can also be set by writing 1 to the bit TXFRQ (bit 4) in the USART_RQR register. An interrupt is generated if the TXFEIE bit =1 (bit 30) in the USART_CR1 register.
$01000000 constant SEC_USART1_USART_ISR_RXFF                        \ RXFIFO Full This bit is set by hardware when the number of received data corresponds to RXFIFO size + 1 (RXFIFO full + 1 data in the USART_RDR register. An interrupt is generated if the RXFFIE bit =1 in the USART_CR1 register.
$02000000 constant SEC_USART1_USART_ISR_TCBGT                       \ Transmission complete before guard time flag This bit is set when the last data written in the USART_TDR has been transmitted correctly out of the shift register. It is set by hardware in Smartcard mode, if the transmission of a frame containing data is complete and if the smartcard did not send back any NACK. An interrupt is generated if TCBGTIE=1 in the USART_CR3 register. This bit is cleared by software, by writing 1 to the TCBGTCF in the USART_ICR register or by a write to the USART_TDR register. Note: If the USART does not support the Smartcard mode, this bit is reserved and kept at reset value. If the USART supports the Smartcard mode and the Smartcard mode is enabled, the TCBGT reset value is 1. Refer to Section 78.4: USART implementation on page 4565.
$04000000 constant SEC_USART1_USART_ISR_RXFT                        \ RXFIFO threshold flag This bit is set by hardware when the threshold programmed in RXFTCFG in USART_CR3 register is reached. This means that there are (RXFTCFG - 1) data in the Receive FIFO and one data in the USART_RDR register. An interrupt is generated if the RXFTIE bit =1 (bit 27) in the USART_CR3 register. Note: When the RXFTCFG threshold is configured to 101, RXFT flag is set if 16 data are available i.e. 15 data in the RXFIFO and 1 data in the USART_RDR. Consequently, the 17th received data does not cause an overrun error. The overrun error occurs after receiving the 18th data.
$08000000 constant SEC_USART1_USART_ISR_TXFT                        \ TXFIFO threshold flag This bit is set by hardware when the TXFIFO reaches the threshold programmed in TXFTCFG of USART_CR3 register i.e. the TXFIFO contains TXFTCFG empty locations. An interrupt is generated if the TXFTIE bit =1 (bit 31) in the USART_CR3 register.


\
\ @brief USART interrupt and status register [alternate]
\ Address offset: 0x1C
\ Reset value: 0x000000C0
\

$00000001 constant SEC_USART1_USART_ISR_ALTERNATE1_PE               \ Parity error This bit is set by hardware when a parity error occurs in Reception mode. It is cleared by software, writing 1 to the PECF in the USART_ICR register. An interrupt is generated if PEIE = 1 in the USART_CR1 register. Note: This error is associated with the character in the USART_RDR.
$00000002 constant SEC_USART1_USART_ISR_ALTERNATE1_FE               \ Framing error This bit is set by hardware when a de-synchronization, excessive noise or a break character is detected. It is cleared by software, writing 1 to the FECF bit in the USART_ICR register. When transmitting data in Smartcard mode, this bit is set when the maximum number of transmit attempts is reached without success (the card NACKs the data frame). An interrupt is generated if EIE = 1 in the USART_CR1 register. Note: This error is associated with the character in the USART_RDR.
$00000004 constant SEC_USART1_USART_ISR_ALTERNATE1_NE               \ Noise detection flag This bit is set by hardware when noise is detected on a received frame. It is cleared by software, writing 1 to the NFCF bit in the USART_ICR register. Note: This bit does not generate an interrupt as it appears at the same time as the RXNE bit which itself generates an interrupt. An interrupt is generated when the NE flag is set during multi buffer communication if the EIE bit is set. Note: When the line is noise-free, the NE flag can be disabled by programming the ONEBIT bit to 1 to increase the USART tolerance to deviations (Refer to Section 78.5.9: Tolerance of the USART receiver to clock deviation on page 4584). Note: This error is associated with the character in the USART_RDR.
$00000008 constant SEC_USART1_USART_ISR_ALTERNATE1_ORE              \ Overrun error This bit is set by hardware when the data currently being received in the shift register is ready to be transferred into the USART_RDR register while RXNE=1. It is cleared by a software, writing 1 to the ORECF, in the USART_ICR register. An interrupt is generated if RXNEIE=1 or EIE = 1 in the USART_CR1 register. Note: When this bit is set, the USART_RDR register content is not lost but the shift register is overwritten. An interrupt is generated if the ORE flag is set during multi buffer communication if the EIE bit is set. Note: This bit is permanently forced to 0 (no overrun detection) when the bit OVRDIS is set in the USART_CR3 register.
$00000010 constant SEC_USART1_USART_ISR_ALTERNATE1_IDLE             \ Idle line detected This bit is set by hardware when an Idle Line is detected. An interrupt is generated if IDLEIE=1 in the USART_CR1 register. It is cleared by software, writing 1 to the IDLECF in the USART_ICR register. Note: The IDLE bit is not set again until the RXNE bit has been set (i.e. a new idle line occurs). Note: If Mute mode is enabled (MME=1), IDLE is set if the USART is not mute (RWU=0), whatever the Mute mode selected by the WAKE bit. If RWU=1, IDLE is not set.
$00000020 constant SEC_USART1_USART_ISR_ALTERNATE1_RXNE             \ Read data register not empty RXNE bit is set by hardware when the content of the USART_RDR shift register has been transferred to the USART_RDR register. It is cleared by reading from the USART_RDR register. The RXNE flag can also be cleared by writing 1 to the RXFRQ in the USART_RQR register. An interrupt is generated if RXNEIE=1 in the USART_CR1 register.
$00000040 constant SEC_USART1_USART_ISR_ALTERNATE1_TC               \ Transmission complete This bit indicates that the last data written in the USART_TDR has been transmitted out of the shift register. The TC flag is set when the transmission of a frame containing data is complete and when TXE is set. An interrupt is generated if TCIE=1 in the USART_CR1 register. TC bit is cleared by software by writing 1 to the TCCF in the USART_ICR register or by writing to the USART_TDR register.
$00000080 constant SEC_USART1_USART_ISR_ALTERNATE1_TXE              \ Transmit data register empty TXE is set by hardware when the content of the USART_TDR register has been transferred into the shift register. It is cleared by writing to the USART_TDR register. The TXE flag can also be set by writing 1 to the TXFRQ in the USART_RQR register, in order to discard the data (only in Smartcard T=0 mode, in case of transmission failure). An interrupt is generated if the TXEIE bit =1 in the USART_CR1 register.
$00000100 constant SEC_USART1_USART_ISR_ALTERNATE1_LBDF             \ LIN break detection flag This bit is set by hardware when the LIN break is detected. It is cleared by software, by writing 1 to the LBDCF in the USART_ICR. An interrupt is generated if LBDIE = 1 in the USART_CR2 register. Note: If the USART does not support LIN mode, this bit is reserved and kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000200 constant SEC_USART1_USART_ISR_ALTERNATE1_CTSIF            \ CTS interrupt flag This bit is set by hardware when the CTS input toggles, if the CTSE bit is set. It is cleared by software, by writing 1 to the CTSCF bit in the USART_ICR register. An interrupt is generated if CTSIE=1 in the USART_CR3 register. Note: If the hardware flow control feature is not supported, this bit is reserved and kept at reset value.
$00000400 constant SEC_USART1_USART_ISR_ALTERNATE1_CTS              \ CTS flag This bit is set/reset by hardware. It is an inverted copy of the status of the CTS input pin. Note: If the hardware flow control feature is not supported, this bit is reserved and kept at reset value.
$00000800 constant SEC_USART1_USART_ISR_ALTERNATE1_RTOF             \ Receiver timeout This bit is set by hardware when the timeout value, programmed in the RTOR register has lapsed, without any communication. It is cleared by software, writing 1 to the RTOCF bit in the USART_ICR register. An interrupt is generated if RTOIE=1 in the USART_CR2 register. In Smartcard mode, the timeout corresponds to the CWT or BWT timings. Note: If a time equal to the value programmed in RTOR register separates 2 characters, RTOF is not set. If this time exceeds this value + 2 sample times (2/16 or 2/8, depending on the oversampling method), RTOF flag is set. Note: The counter counts even if RE = 0 but RTOF is set only when RE = 1. If the timeout has already elapsed when RE is set, then RTOF is set. Note: If the USART does not support the Receiver timeout feature, this bit is reserved and kept at reset value.
$00001000 constant SEC_USART1_USART_ISR_ALTERNATE1_EOBF             \ End of block flag This bit is set by hardware when a complete block has been received (for example T=1 Smartcard mode). The detection is done when the number of received bytes (from the start of the block, including the prologue) is equal or greater than BLEN + 4. An interrupt is generated if EOBIE = 1 in the USART_CR1 register. It is cleared by software, writing 1 to EOBCF in the USART_ICR register. Note: If Smartcard mode is not supported, this bit is reserved and kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00002000 constant SEC_USART1_USART_ISR_ALTERNATE1_UDR              \ SPI slave underrun error flag In Slave transmission mode, this flag is set when the first clock pulse for data transmission appears while the software has not yet loaded any value into USART_TDR. This flag is reset by setting UDRCF bit in the USART_ICR register. Note: If the USART does not support the SPI slave mode, this bit is reserved and kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00004000 constant SEC_USART1_USART_ISR_ALTERNATE1_ABRE             \ Auto baud rate error This bit is set by hardware if the baud rate measurement failed (baud rate out of range or character comparison failed) It is cleared by software, by writing 1 to the ABRRQ bit in the USART_RQR register. Note: If the USART does not support the auto baud rate feature, this bit is reserved and kept at reset value.
$00008000 constant SEC_USART1_USART_ISR_ALTERNATE1_ABRF             \ Auto baud rate flag This bit is set by hardware when the automatic baud rate has been set (RXNE is also set, generating an interrupt if RXNEIE = 1) or when the auto baud rate operation was completed without success (ABRE=1) (ABRE, RXNE and FE are also set in this case) It is cleared by software, in order to request a new auto baud rate detection, by writing 1 to the ABRRQ in the USART_RQR register. Note: If the USART does not support the auto baud rate feature, this bit is reserved and kept at reset value.
$00010000 constant SEC_USART1_USART_ISR_ALTERNATE1_BUSY             \ Busy flag This bit is set and reset by hardware. It is active when a communication is ongoing on the RX line (successful start bit detected). It is reset at the end of the reception (successful or not).
$00020000 constant SEC_USART1_USART_ISR_ALTERNATE1_CMF              \ Character match flag This bit is set by hardware, when a the character defined by ADD[7:0] is received. It is cleared by software, writing 1 to the CMCF in the USART_ICR register. An interrupt is generated if CMIE=1in the USART_CR1 register.
$00040000 constant SEC_USART1_USART_ISR_ALTERNATE1_SBKF             \ Send break flag This bit indicates that a send break character was requested. It is set by software, by writing 1 to the SBKRQ bit in the USART_CR3 register. It is automatically reset by hardware during the stop bit of break transmission.
$00080000 constant SEC_USART1_USART_ISR_ALTERNATE1_RWU              \ Receiver wakeup from Mute mode This bit indicates if the USART is in Mute mode. It is cleared/set by hardware when a wakeup/mute sequence is recognized. The Mute mode control sequence (address or IDLE) is selected by the WAKE bit in the USART_CR1 register. When wakeup on IDLE mode is selected, this bit can only be set by software, writing 1 to the MMRQ bit in the USART_RQR register. Note: If the USART does not support the wakeup from Stop feature, this bit is reserved and kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00200000 constant SEC_USART1_USART_ISR_ALTERNATE1_TEACK            \ Transmit enable acknowledge flag This bit is set/reset by hardware, when the Transmit Enable value is taken into account by the USART. It can be used when an idle frame request is generated by writing TE=0, followed by TE=1 in the USART_CR1 register, in order to respect the TE=0 minimum period.
$00400000 constant SEC_USART1_USART_ISR_ALTERNATE1_REACK            \ Receive enable acknowledge flag This bit is set/reset by hardware, when the Receive Enable value is taken into account by the USART. It can be used to verify that the USART is ready for reception before entering low-power mode. Note: If the USART does not support the wakeup from Stop feature, this bit is reserved and kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$02000000 constant SEC_USART1_USART_ISR_ALTERNATE1_TCBGT            \ Transmission complete before guard time flag This bit is set when the last data written in the USART_TDR has been transmitted correctly out of the shift register. It is set by hardware in Smartcard mode, if the transmission of a frame containing data is complete and if the smartcard did not send back any NACK. An interrupt is generated if TCBGTIE=1 in the USART_CR3 register. This bit is cleared by software, by writing 1 to the TCBGTCF in the USART_ICR register or by a write to the USART_TDR register. Note: If the USART does not support the Smartcard mode, this bit is reserved and kept at reset value. If the USART supports the Smartcard mode and the Smartcard mode is enabled, the TCBGT reset value is 1. Refer to Section 78.4: USART implementation on page 4565.


\
\ @brief USART interrupt flag clear register
\ Address offset: 0x20
\ Reset value: 0x00000000
\

$00000001 constant SEC_USART1_USART_ICR_PECF                        \ Parity error clear flag Writing 1 to this bit clears the PE flag in the USART_ISR register.
$00000002 constant SEC_USART1_USART_ICR_FECF                        \ Framing error clear flag Writing 1 to this bit clears the FE flag in the USART_ISR register.
$00000004 constant SEC_USART1_USART_ICR_NECF                        \ Noise detected clear flag Writing 1 to this bit clears the NE flag in the USART_ISR register.
$00000008 constant SEC_USART1_USART_ICR_ORECF                       \ Overrun error clear flag Writing 1 to this bit clears the ORE flag in the USART_ISR register.
$00000010 constant SEC_USART1_USART_ICR_IDLECF                      \ Idle line detected clear flag Writing 1 to this bit clears the IDLE flag in the USART_ISR register.
$00000020 constant SEC_USART1_USART_ICR_TXFECF                      \ TXFIFO empty clear flag Writing 1 to this bit clears the TXFE flag in the USART_ISR register.
$00000040 constant SEC_USART1_USART_ICR_TCCF                        \ Transmission complete clear flag Writing 1 to this bit clears the TC flag in the USART_ISR register.
$00000080 constant SEC_USART1_USART_ICR_TCBGTCF                     \ Transmission complete before Guard time clear flag Writing 1 to this bit clears the TCBGT flag in the USART_ISR register.
$00000100 constant SEC_USART1_USART_ICR_LBDCF                       \ LIN break detection clear flag Writing 1 to this bit clears the LBDF flag in the USART_ISR register. Note: If LIN mode is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000200 constant SEC_USART1_USART_ICR_CTSCF                       \ CTS clear flag Writing 1 to this bit clears the CTSIF flag in the USART_ISR register. Note: If the hardware flow control feature is not supported, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00000800 constant SEC_USART1_USART_ICR_RTOCF                       \ Receiver timeout clear flag Writing 1 to this bit clears the RTOF flag in the USART_ISR register. Note: If the USART does not support the Receiver timeout feature, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00001000 constant SEC_USART1_USART_ICR_EOBCF                       \ End of block clear flag Writing 1 to this bit clears the EOBF flag in the USART_ISR register. Note: If the USART does not support Smartcard mode, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565.
$00002000 constant SEC_USART1_USART_ICR_UDRCF                       \ SPI slave underrun clear flag Writing 1 to this bit clears the UDRF flag in the USART_ISR register. Note: If the USART does not support SPI slave mode, this bit is reserved and must be kept at reset value. Refer to Section 78.4: USART implementation on page 4565
$00020000 constant SEC_USART1_USART_ICR_CMCF                        \ Character match clear flag Writing 1 to this bit clears the CMF flag in the USART_ISR register.


\
\ @brief USART receive data register
\ Address offset: 0x24
\ Reset value: 0x00000000
\

$000001ff constant SEC_USART1_USART_RDR_RDR                         \ Receive data value Contains the received data character. The RDR register provides the parallel interface between the input shift register and the internal bus (see Figure 927). When receiving with the parity enabled, the value read in the MSB bit is the received parity bit.


\
\ @brief USART transmit data register
\ Address offset: 0x28
\ Reset value: 0x00000000
\

$000001ff constant SEC_USART1_USART_TDR_TDR                         \ Transmit data value Contains the data character to be transmitted. The USART_TDR register provides the parallel interface between the internal bus and the output shift register (see Figure 927). When transmitting with the parity enabled (PCE bit set to 1 in the USART_CR1 register), the value written in the MSB (bit 7 or bit 8 depending on the data length) has no effect because it is replaced by the parity. Note: This register must be written only when TXE/TXFNF=1.


\
\ @brief USART prescaler register
\ Address offset: 0x2C
\ Reset value: 0x00000000
\

$0000000f constant SEC_USART1_USART_PRESC_PRESCALER                 \ Clock prescaler The USART input clock can be divided by a prescaler factor: Remaining combinations: Reserved Note: When PRESCALER is programmed with a value different of the allowed ones, programmed prescaler value is equal to 1011 i.e. input clock divided by 256.


\
\ @brief USART Autonomous mode control register
\ Address offset: 0x30
\ Reset value: 0x80000000
\

$0000ffff constant SEC_USART1_USART_AUTOCR_TDN                      \ TDN transmission data number This bitfield enables the programming of the number of data to be transmitted. It can be written only when UE is cleared in USART_CR1.
$00010000 constant SEC_USART1_USART_AUTOCR_TRIGPOL                  \ Trigger polarity bit This bitfield can be written only when the UE bit is cleared in USART_CR1 register.
$00020000 constant SEC_USART1_USART_AUTOCR_TRIGEN                   \ Trigger enable bit Note: This bitfield can be written only when the UE bit of USART_CR1 register is cleared. Note: When a trigger is detected, TE is set to 1 in USART_CR1 and the data transfer is launched.
$00040000 constant SEC_USART1_USART_AUTOCR_IDLEDIS                  \ Idle frame transmission disable bit after enabling the transmitter Note: This bitfield can be written only when the UE bit of USART_CR1 register is cleared.
$00780000 constant SEC_USART1_USART_AUTOCR_TRIGSEL                  \ Trigger selection bits Refer to Description of USART interconnections. This bitfield can be written only when the UE bit is cleared in USART_CR1 register. ... Note: This bitfield can be written only when the UE bit of USART_CR1 register is cleared.


\
\ @brief USART register block
\
$50013800 constant SEC_USART1_USART_CR1  \ offset: 0x00 : USART control register 1 [alternate]
$50013800 constant SEC_USART1_USART_CR1_ALTERNATE1  \ offset: 0x00 : USART control register 1 [alternate]
$50013804 constant SEC_USART1_USART_CR2  \ offset: 0x04 : USART control register 2
$50013808 constant SEC_USART1_USART_CR3  \ offset: 0x08 : USART control register 3
$5001380c constant SEC_USART1_USART_BRR  \ offset: 0x0C : USART baud rate register
$50013810 constant SEC_USART1_USART_GTPR  \ offset: 0x10 : USART guard time and prescaler register
$50013814 constant SEC_USART1_USART_RTOR  \ offset: 0x14 : USART receiver timeout register
$50013818 constant SEC_USART1_USART_RQR  \ offset: 0x18 : USART request register
$5001381c constant SEC_USART1_USART_ISR  \ offset: 0x1C : USART interrupt and status register [alternate]
$5001381c constant SEC_USART1_USART_ISR_ALTERNATE1  \ offset: 0x1C : USART interrupt and status register [alternate]
$50013820 constant SEC_USART1_USART_ICR  \ offset: 0x20 : USART interrupt flag clear register
$50013824 constant SEC_USART1_USART_RDR  \ offset: 0x24 : USART receive data register
$50013828 constant SEC_USART1_USART_TDR  \ offset: 0x28 : USART transmit data register
$5001382c constant SEC_USART1_USART_PRESC  \ offset: 0x2C : USART prescaler register
$50013830 constant SEC_USART1_USART_AUTOCR  \ offset: 0x30 : USART Autonomous mode control register

