\
\ @file sec_saes.fs
\ @brief Secure AES coprocessor
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

.include ../common.fs

\
\ @brief SAES control register
\ Address offset: 0x00
\ Reset value: 0x00000000
\

$00000001 constant SEC_SAES_SAES_CR_EN                              \ Enable This bit enables/disables the SAES peripheral. At any moment, clearing then setting the bit re-initializes the SAES peripheral. When KMOD[1:0] is different from 00, using IPRST bit is recommended instead. This bit is automatically cleared by hardware upon the completion of the key preparation (MODE[1:0] at 01) and upon the completion of GCM/GMAC/CCM initialization phase. The bit cannot be set as long as KEYVALID=0. The situation is similar for one of the following configurations: 1. KMOD[1:0] at 01 (wrap), CHMOD[2:0] at 11 (GCM) 2. KMOD[1:0] at 01 (wrap), CHMOD[2:0] at 10 (CTR), MODE[1:0] at 00 (encryption).
$00000006 constant SEC_SAES_SAES_CR_DATATYPE                        \ Data type This bitfield defines the format of data written in the SAES_DINR register or read from the SAES_DOUTR register, through selecting the mode of data swapping. This swapping is defined in Section23.4.17: SAES data registers and data swapping. Attempts to write the bitfield are ignored when BUSY is set, as well as when EN is set before the write access and it is not cleared by that write access.
$00000018 constant SEC_SAES_SAES_CR_MODE                            \ Operating mode This bitfield selects the SAES operating mode: Attempts to write the bitfield are ignored when BUSY is set, as well as when EN is set before the write access and it is not cleared by that write access.
$00000060 constant SEC_SAES_SAES_CR_CHMOD                           \ CHMOD[1:0]: Chaining mode This bitfield selects the AES chaining mode: others: Reserved Attempts to write the bitfield are ignored when BUSY is set, as well as when EN is set before the write access and it is not cleared by that write access.
$00000800 constant SEC_SAES_SAES_CR_DMAINEN                         \ DMA input enable When this bit is set, DMA requests are automatically generated by the peripheral during the input data phase. Setting this bit is ignored when MODE[1:0] is at 01 (key derivation).
$00001000 constant SEC_SAES_SAES_CR_DMAOUTEN                        \ DMA output enable When this bit is set, DMA requests are automatically generated by the peripheral during the output data phase. Setting this bit is ignored when MODE[1:0] is at 01 (key derivation).
$00006000 constant SEC_SAES_SAES_CR_GCMPH                           \ GCM or CCM phase selection This bitfield selects the phase, applicable only with GCM, GMAC or CCM chaining modes. This bitfield has no effect if GCM, GMAC or CCM algorithm is not selected with CHMOD[2:0].
$00010000 constant SEC_SAES_SAES_CR_CHMOD_1                         \ CHMOD[2]
$00040000 constant SEC_SAES_SAES_CR_KEYSIZE                         \ Key size selection This bitfield defines the key length in bits of the key used by SAES. When KMOD[1:0] is at 01 or 10, KEYSIZE also defines the length of the key to encrypt or decrypt. Attempts to write the bit are ignored when BUSY is set, as well as when the EN is set before the write access and it is not cleared by that write access.
$00080000 constant SEC_SAES_SAES_CR_KEYPROT                         \ Key protection When set, hardware-based key protection is enabled. Attempts to write the bit are ignored when BUSY is set, as well as when EN is set before the write access and it is not cleared by that write access.
$00f00000 constant SEC_SAES_SAES_CR_NPBLB                           \ Number of padding bytes in last block This padding information must be filled by software before processing the last block of GCM payload encryption or CCM payload decryption, otherwise authentication tag computation is incorrect. ...
$03000000 constant SEC_SAES_SAES_CR_KMOD                            \ Key mode selection The bitfield defines how the SAES key can be used by the application. KEYSIZE must be correctly initialized when setting KMOD[1:0] different from zero. Others: Reserved With KMOD[1:0] other than zero, any attempt to configure the SAES peripheral for use by an application belonging to a different security domain (such as secure or non-secure) results in automatic key erasure and setting of the KEIF flag. Attempts to write the bitfield are ignored when BUSY is set, as well as when EN is set before the write access and it is not cleared by that write access.
$0c000000 constant SEC_SAES_SAES_CR_KSHAREID                        \ Key share identification This bitfield defines, at the end of a decryption process with KMOD[1:0] at 10 (shared key), which target can read the SAES key registers using a dedicated hardware bus. Others: Reserved Attempts to write the bitfield are ignored when BUSY is set, as well as when EN is set before the write access and it is not cleared by that write access.
$70000000 constant SEC_SAES_SAES_CR_KEYSEL                          \ Key selection The bitfield defines the source of the key information to use in the AES cryptographic core. Others: Reserved (if used, unfreeze SAES with IPRST) When KEYSEL[2:0] is different from zero, selected key value is available in key registers when BUSY bit is cleared and KEYVALID is set in the SAES_SR register. Otherwise, the key error flag KEIF is set. Repeated writing of KEYSEL[2:0] with the same non-zero value only triggers the loading of DHUK or BHK when KEYVALIDis cleared. When the application software changes the key selection by writing the KEYSEL[2:0] bitfield, the key registers are immediately erased and the KEYVALID flag cleared. At the end of the decryption process, if KMOD[1:0] is other than zero, KEYSEL[2:0] is cleared. With the bitfield value other than zero and KEYVALID set, the application cannot transfer the ownership of SAES with a loaded key to an application running in another security context (such as secure, non-secure). More specifically, when security of an access to any register does not match the information recorded by SAES, the KEIF flag is set. Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
$80000000 constant SEC_SAES_SAES_CR_IPRST                           \ SAES peripheral software reset Setting the bit resets the SAES peripheral, putting all registers to their default values, except the IPRST bit itself. Hence, any key-relative data are lost. For this reason, it is recommended to set the bit before handing over the SAES to a less secure application. The bit must be low while writing any configuration registers.


\
\ @brief SAES status register
\ Address offset: 0x04
\ Reset value: 0x00000000
\

$00000002 constant SEC_SAES_SAES_SR_RDERRF                          \ Read error flag This bit is set when an unexpected read to the SAES_DOUTR register occurred. When set RDERRF bit has no impact on the SAES operations. This flag is cleared by setting the RWEIF bit in SAES_ICR register. If RWEIE bit is set in SAES_IER register an interrupt is generated when RDERRF is set. It is cleared by setting the RWEIF bit of the SAES_ICR register.
$00000004 constant SEC_SAES_SAES_SR_WRERRF                          \ Write error flag This bit is set when an unexpected write to the SAES_DINR register occurred. When set WRERRF bit has no impact on the SAES operations. This flag is cleared by setting the RWEIF bit in SAES_ICR register. If RWEIE bit is set in SAES_IER register an interrupt is generated when WRERRF is set. It is cleared by setting the RWEIF bit of the SAES_ICR register.
$00000008 constant SEC_SAES_SAES_SR_BUSY                            \ Busy This flag indicates whether SAES is idle or busy. SAES is flagged as idle when disabled or when the last processing is completed. SAES is flagged as busy when processing a block data, preparing a key (ECB or CBC decryption only), fetching random number from the RNG, or transferring a shared key to target peripheral. When GCM encryption is selected, this flag must be at zero before suspending current process to manage a higher-priority message. BUSY must also be cleared before selecting the GCM final phase.
$00000080 constant SEC_SAES_SAES_SR_KEYVALID                        \ Key valid flag This bit is set by hardware when the key of size defined by KEYSIZE is loaded in SAES_KEYRx key registers. The EN bit can only be set when KEYVALID is set. In normal mode when KEYSEL[2:0] is at 000, the key must be written in the key registers in the correct sequence, otherwise the KEIF flag is set and KEYVALID remains cleared. When KEYSEL[2:0] is different from zero, the BUSY flag is automatically set by SAES. When the key is loaded successfully, BUSY is cleared and KEYVALID set. Upon an error, KEIF is set, BUSY cleared and KEYVALID remains cleared. If set, KEIF must be cleared through the SAES_ICR register, otherwise KEYVALID cannot be set. See the KEIF flag description for more details. For further information on key loading, refer to Section23.4.18: SAES key registers.


\
\ @brief SAES data input register
\ Address offset: 0x08
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_DINR_DIN                           \ Input data word A four-fold sequential write to this bitfield during the Input phase results in writing a complete 16-bytes block of input data to the SAES peripheral. From the first to the fourth write, the corresponding data weights are [127:96], [95:64], [63:32], and [31:0]. Upon each write, the data from the 32-bit input buffer are handled by the data swap block according to the DATATYPE[1:0] bitfield, then written into the AES core 16-bytes input buffer. Reads return zero.


\
\ @brief SAES data output register
\ Address offset: 0x0C
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_DOUTR_DOUT                         \ Output data word This read-only bitfield fetches a 32-bit output buffer. A four-fold sequential read of this bitfield, upon the computation completion (CCF flag set), virtually reads a complete 16-byte block of output data from the SAES peripheral. Before reaching the output buffer, the data produced by the AES core are handled by the data swap block according to the DATATYPE[1:0] bitfield. Data weights from the first to the fourth read operation are: [127:96], [95:64], [63:32], and [31:0].


\
\ @brief SAES key register 0
\ Address offset: 0x10
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_KEYR0_KEY                          \ Cryptographic key, bits [31:0] This write-only bitfield contains the bits [31:0] of the AES encryption or decryption key, depending on the operating mode MODE[1:0] in SAES_CR. The SAES_KEYRx registers may be written only when KEYSIZE value is correct and when the SAES peripheral is disabled (EN bit of the SAES_CR register cleared). A special writing sequence is also required, as described in KEYVALID bit of the SAES_SR register. Note that, if KEYSEL[2:0] is different from 0 and KEYVALID=0, the key is directly loaded to SAES_KEYRx registers (hence writes to key register is ignored and KEIF is set). When KEYVALID is set a write to this register clears KEYVALID if SAES is disabled.


\
\ @brief SAES key register 1
\ Address offset: 0x14
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_KEYR1_KEY                          \ Cryptographic key, bits [63:32] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield. When KEYVALID is set in SAES_SR a write to this register clears KEYVALID if EN is cleared in SAES_CR.


\
\ @brief SAES key register 2
\ Address offset: 0x18
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_KEYR2_KEY                          \ Cryptographic key, bits [95:64] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield. When KEYVALID is set in SAES_SR a write to this register clears KEYVALID if EN is cleared in SAES_CR.


\
\ @brief SAES key register 3
\ Address offset: 0x1C
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_KEYR3_KEY                          \ Cryptographic key, bits [127:96] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield. When KEYVALID is set in SAES_SR a write to this register clears KEYVALID if EN is cleared in SAES_CR.


\
\ @brief SAES initialization vector register 0
\ Address offset: 0x20
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_IVR0_IVI                           \ Initialization vector input, bits [31:0] SAES_IVRx registers store the 128-bit initialization vector or the nonce, depending on the chaining mode selected. This value is updated by the AES core after each computation round (when applicable). Write to this register is ignored when EN bit is set in SAES_SR register


\
\ @brief SAES initialization vector register 1
\ Address offset: 0x24
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_IVR1_IVI                           \ Initialization vector input, bits [63:32] Refer to the SAES_IVR0 register for description of the IVI[128:0] bitfield.


\
\ @brief SAES initialization vector register 2
\ Address offset: 0x28
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_IVR2_IVI                           \ Initialization vector input, bits [95:64] Refer to the SAES_IVR0 register for description of the IVI[128:0] bitfield.


\
\ @brief SAES initialization vector register 3
\ Address offset: 0x2C
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_IVR3_IVI                           \ Initialization vector input, bits [127:96] Refer to the SAES_IVR0 register for description of the IVI[128:0] bitfield.


\
\ @brief SAES key register 4
\ Address offset: 0x30
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_KEYR4_KEY                          \ Cryptographic key, bits [159:128] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield. Writing to this register has no effect when key size is 128-bit (KEYSIZE=0). When KEYVALID is set in SAES_SR a write to this register clears KEYVALID if EN is cleared in SAES_CR.


\
\ @brief SAES key register 5
\ Address offset: 0x34
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_KEYR5_KEY                          \ Cryptographic key, bits [191:160] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield. Writing to this register has no effect when key size is 128-bit (KEYSIZE=0). When KEYVALID is set in SAES_SR a write to this register clears KEYVALID if EN is cleared in SAES_CR.


\
\ @brief SAES key register 6
\ Address offset: 0x38
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_KEYR6_KEY                          \ Cryptographic key, bits [223:192] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield. Writing to this register has no effect when key size is 128-bit (KEYSIZE=0). When KEYVALID is set in SAES_SR a write to this register clears KEYVALID if EN is cleared in SAES_CR.


\
\ @brief SAES key register 7
\ Address offset: 0x3C
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_KEYR7_KEY                          \ Cryptographic key, bits [255:224] Refer to the SAES_KEYR0 register for description of the KEY[255:0] bitfield. Writing to this register has no effect when key size is 128-bit (KEYSIZE=0). When KEYVALID is set in SAES_SR a write to this register clears KEYVALID if EN is cleared in SAES_CR.


\
\ @brief SAES suspend registers
\ Address offset: 0x40
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_SUSPR0_SUSP                        \ Suspend data SAES_SUSPRx registers contain the complete internal register states of the SAES when the CCM processing of the current task is suspended to process a higher-priority task. Refer to Section23.4.8: SAES suspend and resume operations for more details. Read to this register returns zero when EN bit is cleared in SAES_SR register. SAES_SUSPRx registers are not used in other chaining modes than CCM.


\
\ @brief SAES suspend registers
\ Address offset: 0x44
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_SUSPR1_SUSP                        \ Suspend data SAES_SUSPRx registers contain the complete internal register states of the SAES when the CCM processing of the current task is suspended to process a higher-priority task. Refer to Section23.4.8: SAES suspend and resume operations for more details. Read to this register returns zero when EN bit is cleared in SAES_SR register. SAES_SUSPRx registers are not used in other chaining modes than CCM.


\
\ @brief SAES suspend registers
\ Address offset: 0x48
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_SUSPR2_SUSP                        \ Suspend data SAES_SUSPRx registers contain the complete internal register states of the SAES when the CCM processing of the current task is suspended to process a higher-priority task. Refer to Section23.4.8: SAES suspend and resume operations for more details. Read to this register returns zero when EN bit is cleared in SAES_SR register. SAES_SUSPRx registers are not used in other chaining modes than CCM.


\
\ @brief SAES suspend registers
\ Address offset: 0x4C
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_SUSPR3_SUSP                        \ Suspend data SAES_SUSPRx registers contain the complete internal register states of the SAES when the CCM processing of the current task is suspended to process a higher-priority task. Refer to Section23.4.8: SAES suspend and resume operations for more details. Read to this register returns zero when EN bit is cleared in SAES_SR register. SAES_SUSPRx registers are not used in other chaining modes than CCM.


\
\ @brief SAES suspend registers
\ Address offset: 0x50
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_SUSPR4_SUSP                        \ Suspend data SAES_SUSPRx registers contain the complete internal register states of the SAES when the CCM processing of the current task is suspended to process a higher-priority task. Refer to Section23.4.8: SAES suspend and resume operations for more details. Read to this register returns zero when EN bit is cleared in SAES_SR register. SAES_SUSPRx registers are not used in other chaining modes than CCM.


\
\ @brief SAES suspend registers
\ Address offset: 0x54
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_SUSPR5_SUSP                        \ Suspend data SAES_SUSPRx registers contain the complete internal register states of the SAES when the CCM processing of the current task is suspended to process a higher-priority task. Refer to Section23.4.8: SAES suspend and resume operations for more details. Read to this register returns zero when EN bit is cleared in SAES_SR register. SAES_SUSPRx registers are not used in other chaining modes than CCM.


\
\ @brief SAES suspend registers
\ Address offset: 0x58
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_SUSPR6_SUSP                        \ Suspend data SAES_SUSPRx registers contain the complete internal register states of the SAES when the CCM processing of the current task is suspended to process a higher-priority task. Refer to Section23.4.8: SAES suspend and resume operations for more details. Read to this register returns zero when EN bit is cleared in SAES_SR register. SAES_SUSPRx registers are not used in other chaining modes than CCM.


\
\ @brief SAES suspend registers
\ Address offset: 0x5C
\ Reset value: 0x00000000
\

$00000000 constant SEC_SAES_SAES_SUSPR7_SUSP                        \ Suspend data SAES_SUSPRx registers contain the complete internal register states of the SAES when the CCM processing of the current task is suspended to process a higher-priority task. Refer to Section23.4.8: SAES suspend and resume operations for more details. Read to this register returns zero when EN bit is cleared in SAES_SR register. SAES_SUSPRx registers are not used in other chaining modes than CCM.


\
\ @brief SAES interrupt enable register
\ Address offset: 0x300
\ Reset value: 0x00000000
\

$00000001 constant SEC_SAES_SAES_IER_CCFIE                          \ Computation complete flag interrupt enable This bit enables or disables (masks) the SAES interrupt generation when CCF (computation complete flag) is set.
$00000002 constant SEC_SAES_SAES_IER_RWEIE                          \ Read or write error interrupt enable This bit enables or disables (masks) the SAES interrupt generation when RWEIF (read and/or write error flag) is set.
$00000004 constant SEC_SAES_SAES_IER_KEIE                           \ Key error interrupt enable This bit enables or disables (masks) the SAES interrupt generation when KEIF (key error flag) is set.
$00000008 constant SEC_SAES_SAES_IER_RNGEIE                         \ RNG error interrupt enable This bit enables or disables (masks) the SAES interrupt generation when RNGEIF (RNG error flag) is set.


\
\ @brief SAES interrupt status register
\ Address offset: 0x304
\ Reset value: 0x00000000
\

$00000001 constant SEC_SAES_SAES_ISR_CCF                            \ Computation complete flag This flag indicates whether the computation is completed. It is significant only when the DMAOUTEN bit is cleared, and it may stay high when DMAOUTEN is set. CCF bit is cleared when application sets the corresponding bit of AES_ICR register. An interrupt is generated if the CCFIE bit has been previously set in the AES_IER register.
$00000002 constant SEC_SAES_SAES_ISR_RWEIF                          \ Read or write error interrupt flag This read-only bit is set by hardware when a RDERRF or a WRERRF error flag is set in the SAES_SR register. RWEIF bit is cleared when application sets the corresponding bit of SAES_ICR register. An interrupt is generated if the RWEIE bit has been previously set in the SAES_IER register. This flags has no meaning when key derivation mode is selected.
$00000004 constant SEC_SAES_SAES_ISR_KEIF                           \ Key error interrupt flag This read-only bit is set by hardware when key information failed to load into key registers or key register usage is forbidden. Setting the corresponding bit of the SAES_ICR register clears the KEIF and generates interrupt if the KEIE bit of the SAES_IER register is set. KEIF is triggered upon any of the following errors: SAES fails to load the DHUK (KEYSEL[2:0]=001 or 100). SAES fails to load the BHK (KEYSEL[2:0]=010 or 100) respecting the correct order. AES fails to load the key shared by SAES peripheral (KMOD=10). When KEYVALID is set and either KEYPROT is set or KEYSEL[2:0] is other than 000, the security context of the application that loads the key (secure or non-secure) does not match the security attribute of the access to SAES_CR or SAES_DOUT. In this case, KEYVALID and EN bits are cleared. SAES_KEYRx register write does not respect the correct order. (For KEYSIZE=0, SAES_KEYR0 then SAES_KEYR1 then SAES_KEYR2 then SAES_KEYR3 register, or reverse. For KEYSIZE set, SAES_KEYR0 then SAES_KEYR1 then SAES_KEYR2 then SAES_KEYR3 then SAES_KEYR4 then SAES_KEYR5 then SAES_KEYR6 then SAES_KEYR7, or reverse). KEIF must be cleared by the application software, otherwise KEYVALID cannot be set.
$00000008 constant SEC_SAES_SAES_ISR_RNGEIF                         \ RNG error interrupt flag This read-only bit is set by hardware when an error is detected on RNG bus interface (e.g. bad entropy). RNGEIE bit is cleared when application sets the corresponding bit of SAES_ICR register. An interrupt is generated if the RNGEIE bit has been previously set in the SAES_IER register. Clearing this bit triggers the reload of a new random number from RNG peripheral.


\
\ @brief SAES interrupt clear register
\ Address offset: 0x308
\ Reset value: 0x00000000
\

$00000001 constant SEC_SAES_SAES_ICR_CCF                            \ Computation complete flag clear Setting this bit clears the CCF status bit of the SAES_ISR register.
$00000002 constant SEC_SAES_SAES_ICR_RWEIF                          \ Read or write error interrupt flag clear Setting this bit clears the RWEIF status bit of the SAES_ISR register, and clears both RDERRF and WRERRF flags in the SAES_SR register.
$00000004 constant SEC_SAES_SAES_ICR_KEIF                           \ Key error interrupt flag clear Setting this bit clears the KEIF status bit of the SAES_ISR register.
$00000008 constant SEC_SAES_SAES_ICR_RNGEIF                         \ RNG error interrupt flag clear Application must set this bit to clear the RNGEIF status bit in SAES_ISR register.


\
\ @brief Secure AES coprocessor
\
$520c0c00 constant SEC_SAES_SAES_CR  \ offset: 0x00 : SAES control register
$520c0c04 constant SEC_SAES_SAES_SR  \ offset: 0x04 : SAES status register
$520c0c08 constant SEC_SAES_SAES_DINR  \ offset: 0x08 : SAES data input register
$520c0c0c constant SEC_SAES_SAES_DOUTR  \ offset: 0x0C : SAES data output register
$520c0c10 constant SEC_SAES_SAES_KEYR0  \ offset: 0x10 : SAES key register 0
$520c0c14 constant SEC_SAES_SAES_KEYR1  \ offset: 0x14 : SAES key register 1
$520c0c18 constant SEC_SAES_SAES_KEYR2  \ offset: 0x18 : SAES key register 2
$520c0c1c constant SEC_SAES_SAES_KEYR3  \ offset: 0x1C : SAES key register 3
$520c0c20 constant SEC_SAES_SAES_IVR0  \ offset: 0x20 : SAES initialization vector register 0
$520c0c24 constant SEC_SAES_SAES_IVR1  \ offset: 0x24 : SAES initialization vector register 1
$520c0c28 constant SEC_SAES_SAES_IVR2  \ offset: 0x28 : SAES initialization vector register 2
$520c0c2c constant SEC_SAES_SAES_IVR3  \ offset: 0x2C : SAES initialization vector register 3
$520c0c30 constant SEC_SAES_SAES_KEYR4  \ offset: 0x30 : SAES key register 4
$520c0c34 constant SEC_SAES_SAES_KEYR5  \ offset: 0x34 : SAES key register 5
$520c0c38 constant SEC_SAES_SAES_KEYR6  \ offset: 0x38 : SAES key register 6
$520c0c3c constant SEC_SAES_SAES_KEYR7  \ offset: 0x3C : SAES key register 7
$520c0c40 constant SEC_SAES_SAES_SUSPR0  \ offset: 0x40 : SAES suspend registers
$520c0c44 constant SEC_SAES_SAES_SUSPR1  \ offset: 0x44 : SAES suspend registers
$520c0c48 constant SEC_SAES_SAES_SUSPR2  \ offset: 0x48 : SAES suspend registers
$520c0c4c constant SEC_SAES_SAES_SUSPR3  \ offset: 0x4C : SAES suspend registers
$520c0c50 constant SEC_SAES_SAES_SUSPR4  \ offset: 0x50 : SAES suspend registers
$520c0c54 constant SEC_SAES_SAES_SUSPR5  \ offset: 0x54 : SAES suspend registers
$520c0c58 constant SEC_SAES_SAES_SUSPR6  \ offset: 0x58 : SAES suspend registers
$520c0c5c constant SEC_SAES_SAES_SUSPR7  \ offset: 0x5C : SAES suspend registers
$520c0f00 constant SEC_SAES_SAES_IER  \ offset: 0x300 : SAES interrupt enable register
$520c0f04 constant SEC_SAES_SAES_ISR  \ offset: 0x304 : SAES interrupt status register
$520c0f08 constant SEC_SAES_SAES_ICR  \ offset: 0x308 : SAES interrupt clear register

