\
\ @file sec_gtzc1_mpcbb2.fs
\ @brief GTZC1_MPCBB1 address block description
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

.include ../common.fs

\
\ @brief MPCBB control register
\ Address offset: 0x00
\ Reset value: 0x00000000
\

$00000001 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_CR_GLOCK            \ lock the control register of the MPCBB until next reset; This bit is cleared by default and once set, it can not be reset until system reset.
$40000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_CR_INVSECSTATE      \ SRAM clocks security state; This bit is used to define the internal SRAM clocks control in RCC as secure or not.
$80000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_CR_SRWILADIS        \ secure read/write illegal access disable; This bit disables the detection of an illegal access when a secure read/write transaction access a non-secure blocks of the block-based SRAM (secure fetch on non-secure block is always considered illegal).


\
\ @brief GTZC1 SRAMz MPCBB configuration lock register
\ Address offset: 0x10
\ Reset value: 0x00000000
\

$00000001 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_CFGLOCK_SPLCK0      \ Security/privilege configuration lock super-block; This bit is set by software and can be cleared only by system reset.; note that bit [3:2] are reserved on sales type STM32WBA5xEx for MPCBB1.
$00000002 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_CFGLOCK_SPLCK1      \ Security/privilege configuration lock super-block; This bit is set by software and can be cleared only by system reset.; note that bit [3:2] are reserved on sales type STM32WBA5xEx for MPCBB1.
$00000004 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_CFGLOCK_SPLCK2      \ Security/privilege configuration lock super-block; This bit is set by software and can be cleared only by system reset.; note that bit [3:2] are reserved on sales type STM32WBA5xEx for MPCBB1.
$00000008 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_CFGLOCK_SPLCK3      \ Security/privilege configuration lock super-block; This bit is set by software and can be cleared only by system reset.; note that bit [3:2] are reserved on sales type STM32WBA5xEx for MPCBB1.


\
\ @brief GTZC1 MPCBB security configuration for super-block 0 register
\ Address offset: 0x100
\ Reset value: 0xFFFFFFFF
\

$00000001 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC0       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000002 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC1       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000004 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC2       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000008 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC3       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000010 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC4       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000020 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC5       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000040 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC6       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000080 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC7       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000100 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC8       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000200 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC9       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000400 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC10      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000800 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC11      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00001000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC12      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00002000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC13      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00004000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC14      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00008000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC15      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00010000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC16      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00020000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC17      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00040000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC18      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00080000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC19      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00100000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC20      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00200000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC21      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00400000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC22      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00800000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC23      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$01000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC24      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$02000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC25      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$04000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC26      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$08000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC27      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$10000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC28      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$20000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC29      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$40000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC30      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$80000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0_SEC31      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.


\
\ @brief GTZC1 MPCBB security configuration for super-block 1 register
\ Address offset: 0x104
\ Reset value: 0xFFFFFFFF
\

$00000001 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC0       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000002 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC1       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000004 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC2       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000008 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC3       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000010 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC4       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000020 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC5       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000040 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC6       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000080 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC7       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000100 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC8       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000200 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC9       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000400 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC10      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000800 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC11      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00001000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC12      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00002000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC13      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00004000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC14      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00008000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC15      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00010000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC16      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00020000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC17      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00040000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC18      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00080000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC19      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00100000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC20      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00200000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC21      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00400000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC22      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00800000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC23      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$01000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC24      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$02000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC25      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$04000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC26      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$08000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC27      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$10000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC28      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$20000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC29      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$40000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC30      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$80000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1_SEC31      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.


\
\ @brief GTZC1 MPCBB security configuration for super-block 2 register
\ Address offset: 0x108
\ Reset value: 0xFFFFFFFF
\

$00000001 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC0       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000002 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC1       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000004 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC2       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000008 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC3       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000010 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC4       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000020 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC5       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000040 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC6       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000080 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC7       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000100 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC8       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000200 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC9       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000400 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC10      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000800 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC11      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00001000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC12      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00002000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC13      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00004000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC14      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00008000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC15      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00010000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC16      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00020000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC17      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00040000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC18      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00080000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC19      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00100000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC20      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00200000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC21      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00400000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC22      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00800000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC23      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$01000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC24      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$02000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC25      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$04000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC26      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$08000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC27      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$10000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC28      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$20000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC29      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$40000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC30      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$80000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2_SEC31      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.


\
\ @brief GTZC1 MPCBB security configuration for super-block 3 register
\ Address offset: 0x10C
\ Reset value: 0xFFFFFFFF
\

$00000001 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC0       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000002 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC1       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000004 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC2       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000008 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC3       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000010 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC4       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000020 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC5       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000040 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC6       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000080 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC7       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000100 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC8       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000200 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC9       \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000400 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC10      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000800 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC11      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00001000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC12      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00002000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC13      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00004000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC14      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00008000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC15      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00010000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC16      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00020000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC17      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00040000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC18      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00080000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC19      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00100000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC20      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00200000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC21      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00400000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC22      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00800000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC23      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$01000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC24      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$02000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC25      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$04000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC26      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$08000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC27      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$10000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC28      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$20000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC29      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$40000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC30      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$80000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3_SEC31      \ Security configuration for block y (y = 0 to 31) in super block n Unprivileged write to this bit is ignored if PRIVy bit is set in GTZC1_MPCBB_PRIVCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.


\
\ @brief GTZC1 MPCBB privileged configuration for super-block 0 register
\ Address offset: 0x200
\ Reset value: 0xFFFFFFFF
\

$00000001 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV0     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000002 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV1     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000004 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV2     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000008 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV3     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000010 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV4     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000020 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV5     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000040 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV6     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000080 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV7     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000100 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV8     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000200 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV9     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000400 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV10    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000800 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV11    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00001000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV12    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00002000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV13    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00004000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV14    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00008000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV15    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00010000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV16    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00020000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV17    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00040000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV18    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00080000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV19    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00100000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV20    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00200000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV21    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00400000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV22    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00800000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV23    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$01000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV24    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$02000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV25    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$04000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV26    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$08000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV27    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$10000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV28    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$20000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV29    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$40000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV30    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$80000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0_PRIV31    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.


\
\ @brief GTZC1 MPCBB privileged configuration for super-block 1 register
\ Address offset: 0x204
\ Reset value: 0xFFFFFFFF
\

$00000001 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV0     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000002 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV1     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000004 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV2     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000008 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV3     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000010 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV4     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000020 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV5     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000040 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV6     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000080 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV7     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000100 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV8     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000200 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV9     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000400 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV10    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000800 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV11    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00001000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV12    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00002000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV13    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00004000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV14    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00008000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV15    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00010000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV16    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00020000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV17    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00040000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV18    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00080000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV19    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00100000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV20    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00200000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV21    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00400000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV22    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00800000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV23    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$01000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV24    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$02000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV25    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$04000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV26    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$08000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV27    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$10000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV28    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$20000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV29    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$40000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV30    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$80000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1_PRIV31    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.


\
\ @brief GTZC1 MPCBB privileged configuration for super-block 2 register
\ Address offset: 0x208
\ Reset value: 0xFFFFFFFF
\

$00000001 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV0     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000002 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV1     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000004 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV2     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000008 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV3     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000010 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV4     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000020 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV5     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000040 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV6     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000080 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV7     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000100 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV8     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000200 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV9     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000400 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV10    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000800 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV11    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00001000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV12    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00002000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV13    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00004000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV14    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00008000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV15    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00010000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV16    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00020000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV17    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00040000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV18    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00080000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV19    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00100000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV20    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00200000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV21    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00400000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV22    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00800000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV23    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$01000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV24    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$02000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV25    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$04000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV26    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$08000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV27    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$10000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV28    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$20000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV29    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$40000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV30    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$80000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2_PRIV31    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.


\
\ @brief GTZC1 MPCBB privileged configuration for super-block 3 register
\ Address offset: 0x20C
\ Reset value: 0xFFFFFFFF
\

$00000001 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV0     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000002 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV1     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000004 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV2     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000008 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV3     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000010 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV4     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000020 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV5     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000040 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV6     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000080 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV7     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000100 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV8     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000200 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV9     \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000400 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV10    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00000800 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV11    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00001000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV12    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00002000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV13    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00004000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV14    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00008000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV15    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00010000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV16    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00020000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV17    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00040000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV18    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00080000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV19    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00100000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV20    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00200000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV21    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00400000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV22    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$00800000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV23    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$01000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV24    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$02000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV25    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$04000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV26    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$08000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV27    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$10000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV28    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$20000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV29    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$40000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV30    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.
$80000000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3_PRIV31    \ Privileged configuration for block y (y = 0 to 31), belonging to super-block n. Non-secure write to this bit is ignored if SECy bit is set in GTZC1_MPCBB_SECCFGRn. Writes are ignored if SPLCKn bit is set in GTZC1_MPCBB_CFGLOCK.


\
\ @brief GTZC1_MPCBB1 address block description
\
$50033000 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_CR  \ offset: 0x00 : MPCBB control register
$50033010 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_CFGLOCK  \ offset: 0x10 : GTZC1 SRAMz MPCBB configuration lock register
$50033100 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR0  \ offset: 0x100 : GTZC1 MPCBB security configuration for super-block 0 register
$50033104 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR1  \ offset: 0x104 : GTZC1 MPCBB security configuration for super-block 1 register
$50033108 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR2  \ offset: 0x108 : GTZC1 MPCBB security configuration for super-block 2 register
$5003310c constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_SECCFGR3  \ offset: 0x10C : GTZC1 MPCBB security configuration for super-block 3 register
$50033200 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR0  \ offset: 0x200 : GTZC1 MPCBB privileged configuration for super-block 0 register
$50033204 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR1  \ offset: 0x204 : GTZC1 MPCBB privileged configuration for super-block 1 register
$50033208 constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR2  \ offset: 0x208 : GTZC1 MPCBB privileged configuration for super-block 2 register
$5003320c constant SEC_GTZC1_MPCBB2_GTZC1_MPCBB_PRIVCFGR3  \ offset: 0x20C : GTZC1 MPCBB privileged configuration for super-block 3 register

