\
\ @file adc.fs
\ @brief ADC address block description
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

.include ../common.fs

\
\ @brief ADC interrupt and status register
\ Address offset: 0x00
\ Reset value: 0x00000000
\

$00000001 constant ADC_ADC_ISR_ADRDY                                \ ADC ready This bit is set by hardware after the ADC has been enabled (ADEN = 1) and when the ADC reaches a state where it is ready to accept conversion requests. It is cleared by software writing 1 to it.
$00000002 constant ADC_ADC_ISR_EOSMP                                \ End of sampling flag This bit is set by hardware during the conversion, at the end of the sampling phase.It is cleared by software by programming it to 1 .
$00000004 constant ADC_ADC_ISR_EOC                                  \ End of conversion flag This bit is set by hardware at the end of each conversion of a channel when a new data result is available in the ADC_DR register. It is cleared by software writing 1 to it or by reading the ADC_DR register.
$00000008 constant ADC_ADC_ISR_EOS                                  \ End of sequence flag This bit is set by hardware at the end of the conversion of a sequence of channels selected by the CHSEL bits. It is cleared by software writing 1 to it.
$00000010 constant ADC_ADC_ISR_OVR                                  \ ADC overrun This bit is set by hardware when an overrun occurs, meaning that a new conversion has complete while the EOC flag was already set. It is cleared by software writing 1 to it.
$00000080 constant ADC_ADC_ISR_AWD1                                 \ Analog watchdog 1 flag This bit is set by hardware when the converted voltage crosses the values programmed in ADC_TR1 and ADC_HR1 registers. It is cleared by software by programming it to 1.
$00000100 constant ADC_ADC_ISR_AWD2                                 \ Analog watchdog 2 flag This bit is set by hardware when the converted voltage crosses the values programmed in ADC_AWD2TR and ADC_AWD2TR registers. It is cleared by software programming it it.
$00000200 constant ADC_ADC_ISR_AWD3                                 \ Analog watchdog 3 flag This bit is set by hardware when the converted voltage crosses the values programmed in ADC_AWD3TR and ADC_AWD3TR registers. It is cleared by software by programming it to 1.
$00000800 constant ADC_ADC_ISR_EOCAL                                \ End Of Calibration flag This bit is set by hardware when calibration is complete. It is cleared by software writing 1 to it.
$00002000 constant ADC_ADC_ISR_CCRDY                                \ Channel Configuration Ready flag This flag bit is set by hardware when the channel configuration is applied after programming to ADC_CHSELR register or changing CHSELRMOD or SCANDIR. It is cleared by software by programming it to it. Note: When the software configures the channels (by programming ADC_CHSELR or changing CHSELRMOD or SCANDIR), it must wait until the CCRDY flag rises before configuring again or starting conversions, otherwise the new configuration (or the START bit) is ignored. Once the flag is asserted, if the software needs to configure again the channels, it must clear the CCRDY flag before proceeding with a new configuration.


\
\ @brief ADC interrupt enable register
\ Address offset: 0x04
\ Reset value: 0x00000000
\

$00000001 constant ADC_ADC_IER_ADRDYIE                              \ ADC ready interrupt enable This bit is set and cleared by software to enable/disable the ADC Ready interrupt. Note: The software is allowed to write this bit only when ADSTART bit is cleared (this ensures that no conversion is ongoing).
$00000002 constant ADC_ADC_IER_EOSMPIE                              \ End of sampling flag interrupt enable This bit is set and cleared by software to enable/disable the end of the sampling phase interrupt. Note: The software is allowed to write this bit only when ADSTART bit is cleared (this ensures that no conversion is ongoing).
$00000004 constant ADC_ADC_IER_EOCIE                                \ End of conversion interrupt enable This bit is set and cleared by software to enable/disable the end of conversion interrupt. Note: The software is allowed to write this bit only when ADSTART bit is cleared (this ensures that no conversion is ongoing).
$00000008 constant ADC_ADC_IER_EOSIE                                \ End of conversion sequence interrupt enable This bit is set and cleared by software to enable/disable the end of sequence of conversions interrupt. Note: The software is allowed to write this bit only when ADSTART bit is cleared (this ensures that no conversion is ongoing).
$00000010 constant ADC_ADC_IER_OVRIE                                \ Overrun interrupt enable This bit is set and cleared by software to enable/disable the overrun interrupt. Note: The software is allowed to write this bit only when ADSTART bit is cleared (this ensures that no conversion is ongoing).
$00000080 constant ADC_ADC_IER_AWD1IE                               \ Analog watchdog 1 interrupt enable This bit is set and cleared by software to enable/disable the analog watchdog interrupt. Note: The Software is allowed to write this bit only when ADSTART bit is cleared (this ensures that no conversion is ongoing).
$00000100 constant ADC_ADC_IER_AWD2IE                               \ Analog watchdog 2 interrupt enable This bit is set and cleared by software to enable/disable the analog watchdog interrupt. Note: The Software is allowed to write this bit only when ADSTART bit is cleared (this ensures that no conversion is ongoing).
$00000200 constant ADC_ADC_IER_AWD3IE                               \ Analog watchdog 3 interrupt enable This bit is set and cleared by software to enable/disable the analog watchdog interrupt. Note: The Software is allowed to write this bit only when ADSTART bit is cleared (this ensures that no conversion is ongoing).
$00000800 constant ADC_ADC_IER_EOCALIE                              \ End of calibration interrupt enable This bit is set and cleared by software to enable/disable the end of calibration interrupt. Note: The software is allowed to write this bit only when ADSTART bit is cleared (this ensures that no conversion is ongoing).
$00002000 constant ADC_ADC_IER_CCRDYIE                              \ Channel Configuration Ready Interrupt enable This bit is set and cleared by software to enable/disable the channel configuration ready interrupt. Note: The software is allowed to write this bit only when ADSTART bit is cleared (this ensures that no conversion is ongoing).


\
\ @brief ADC control register
\ Address offset: 0x08
\ Reset value: 0x00000000
\

$00000001 constant ADC_ADC_CR_ADEN                                  \ ADC enable command This bit is set by software to enable the ADC. The ADC is effectively ready to operate once the ADRDY flag has been set. It is cleared by hardware when the ADC is disabled, after the execution of the ADDIS command. Note: The software is allowed to set ADEN only when all bits of ADC_CR registers are 0 (ADCAL = 0, ADSTP = 0, ADSTART = 0, ADDIS = 0 and ADEN = 0)
$00000002 constant ADC_ADC_CR_ADDIS                                 \ ADC disable command
$00000004 constant ADC_ADC_CR_ADSTART                               \ ADC start conversion command This bit is set by software to start ADC conversion. Depending on the EXTEN [1:0] configuration bits, a conversion either starts immediately (software trigger configuration) or once a hardware trigger event occurs (hardware trigger configuration). It is cleared by hardware: In single conversion mode (CONT = 0, DISCEN = 0), when software trigger is selected (EXTEN = 00): at the assertion of the end of Conversion Sequence (EOS) flag. In discontinuous conversion mode(CONT = 0, DISCEN = 1), when the software trigger is selected (EXTEN = 00): at the assertion of the end of Conversion (EOC) flag. In all other cases: after the execution of the ADSTP command, at the same time as the ADSTP bit is cleared by hardware. Note: The software is allowed to set ADSTART only when ADEN = 1 and ADDIS = 0 (ADC is enabled and there is no pending request to disable the ADC). Note: After writing to ADC_CHSELR register or changing CHSELRMOD or SCANDIRW, it is mandatory to wait until CCRDY flag is asserted before setting ADSTART, otherwise, the value written to ADSTART is ignored.
$00000010 constant ADC_ADC_CR_ADSTP                                 \ ADC stop conversion command
$10000000 constant ADC_ADC_CR_ADVREGEN                              \ ADC Voltage Regulator Enable This bit is set by software, to enable the ADC internal voltage regulator. The voltage regulator output is available after t<sub>ADCVREG_STUP</sub>. It is cleared by software to disable the voltage regulator. It can be cleared only if ADEN is et to 0. Note: The software is allowed to program this bit field only when the ADC is disabled (ADCAL = 0, ADSTART = 0, ADSTP = 0, ADDIS = 0 and ADEN = 0).
$80000000 constant ADC_ADC_CR_ADCAL                                 \ ADC calibration This bit is set by software to start the calibration of the ADC. It is cleared by hardware after calibration is complete. Note: The software is allowed to set ADCAL only when the ADC is disabled (ADCAL = 0, ADSTART = 0, ADSTP = 0, ADDIS = 0, AUTOFF = 0, and ADEN = 0). Note: The software is allowed to update the calibration factor by writing ADC_CALFACT only when ADEN = 1 and ADSTART = 0 (ADC enabled and no conversion is ongoing).


\
\ @brief ADC configuration register 1
\ Address offset: 0x0C
\ Reset value: 0x00000000
\

$00000001 constant ADC_ADC_CFGR1_DMAEN                              \ Direct memory access enable This bit is set and cleared by software to enable the generation of DMA requests. This allows the DMA controller to be used to manage automatically the converted data. For more details, refer to Section 16.6.5: Managing converted data using the DMA on page 325.
$00000002 constant ADC_ADC_CFGR1_DMACFG                             \ Direct memory access configuration This bit is set and cleared by software to select between two DMA modes of operation and is effective only when DMAEN = 1. For more details, refer to Section 16.6.5: Managing converted data using the DMA on page 325.
$00000004 constant ADC_ADC_CFGR1_SCANDIR                            \ Scan sequence direction This bit is set and cleared by software to select the direction in which the channels is scanned in the sequence. It is effective only if CHSELMOD bit is cleared. Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00000018 constant ADC_ADC_CFGR1_RES                                \ Data resolution These bits are written by software to select the resolution of the conversion.
$00000020 constant ADC_ADC_CFGR1_ALIGN                              \ Data alignment This bit is set and cleared by software to select right or left alignment. Refer to Figure 43: Data alignment and resolution (oversampling disabled: OVSE = 0) on page 323
$000001c0 constant ADC_ADC_CFGR1_EXTSEL                             \ External trigger selection These bits select the external event used to trigger the start of conversion (refer to Table 67: External triggers for details):
$00000c00 constant ADC_ADC_CFGR1_EXTEN                              \ External trigger enable and polarity selection These bits are set and cleared by software to select the external trigger polarity and enable the trigger.
$00001000 constant ADC_ADC_CFGR1_OVRMOD                             \ Overrun management mode This bit is set and cleared by software and configure the way data overruns are managed.
$00002000 constant ADC_ADC_CFGR1_CONT                               \ Single / continuous conversion mode This bit is set and cleared by software. If it is set, conversion takes place continuously until it is cleared. Note: It is not possible to have both discontinuous mode and continuous mode enabled: it is forbidden to set both bits DISCEN = 1 and CONT = 1.
$00004000 constant ADC_ADC_CFGR1_WAIT                               \ Wait conversion mode This bit is set and cleared by software to enable/disable wait conversion mode.<sup>.</sup>
$00008000 constant ADC_ADC_CFGR1_AUTOFF                             \ Auto-off mode This bit is set and cleared by software to enable/disable auto-off mode.<sup>.</sup>
$00010000 constant ADC_ADC_CFGR1_DISCEN                             \ Discontinuous mode This bit is set and cleared by software to enable/disable discontinuous mode. Note: It is not possible to have both discontinuous mode and continuous mode enabled: it is forbidden to set both bits DISCEN = 1 and CONT = 1.
$00200000 constant ADC_ADC_CFGR1_CHSELRMOD                          \ Mode selection of the ADC_CHSELR register This bit is set and cleared by software to control the ADC_CHSELR feature: Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00400000 constant ADC_ADC_CFGR1_AWD1SGL                            \ Enable the watchdog on a single channel or on all channels This bit is set and cleared by software to enable the analog watchdog on the channel identified by the AWDCH[4:0] bits or on all the channels
$00800000 constant ADC_ADC_CFGR1_AWD1EN                             \ Analog watchdog enable This bit is set and cleared by software.
$7c000000 constant ADC_ADC_CFGR1_AWD1CH                             \ Analog watchdog channel selection These bits are set and cleared by software. They select the input channel to be guarded by the analog watchdog. ..... Others: Reserved Note: The channel selected by the AWDCH[4:0] bits must be also set into the CHSELR register.


\
\ @brief ADC configuration register 2
\ Address offset: 0x10
\ Reset value: 0x00000000
\

$00000001 constant ADC_ADC_CFGR2_OVSE                               \ Oversampler Enable This bit is set and cleared by software. Note: The software is allowed to write this bit only when ADEN bit is cleared.
$0000001c constant ADC_ADC_CFGR2_OVSR                               \ Oversampling ratio This bit filed defines the number of oversampling ratio. Note: The software is allowed to write this bit only when ADEN bit is cleared.
$000001e0 constant ADC_ADC_CFGR2_OVSS                               \ Oversampling shift This bit is set and cleared by software. Others: Reserved Note: The software is allowed to write this bit only when ADEN bit is cleared.
$00000200 constant ADC_ADC_CFGR2_TOVS                               \ Triggered Oversampling This bit is set and cleared by software. Note: The software is allowed to write this bit only when ADEN bit is cleared.
$20000000 constant ADC_ADC_CFGR2_LFTRIG                             \ Low frequency trigger mode enable This bit is set and cleared by software. Note: The software is allowed to write this bit only when ADEN bit is cleared.
$c0000000 constant ADC_ADC_CFGR2_CKMODE                             \ ADC clock mode These bits are set and cleared by software to define how the analog ADC is clocked: In all synchronous clock modes, there is no jitter in the delay from a timer trigger to the start of a conversion. Note: The software is allowed to write these bits only when the ADC is disabled (ADCAL = 0, ADSTART = 0, ADSTP = 0, ADDIS = 0 and ADEN = 0).


\
\ @brief ADC sampling time register
\ Address offset: 0x14
\ Reset value: 0x00000000
\

$00000007 constant ADC_ADC_SMPR_SMP1                                \ Sampling time selection 1 These bits are written by software to select the sampling time that applies to all channels. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00000070 constant ADC_ADC_SMPR_SMP2                                \ Sampling time selection 2 These bits are written by software to select the sampling time that applies to all channels. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00000100 constant ADC_ADC_SMPR_SMPSEL0                             \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$00000200 constant ADC_ADC_SMPR_SMPSEL1                             \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$00000400 constant ADC_ADC_SMPR_SMPSEL2                             \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$00000800 constant ADC_ADC_SMPR_SMPSEL3                             \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$00001000 constant ADC_ADC_SMPR_SMPSEL4                             \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$00002000 constant ADC_ADC_SMPR_SMPSEL5                             \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$00004000 constant ADC_ADC_SMPR_SMPSEL6                             \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$00008000 constant ADC_ADC_SMPR_SMPSEL7                             \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$00010000 constant ADC_ADC_SMPR_SMPSEL8                             \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$00020000 constant ADC_ADC_SMPR_SMPSEL9                             \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$00040000 constant ADC_ADC_SMPR_SMPSEL10                            \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$00080000 constant ADC_ADC_SMPR_SMPSEL11                            \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$00100000 constant ADC_ADC_SMPR_SMPSEL12                            \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$00200000 constant ADC_ADC_SMPR_SMPSEL13                            \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$00400000 constant ADC_ADC_SMPR_SMPSEL14                            \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$00800000 constant ADC_ADC_SMPR_SMPSEL15                            \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$01000000 constant ADC_ADC_SMPR_SMPSEL16                            \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$02000000 constant ADC_ADC_SMPR_SMPSEL17                            \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$04000000 constant ADC_ADC_SMPR_SMPSEL18                            \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$08000000 constant ADC_ADC_SMPR_SMPSEL19                            \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$10000000 constant ADC_ADC_SMPR_SMPSEL20                            \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$20000000 constant ADC_ADC_SMPR_SMPSEL21                            \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.
$40000000 constant ADC_ADC_SMPR_SMPSEL22                            \ Channel-x sampling time selection (x = 22 to 0) These bits are written by software to define which sampling time is used. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: Refer to Section 16.3: ADC implementation for the maximum number of channels.


\
\ @brief ADC watchdog threshold register
\ Address offset: 0x20
\ Reset value: 0x0FFF0000
\

$00000fff constant ADC_ADC_AWD1TR_LT1                               \ Analog watchdog 1 lower threshold These bits are written by software to define the lower threshold for the analog watchdog. Refer to Section 16.8: Analog window watchdogs on page 329.
$0fff0000 constant ADC_ADC_AWD1TR_HT1                               \ Analog watchdog 1 higher threshold These bits are written by software to define the higher threshold for the analog watchdog. Refer to Section 16.8: Analog window watchdogs on page 329.


\
\ @brief ADC watchdog threshold register
\ Address offset: 0x24
\ Reset value: 0x0FFF0000
\

$00000fff constant ADC_ADC_AWD2TR_LT2                               \ Analog watchdog 2 lower threshold These bits are written by software to define the lower threshold for the analog watchdog. Refer to Section 16.8: Analog window watchdogs on page 329.
$0fff0000 constant ADC_ADC_AWD2TR_HT2                               \ Analog watchdog 2 higher threshold These bits are written by software to define the higher threshold for the analog watchdog. Refer to Section 16.8: Analog window watchdogs on page 329.


\
\ @brief ADC channel selection register
\ Address offset: 0x28
\ Reset value: 0x00000000
\

$00000001 constant ADC_ADC_CHSELR_CHSEL0                            \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00000002 constant ADC_ADC_CHSELR_CHSEL1                            \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00000004 constant ADC_ADC_CHSELR_CHSEL2                            \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00000008 constant ADC_ADC_CHSELR_CHSEL3                            \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00000010 constant ADC_ADC_CHSELR_CHSEL4                            \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00000020 constant ADC_ADC_CHSELR_CHSEL5                            \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00000040 constant ADC_ADC_CHSELR_CHSEL6                            \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00000080 constant ADC_ADC_CHSELR_CHSEL7                            \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00000100 constant ADC_ADC_CHSELR_CHSEL8                            \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00000200 constant ADC_ADC_CHSELR_CHSEL9                            \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00000400 constant ADC_ADC_CHSELR_CHSEL10                           \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00000800 constant ADC_ADC_CHSELR_CHSEL11                           \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00001000 constant ADC_ADC_CHSELR_CHSEL12                           \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00002000 constant ADC_ADC_CHSELR_CHSEL13                           \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00004000 constant ADC_ADC_CHSELR_CHSEL14                           \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00008000 constant ADC_ADC_CHSELR_CHSEL15                           \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00010000 constant ADC_ADC_CHSELR_CHSEL16                           \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00020000 constant ADC_ADC_CHSELR_CHSEL17                           \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00040000 constant ADC_ADC_CHSELR_CHSEL18                           \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00080000 constant ADC_ADC_CHSELR_CHSEL19                           \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00100000 constant ADC_ADC_CHSELR_CHSEL20                           \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00200000 constant ADC_ADC_CHSELR_CHSEL21                           \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.
$00400000 constant ADC_ADC_CHSELR_CHSEL22                           \ Channel-x selection These bits are written by software and define which channels are part of the sequence of channels to be converted. Refer to Figure 35: ADC connectivity for ADC inputs connected to external channels and internal sources. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing). Note: If CCRDY is not yet asserted after channel configuration (writing ADC_CHSELR register or changing CHSELRMOD or SCANDIR), the value written to this bit is ignored.


\
\ @brief ADC channel selection register
\ Address offset: 0x28
\ Reset value: 0x00000000
\

$0000000f constant ADC_ADC_CHSELR_ALTERNATE1_SQ1                    \ 1st conversion of the sequence These bits are programmed by software with the channel number (0...14) assigned to the 8th conversion of the sequence. 0b1111 indicates end of the sequence. When 0b1111 (end of sequence) is programmed to the lower sequence channels, these bits are ignored. Refer to SQ8[3:0] for a definition of channel selection. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$000000f0 constant ADC_ADC_CHSELR_ALTERNATE1_SQ2                    \ 2nd conversion of the sequence These bits are programmed by software with the channel number (0...14) assigned to the 8th conversion of the sequence. 0b1111 indicates end of the sequence. When 0b1111 (end of sequence) is programmed to the lower sequence channels, these bits are ignored. Refer to SQ8[3:0] for a definition of channel selection. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00000f00 constant ADC_ADC_CHSELR_ALTERNATE1_SQ3                    \ 3rd conversion of the sequence These bits are programmed by software with the channel number (0...14) assigned to the 8th conversion of the sequence. 0b1111 indicates end of the sequence. When 0b1111 (end of sequence) is programmed to the lower sequence channels, these bits are ignored. Refer to SQ8[3:0] for a definition of channel selection. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$0000f000 constant ADC_ADC_CHSELR_ALTERNATE1_SQ4                    \ 4th conversion of the sequence These bits are programmed by software with the channel number (0...14) assigned to the 8th conversion of the sequence. 0b1111 indicates end of the sequence. When 0b1111 (end of sequence) is programmed to the lower sequence channels, these bits are ignored. Refer to SQ8[3:0] for a definition of channel selection. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$000f0000 constant ADC_ADC_CHSELR_ALTERNATE1_SQ5                    \ 5th conversion of the sequence These bits are programmed by software with the channel number (0...14) assigned to the 8th conversion of the sequence. 0b1111 indicates end of the sequence. When 0b1111 (end of sequence) is programmed to the lower sequence channels, these bits are ignored. Refer to SQ8[3:0] for a definition of channel selection. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00f00000 constant ADC_ADC_CHSELR_ALTERNATE1_SQ6                    \ 6th conversion of the sequence These bits are programmed by software with the channel number (0...14) assigned to the 8th conversion of the sequence. 0b1111 indicates end of the sequence. When 0b1111 (end of sequence) is programmed to the lower sequence channels, these bits are ignored. Refer to SQ8[3:0] for a definition of channel selection. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$0f000000 constant ADC_ADC_CHSELR_ALTERNATE1_SQ7                    \ 7th conversion of the sequence These bits are programmed by software with the channel number (0...14) assigned to the 8th conversion of the sequence. 0b1111 indicates end of the sequence. When 0b1111 (end of sequence) is programmed to the lower sequence channels, these bits are ignored. Refer to SQ8[3:0] for a definition of channel selection. Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$f0000000 constant ADC_ADC_CHSELR_ALTERNATE1_SQ8                    \ 8th conversion of the sequence These bits are programmed by software with the channel number (0...14) assigned to the 8th conversion of the sequence. 0b1111 indicates the end of the sequence. When 0b1111 (end of sequence) is programmed to the lower sequence channels, these bits are ignored. ... Note: The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).


\
\ @brief ADC watchdog threshold register
\ Address offset: 0x2C
\ Reset value: 0x0FFF0000
\

$00000fff constant ADC_ADC_AWD3TR_LT3                               \ Analog watchdog 3lower threshold These bits are written by software to define the lower threshold for the analog watchdog. Refer to Section 16.8: Analog window watchdogs on page 329.
$0fff0000 constant ADC_ADC_AWD3TR_HT3                               \ Analog watchdog 3 higher threshold These bits are written by software to define the higher threshold for the analog watchdog. Refer to Section 16.8: Analog window watchdogs on page 329.


\
\ @brief ADC data register
\ Address offset: 0x40
\ Reset value: 0x00000000
\

$0000ffff constant ADC_ADC_DR_DATA                                  \ Converted data These bits are read-only. They contain the conversion result from the last converted channel. The data are left- or right-aligned as shown in Figure 43: Data alignment and resolution (oversampling disabled: OVSE = 0) on page 323. Just after a calibration is complete, DATA[6:0] contains the calibration factor.


\
\ @brief ADC analog watchdog 2 configuration register
\ Address offset: 0xA0
\ Reset value: 0x00000000
\

$00000001 constant ADC_ADC_AWD2CR_AWD2CH0                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00000002 constant ADC_ADC_AWD2CR_AWD2CH1                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00000004 constant ADC_ADC_AWD2CR_AWD2CH2                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00000008 constant ADC_ADC_AWD2CR_AWD2CH3                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00000010 constant ADC_ADC_AWD2CR_AWD2CH4                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00000020 constant ADC_ADC_AWD2CR_AWD2CH5                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00000040 constant ADC_ADC_AWD2CR_AWD2CH6                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00000080 constant ADC_ADC_AWD2CR_AWD2CH7                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00000100 constant ADC_ADC_AWD2CR_AWD2CH8                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00000200 constant ADC_ADC_AWD2CR_AWD2CH9                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00000400 constant ADC_ADC_AWD2CR_AWD2CH10                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00000800 constant ADC_ADC_AWD2CR_AWD2CH11                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00001000 constant ADC_ADC_AWD2CR_AWD2CH12                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00002000 constant ADC_ADC_AWD2CR_AWD2CH13                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00004000 constant ADC_ADC_AWD2CR_AWD2CH14                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00008000 constant ADC_ADC_AWD2CR_AWD2CH15                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00010000 constant ADC_ADC_AWD2CR_AWD2CH16                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00020000 constant ADC_ADC_AWD2CR_AWD2CH17                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00040000 constant ADC_ADC_AWD2CR_AWD2CH18                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00080000 constant ADC_ADC_AWD2CR_AWD2CH19                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00100000 constant ADC_ADC_AWD2CR_AWD2CH20                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00200000 constant ADC_ADC_AWD2CR_AWD2CH21                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00400000 constant ADC_ADC_AWD2CR_AWD2CH22                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 2 (AWD2). Note: The channels selected through ADC_AWD2CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).


\
\ @brief ADC Analog Watchdog 3 Configuration register
\ Address offset: 0xA4
\ Reset value: 0x00000000
\

$00000001 constant ADC_ADC_AWD3CR_AWD3CH0                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00000002 constant ADC_ADC_AWD3CR_AWD3CH1                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00000004 constant ADC_ADC_AWD3CR_AWD3CH2                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00000008 constant ADC_ADC_AWD3CR_AWD3CH3                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00000010 constant ADC_ADC_AWD3CR_AWD3CH4                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00000020 constant ADC_ADC_AWD3CR_AWD3CH5                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00000040 constant ADC_ADC_AWD3CR_AWD3CH6                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00000080 constant ADC_ADC_AWD3CR_AWD3CH7                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00000100 constant ADC_ADC_AWD3CR_AWD3CH8                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00000200 constant ADC_ADC_AWD3CR_AWD3CH9                           \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00000400 constant ADC_ADC_AWD3CR_AWD3CH10                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00000800 constant ADC_ADC_AWD3CR_AWD3CH11                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00001000 constant ADC_ADC_AWD3CR_AWD3CH12                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00002000 constant ADC_ADC_AWD3CR_AWD3CH13                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00004000 constant ADC_ADC_AWD3CR_AWD3CH14                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00008000 constant ADC_ADC_AWD3CR_AWD3CH15                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00010000 constant ADC_ADC_AWD3CR_AWD3CH16                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00020000 constant ADC_ADC_AWD3CR_AWD3CH17                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00040000 constant ADC_ADC_AWD3CR_AWD3CH18                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00080000 constant ADC_ADC_AWD3CR_AWD3CH19                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00100000 constant ADC_ADC_AWD3CR_AWD3CH20                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00200000 constant ADC_ADC_AWD3CR_AWD3CH21                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).
$00400000 constant ADC_ADC_AWD3CR_AWD3CH22                          \ Analog watchdog channel selection These bits are set and cleared by software. They enable and select the input channels to be guarded by analog watchdog 3 (AWD3). Note: The channels selected through ADC_AWD3CR must be also configured into the ADC_CHSELR registers. The software is allowed to write this bit only when ADSTART=0 (which ensures that no conversion is ongoing).


\
\ @brief ADC calibration factor
\ Address offset: 0xB4
\ Reset value: 0x00000000
\

$0000007f constant ADC_ADC_CALFACT_CALFACT                          \ Calibration factor These bits are written by hardware or by software. Once a calibration is complete, they are updated by hardware with the calibration factors. Software can write these bits with a new calibration factor. If the new calibration factor is different from the current one stored into the analog ADC, it is then applied once a new conversion is launched. Just after a calibration is complete, DATA[6:0] contains the calibration factor. Note: Software can write these bits only when ADEN=1 (ADC is enabled and no calibration is ongoing and no conversion is ongoing).


\
\ @brief ADC common configuration register
\ Address offset: 0x308
\ Reset value: 0x00000000
\

$003c0000 constant ADC_ADC_CCR_PRESC                                \ ADC prescaler Set and cleared by software to select the frequency of the clock to the ADC. Other: Reserved Note: Software is allowed to write these bits only when the ADC is disabled (ADCAL = 0, ADSTART = 0, ADSTP = 0, ADDIS = 0 and ADEN = 0).
$00400000 constant ADC_ADC_CCR_VREFEN                               \ V<sub>REFINT</sub> enable This bit is set and cleared by software to enable/disable the V<sub>REFINT</sub>. Note: Software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).
$00800000 constant ADC_ADC_CCR_TSEN                                 \ Temperature sensor enable This bit is set and cleared by software to enable/disable the temperature sensor. Note: Software is allowed to write this bit only when ADSTART = 0 (which ensures that no conversion is ongoing).


\
\ @brief ADC address block description
\
$40012400 constant ADC_ADC_ISR    \ offset: 0x00 : ADC interrupt and status register
$40012404 constant ADC_ADC_IER    \ offset: 0x04 : ADC interrupt enable register
$40012408 constant ADC_ADC_CR     \ offset: 0x08 : ADC control register
$4001240c constant ADC_ADC_CFGR1  \ offset: 0x0C : ADC configuration register 1
$40012410 constant ADC_ADC_CFGR2  \ offset: 0x10 : ADC configuration register 2
$40012414 constant ADC_ADC_SMPR   \ offset: 0x14 : ADC sampling time register
$40012420 constant ADC_ADC_AWD1TR  \ offset: 0x20 : ADC watchdog threshold register
$40012424 constant ADC_ADC_AWD2TR  \ offset: 0x24 : ADC watchdog threshold register
$40012428 constant ADC_ADC_CHSELR  \ offset: 0x28 : ADC channel selection register
$40012428 constant ADC_ADC_CHSELR_ALTERNATE1  \ offset: 0x28 : ADC channel selection register
$4001242c constant ADC_ADC_AWD3TR  \ offset: 0x2C : ADC watchdog threshold register
$40012440 constant ADC_ADC_DR     \ offset: 0x40 : ADC data register
$400124a0 constant ADC_ADC_AWD2CR  \ offset: 0xA0 : ADC analog watchdog 2 configuration register
$400124a4 constant ADC_ADC_AWD3CR  \ offset: 0xA4 : ADC Analog Watchdog 3 Configuration register
$400124b4 constant ADC_ADC_CALFACT  \ offset: 0xB4 : ADC calibration factor
$40012708 constant ADC_ADC_CCR    \ offset: 0x308 : ADC common configuration register

