\
\ @file crs.fs
\ @brief CRS address block description
\
\ This file is auto-generated from SVD file.
\ DO NOT EDIT MANUALLY.
\

.include ../common.fs

\
\ @brief CRS control register
\ Address offset: 0x00
\ Reset value: 0x00004000
\

$00000001 constant CRS_CRS_CR_SYNCOKIE                              \ SYNC event OK interrupt enable
$00000002 constant CRS_CRS_CR_SYNCWARNIE                            \ SYNC warning interrupt enable
$00000004 constant CRS_CRS_CR_ERRIE                                 \ Synchronization or trimming error interrupt enable
$00000008 constant CRS_CRS_CR_ESYNCIE                               \ Expected SYNC interrupt enable
$00000020 constant CRS_CRS_CR_CEN                                   \ Frequency error counter enable This bit enables the oscillator clock for the frequency error counter. When this bit is set, the CRS_CFGR register is write-protected and cannot be modified.
$00000040 constant CRS_CRS_CR_AUTOTRIMEN                            \ Automatic trimming enable This bit enables the automatic hardware adjustment of TRIM bits according to the measured frequency error between two SYNC events. If this bit is set, the TRIM bits are read-only. The TRIM value can be adjusted by hardware by one or two steps at a time, depending on the measured frequency error value. Refer to Section 7.4.4 for more details.
$00000080 constant CRS_CRS_CR_SWSYNC                                \ Generate software SYNC event This bit is set by software in order to generate a software SYNC event. It is automatically cleared by hardware.
$00007f00 constant CRS_CRS_CR_TRIM                                  \ HSI48 oscillator smooth trimming The default value of the HSI48 oscillator smooth trimming is 64, which corresponds to the middle of the trimming interval.


\
\ @brief CRS configuration register
\ Address offset: 0x04
\ Reset value: 0x2022BB7F
\

$0000ffff constant CRS_CRS_CFGR_RELOAD                              \ Counter reload value RELOAD is the value to be loaded in the frequency error counter with each SYNC event. Refer to Section 7.4.3 for more details about counter behavior.
$00ff0000 constant CRS_CRS_CFGR_FELIM                               \ Frequency error limit FELIM contains the value to be used to evaluate the captured frequency error value latched in the FECAP[15:0] bits of the CRS_ISR register. Refer to Section 7.4.4 for more details about FECAP evaluation.
$07000000 constant CRS_CRS_CFGR_SYNCDIV                             \ SYNC divider These bits are set and cleared by software to control the division factor of the SYNC signal.
$30000000 constant CRS_CRS_CFGR_SYNCSRC                             \ SYNC signal source selection These bits are set and cleared by software to select the SYNC signal source (see Table 28): Note: When using USB LPM (Link Power Management) and the device is in Sleep mode, the periodic USB SOF is not generated by the host. No SYNC signal is therefore provided to the CRS to calibrate the HSI48 oscillator on the run. To guarantee the required clock precision after waking up from Sleep mode, the LSE or reference clock on the GPIOs must be used as SYNC signal.
$80000000 constant CRS_CRS_CFGR_SYNCPOL                             \ SYNC polarity selection This bit is set and cleared by software to select the input polarity for the SYNC signal source.


\
\ @brief CRS interrupt and status register
\ Address offset: 0x08
\ Reset value: 0x00000000
\

$00000001 constant CRS_CRS_ISR_SYNCOKF                              \ SYNC event OK flag This flag is set by hardware when the measured frequency error is smaller than FELIM * 3. This means that either no adjustment of the TRIM value is needed or that an adjustment by one trimming step is enough to compensate the frequency error. An interrupt is generated if the SYNCOKIE bit is set in the CRS_CR register. It is cleared by software by setting the SYNCOKC bit in the CRS_ICR register.
$00000002 constant CRS_CRS_ISR_SYNCWARNF                            \ SYNC warning flag This flag is set by hardware when the measured frequency error is greater than or equal to FELIM * 3, but smaller than FELIM * 128. This means that to compensate the frequency error, the TRIM value must be adjusted by two steps or more. An interrupt is generated if the SYNCWARNIE bit is set in the CRS_CR register. It is cleared by software by setting the SYNCWARNC bit in the CRS_ICR register.
$00000004 constant CRS_CRS_ISR_ERRF                                 \ Error flag This flag is set by hardware in case of any synchronization or trimming error. It is the logical OR of the TRIMOVF, SYNCMISS and SYNCERR bits. An interrupt is generated if the ERRIE bit is set in the CRS_CR register. It is cleared by software in reaction to setting the ERRC bit in the CRS_ICR register, which clears the TRIMOVF, SYNCMISS and SYNCERR bits.
$00000008 constant CRS_CRS_ISR_ESYNCF                               \ Expected SYNC flag This flag is set by hardware when the frequency error counter reached a zero value. An interrupt is generated if the ESYNCIE bit is set in the CRS_CR register. It is cleared by software by setting the ESYNCC bit in the CRS_ICR register.
$00000100 constant CRS_CRS_ISR_SYNCERR                              \ SYNC error This flag is set by hardware when the SYNC pulse arrives before the ESYNC event and the measured frequency error is greater than or equal to FELIM * 128. This means that the frequency error is too big (internal frequency too low) to be compensated by adjusting the TRIM value, and that some other action has to be taken. An interrupt is generated if the ERRIE bit is set in the CRS_CR register. It is cleared by software by setting the ERRC bit in the CRS_ICR register.
$00000200 constant CRS_CRS_ISR_SYNCMISS                             \ SYNC missed This flag is set by hardware when the frequency error counter reaches value FELIM * 128 and no SYNC is detected, meaning either that a SYNC pulse was missed, or the frequency error is too big (internal frequency too high) to be compensated by adjusting the TRIM value, hence some other action must be taken. At this point, the frequency error counter is stopped (waiting for a next SYNC), and an interrupt is generated if the ERRIE bit is set in the CRS_CR register. It is cleared by software by setting the ERRC bit in the CRS_ICR register.
$00000400 constant CRS_CRS_ISR_TRIMOVF                              \ Trimming overflow or underflow This flag is set by hardware when the automatic trimming tries to over- or under-flow the TRIM value. An interrupt is generated if the ERRIE bit is set in the CRS_CR register. It is cleared by software by setting the ERRC bit in the CRS_ICR register.
$00008000 constant CRS_CRS_ISR_FEDIR                                \ Frequency error direction FEDIR is the counting direction of the frequency error counter latched in the time of the last SYNC event. It shows whether the actual frequency is below or above the target.
$ffff0000 constant CRS_CRS_ISR_FECAP                                \ Frequency error capture FECAP is the frequency error counter value latched in the time of the last SYNC event. Refer to Section 7.4.4 for more details about FECAP usage.


\
\ @brief CRS interrupt flag clear register
\ Address offset: 0x0C
\ Reset value: 0x00000000
\

$00000001 constant CRS_CRS_ICR_SYNCOKC                              \ SYNC event OK clear flag Writing 1 to this bit clears the SYNCOKF flag in the CRS_ISR register.
$00000002 constant CRS_CRS_ICR_SYNCWARNC                            \ SYNC warning clear flag Writing 1 to this bit clears the SYNCWARNF flag in the CRS_ISR register.
$00000004 constant CRS_CRS_ICR_ERRC                                 \ Error clear flag Writing 1 to this bit clears TRIMOVF, SYNCMISS and SYNCERR bits and consequently also the ERRF flag in the CRS_ISR register.
$00000008 constant CRS_CRS_ICR_ESYNCC                               \ Expected SYNC clear flag Writing 1 to this bit clears the ESYNCF flag in the CRS_ISR register.


\
\ @brief CRS address block description
\
$40006c00 constant CRS_CRS_CR     \ offset: 0x00 : CRS control register
$40006c04 constant CRS_CRS_CFGR   \ offset: 0x04 : CRS configuration register
$40006c08 constant CRS_CRS_ISR    \ offset: 0x08 : CRS interrupt and status register
$40006c0c constant CRS_CRS_ICR    \ offset: 0x0C : CRS interrupt flag clear register

